### ISSUE TITLE
Update to Minimum Cardset script

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC#101]
1) repackage output as a tar.bz2 (same as source download elsewhere)
2) ID script directory and prepend to filename "cardsets_to_bundle". Keep cat command from failing if script is called from another location.
(assumption "cardsets_to_bundle" is always in same directory as script).
3) update .gitignore to exclude archives/folders of cardset work

[min_cards_scripts_change.diff.zip](https://github.com/shlomif/PySolFC/files/2873488/min_cards_scripts_change.diff.zip)

**Comment by shlomif** [comment]
Hi thanks! It should be tar.xz for the dest because it compresses better. I don't see a change to gitignore in the diff. The third change looks good.

**Comment by scottfurry** [comment]
Updated diff here: https://pastebin.com/dk5VMsMJ
Updated gitignore(at project root) to disregard Cardset Folders/archives at any level (recursively ignore folder/archives)

I keep downloading the *.xz archive and getting different checksums on every iteration. I'm getting consistent checksums on the extra cardset archive. I'm not sure if it's archiving xz format or just the archive size, but differing checksums is maddening... maddness, I tell you! (;-)

**Comment by scottfurry** [comment]
Case in point... https://pastebin.com/Unq1C6wf
I'm working on updating the packing for my distro. The same checksum is encountered on the source tarball (dl from GitHub) and the extra cardset tarball(dl from SrcF) each time those tarballs are fetched. However, every time the Minimal card set is downloaded a different checksum is being generated. That's not suppose to happen...as far as I know.

**Comment by scottfurry** [comment]
Checksum foolish has stopped. Getting consistent sum values now. No explanation...

**Comment by shlomif** [comment]
@scottfurry : I think I don't like the direction in this patch, so I'd like to decline and close this bug. Any comments?

**Comment by scottfurry** [comment]
My original problem was resolved somehow(server problems?). I dug into the source as a means to resolve. The patch was partly to fix my problems as well as minor tweaks. You mentioned not wanting to change archive type. Okay. At a minimum, I would encourage change to gitignore to keep tree clean. No objections to closing beyond that.

**Comment by shlomif** [comment]
Applied changes to .gitignore. Thanks!
