### ISSUE TITLE
On MacOS, in 2.6.1, "No cardsets were found"

### ISSUE THREAD

**Issue by kingjon3377** [shlomif/PySolFC#102]
When I try to run the `PySolFC.app` downloaded from [the GitHub 2.6.1 release](https://github.com/shlomif/PySolFC/releases/tag/pysolfc-2.6.1), it throws up a dialog box titled "PySol installation error" with the following text:

> No cardsets were found !!!

> Main data directory is: /Users/kingjon/Downloads/PySolFC.app/Contents/Resources/data

> Please check your PySol installation

The dialog box has only one button, labeled "Quit".

(When I try running `PySolFC.app/Contents/MacOS/PySolFC` directly, it also spews some "config file: validation error" warnings to standard error, but as I didn't see those when I tried renaming my `${HOME}/.PySolFC` directory (but the error dialog was unchanged) I expect they're not related.)

And indeed, this `PySolFC.app` has no `cardset-suchandsuch` directories in its Contents/Resources/data directory. If I copy those directories from the 2.0 `PySolFC.app`, opening the app normally seems to silently hang; running `PySolFC.app/Contents/MacOS/PySolFC` directly works, but spews errors (all "CFURLCopyResourcePropertyForKey failed because it was passed an URL which has no scheme") to the standard error.

**Comment by shlomif** [comment]
@kingjon3377 : thanks for testing. I don't have mac hardware and used travis-ci to prepare a package. Pull-reqs are welcome, and you can try debugging using https://docs.python.org/3/library/pdb.html or https://docs.python.org/3.5/library/trace.html .
