### ISSUE TITLE
No way to get game number on imported layouts

### ISSUE THREAD

**Issue by BlohoJo** [shlomif/PySolFC#103]
There is no way to get the Pysol game number from an imported layout.

If you import a layout, and do a "Save as" or do anything from the "Game" menu, it uses the number from the last game that was NOT imported as a layout.

Is this a bug, or the way it's expected to work?

**Comment by shlomif** [comment]
Hi! Imported layouts are either not present in the pysol canned seed-generated deals or otherwise are hard to find - see https://fc-solve.shlomifish.org/js-fc-solve/find-deal/ . However, the "save as" basename should be "custom" or similar - so there is a bug.

**Comment by shlomif** [comment]
@BlohoJo : I've now tried it with pysolfc 2.6.1 and after an import it gives "freecell-Custom.pso" as the basename. So I cannot reproduce your issue.

**Comment by shlomif** [comment]
Closing for now due to lack of response.
