### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by ghostofiht** [shlomif/PySolFC#107]
Hi,  I make design contributions for open source projects. I have a great logo design idea for PySolFC. You want to see this?

**Comment by shlomif** [comment]
@ghostofiht : yes, please share it as long as its licence is compatible with pysol fc's gplv3-or-later - https://opensource.stackexchange.com/questions/7759/gplv3-explicit-version-number-or-any-later-version-implications

**Comment by ghostofiht** [comment]
Don't worry about the license. The main idea of ​​the design; "Portable card game". That's why I designed the cards in a pocket. I hope you liked it. If you think of any changes, you can say that. I can do that. And please specify the color you prefer.

![pySol](https://user-images.githubusercontent.com/42060713/55581566-db876200-5725-11e9-8ee7-ee7d03249b72.jpg)

![Untitled-2](https://user-images.githubusercontent.com/42060713/55581815-813ad100-5726-11e9-8102-9a3d6f65e727.jpg)
![3](https://user-images.githubusercontent.com/42060713/55581816-813ad100-5726-11e9-9da9-1f52b205349c.jpg)

**Comment by shlomif** [comment]
@ghostofiht : thanks! I had some initial reservations but they were soon gone. I prefer the green colour, but think that the upper dashed line's side should be  more distanced from the upper edge, similar to the other lines. @Programator2 @lufebe16 : what do you think?

**Comment by ghostofiht** [comment]
Sorry about the top dashed line. I arranged it as you wanted. The final version is as follows. If you don't have another change, I'll send you a logo with a PR. ?

![logo_end](https://user-images.githubusercontent.com/42060713/55596662-62eaca80-5752-11e9-810c-dc3f8ad26b85.jpg)

**Comment by shlomif** [comment]
The line looks great now - thanks! Note that I feel that the font used is a little strange-looking. Perhaps use a somewhat different font. I also want to get opinions from more people.

**Comment by Programator2** [comment]
I'm sorry, but I don't like the design. Here are my comments:

- Combination of 3D and 2D - cards are shown in perspective viewed at an angle, but the pocket is viewed straight on. It looks strange to have flat object slapped on 3D object. Logo should be displayed either in perspective or flat, but not both.
- Cards are not main focus - most of the space is taken by the pocket. In smaller sizes (like on the webpage) it looks like a shield. Cards should be more prominent and the pocket should take less space.
- Cards in the pack are not aligned, gaps between cards are not consistent, it looks a bit messy.

**Comment by ghostofiht** [comment]
@Programator2 You may be right.  In fact, my goal was to make the cards look natural by showing them a little messy. I re-edited it for you. And I made the cards come to the fore. I'm here for you. Feel free to let me know your requests.

![edited](https://user-images.githubusercontent.com/42060713/55630218-d5dd5b00-57bd-11e9-91d3-832ac916ac72.jpg)

**Comment by Programator2** [comment]
@ghostofiht Thanks for the update. My favourite is the third version, flat and simple. Let's see what others think.

**Comment by shlomif** [comment]
@ghostofiht : I prefer the rightmost version too.

**Comment by ghostofiht** [comment]
I'm glad you like it. What do you think about font? [Here](https://www.dafont.com/) you can choose from among thousands of fonts. Or you can say any font. This is your logo, guys. We should design according to your preferences.

**Comment by shlomif** [comment]
@ghostofiht : one problem with dafont is that many of the fonts featured there are not open source fonts (see https://opensource.com/life/16/2/top-sources-open-source-fonts ) so one needs to be careful. There are some other font collections in the link. I'll try to see about that.

**Comment by ghostofiht** [comment]
@shlomif I think I need to review the subject of licenses. Thank you for your information. Have you chosen a font?

**Comment by shlomif** [comment]
On Sat, 06 Apr 2019 05:08:48 -0700
ghostofiht <notifications@github.com> wrote:

> @shlomif I think I need to review the subject of licenses. Thank you for your
> information. Have you chosen a font?
> 

Sorry - not yet - I was busy with other projects.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
What does “Zionism” mean? - http://shlom.in/def-zionism

Where they have burned books, they will end in burning human beings.
    — http://en.wikiquote.org/wiki/Heinrich_Heine

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@ghostofiht : I like the Bold variant of https://fontlibrary.org/en/font/trueno . @Programator2 : do you have a favourite?

**Comment by ghostofiht** [comment]
@shlomif Good choice. I applied it so you could see how it looks.

![tipik](https://user-images.githubusercontent.com/42060713/55676052-6eb2ca00-58d5-11e9-9033-587798548005.jpg)

**Comment by shlomif** [comment]
@ghostofiht : looks great IMHO.

**Comment by Programator2** [comment]
It looks good to me.

**Comment by ghostofiht** [comment]
Wonderful ! How about I send a PR? If you report the required dimensions and formats, I can prepare. I also think you will need a favicon.

**Comment by shlomif** [comment]
@ghostofiht : the existing logos can be found on https://github.com/shlomif/PySolFC/tree/master/html-src/images - in low-res .gif format. What we need is RGBA - at least 8 bit per channel (possibly more) and either https://inkscape.org/ SVG , GIMP .xcf, or a high resolution (lowest dimension being roughly 2,048 or above) PNG, lossless https://en.wikipedia.org/wiki/WebP or lossless https://en.wikipedia.org/wiki/OpenEXR - at the proportions of the existing logos. Is this acceptable? Thanks!

**Comment by ghostofiht** [comment]
@shlomif     I've prepared high-resolution PNG and SVG files. (24 bit RGBA). [Here](https://github.com/ghostofiht/PySolFC/tree/master/html-src/images/high_res) you can see. I also changed the existing logo files with the same resolution. From [here](https://github.com/ghostofiht/PySolFC/tree/master/html-src/images/). I thought these were enough.(?) If any, you can convert your other needs from high-resolution PNG and SVG files. If there's no problem, I'll send a PR.

**Comment by shlomif** [comment]
@ghostofiht : thanks! One comment is that the frame of the horizontal .png.svg does not match the image (it should be resized). Otherwise - looks great.

**Comment by ghostofiht** [comment]
@shlomif I edited it again. And I sent a PR. https://github.com/shlomif/PySolFC/pull/109

**Comment by shlomif** [comment]
@ghostofiht : PR merged. Thanks for your contribution and for your persistence. Can we close this issue? If you feel like contributing more then you can try working with the kivy version maintainer about having android-compatible graphics. There seem to be .pngs at:

```
shlomif[PySolFC]:$trunk$ python3 pysol.py
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/new.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/restart.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/open.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/save.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/undo.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/redo.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/autodrop.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/shuffle.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/pause.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/statistics.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/rules.png
file = /usr/share/PySolFC/images/toolbar/bluecurve/small/quit.png
shlomif[PySolFC]:$trunk$ git i 
⇒ On branch master

```

**Comment by ghostofiht** [comment]
@shlomif Thank you. But I prefer to make only logo designs. I wish you success for the PySol project. You can close this issue.

**Comment by shlomif** [comment]
@ghostofiht : thanks! I could use a new logo for https://fc-solve.shlomifish.org/ if you are interested. Closing.

**Comment by ghostofiht** [comment]
@shlomif I'il take care of that. I'il write to you when you're ready.

**Comment by shlomif** [comment]
On Tue, 09 Apr 2019 05:15:27 -0700
ghostofiht <notifications@github.com> wrote:

> @shlomif I'il take care of that. I'il write to you when you're ready.
> 

Thanks! I am ready.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Editors and IDEs - http://shlom.in/IDEs

A fanatic: one who redoubles his efforts after he has forgotten his aim.
    — http://en.wikiquote.org/wiki/George_Santayana
    (via http://esr.ibiblio.org/?p=4371 ).

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by THEtomaso** [comment]
The new icon looks great!
Good job!! :)

Not a big fan of that bold **Arial** font though.
Amongst such standard fonts, I think **Times New Roman** would look better.

**Comment by shlomif** [comment]
On Mon, 15 Apr 2019 03:08:40 -0700
THEtomaso <notifications@github.com> wrote:

> The new icon looks great!
> Good job!! :)
> 
> Not a big fan of that bold **Arial** font though.
> Amongst such standard fonts, I think **Times New Roman** would look better.
> 
> 

It is not Arial, or are you confusing Arial with
https://en.wikipedia.org/wiki/Sans-serif in general?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/shlomif/Freenode-programming-channel-FAQ

If Chuck Norris travelled to the market with his son and his donkey, he would
have clubbed the critics to death. With the donkey.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by THEtomaso** [comment]
Yeah, they're very similar.
Nevertheless, I still don't like it. :)
