### ISSUE TITLE
Not compatible with python-pillow 6.0

### ISSUE THREAD

**Issue by mlmatlock** [shlomif/PySolFC#108]
OS:  Manjaro 18.0.4
Kernel: 5.0.6
pysolfc  2.4.0:  
python:  3.7.3
python-pillow:  6.0.0

Problem:

Update to python-pillow (pulled by upgrade to hplip).  Starting pysol results with:

`
merell@Jammin1 ~]$ pysol &
[1] 7227
[merell@Jammin1 ~]$ Traceback (most recent call last):
  File "/usr/bin/pysol", line 37, in <module>
    from pysollib.main import main  # noqa: E402
  File "/usr/lib/python3.7/site-packages/pysollib/main.py", line 32, in <module>
    from pysollib.util import DataLoader
  File "/usr/lib/python3.7/site-packages/pysollib/util.py", line 30, in <module>
    from pysollib.mfxutil import Image
  File "/usr/lib/python3.7/site-packages/pysollib/mfxutil.py", line 54, in <module>
    if TOOLKIT == 'tk' and Image and Image.VERSION >= '1.1.7':
AttributeError: module 'PIL.Image' has no attribute 'VERSION'

`
Downgrading python-pillow, and pysol runs correctly.

**Comment by shlomif** [comment]
@mlmatlock : hi, please try https://github.com/shlomif/PySolFC/commit/fa20e7f834a1385f383f09a3aa8f4fb4bb86da18

**Comment by mlmatlock** [comment]
@shlomif:  You rock!  fa20e7f fixed this issue!  Thanks!

**Comment by shlomif** [comment]
On Fri, 05 Apr 2019 11:51:31 -0700
mlmatlock <notifications@github.com> wrote:

> @shlomif:  You rock!  fa20e7f fixed this issue!  Thanks!
> 

you're welcome and thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
The Human Hacking Field Guide - http://shlom.in/hhfg

Chuck Norris wrote an interpreter for a Turing-complete language using only
NOPs.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by TonyMorehen** [comment]
Same issue when loading card sets:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pysollib/app.py", line 929, in l
oadCardset
    if not images.load(app=self, progress=progress):
  File "/usr/lib/python3.7/site-packages/pysollib/images.py", line 235, i
n load
    self._getHighlight(self._card[0], None, '#3896f8'))
  File "/usr/lib/python3.7/site-packages/pysollib/images.py", line 341, i
n _getHighlight
    shade = shadowImage(image, color, factor)
  File "/usr/lib/python3.7/site-packages/pysollib/ui/tktile/tkutil.py", l
ine 357, in shadowImage
    if Image.VERSION >= '1.1.7':
AttributeError: module 'PIL.Image' has no attribute 'VERSION'
Terminated

As a quick and very dirty hack, I changed line 357 in tkutil.py from:
if Image.VERSION >= '1.1.7':
to
if Image:
