### ISSUE TITLE
Git Repo for PySolFC Cardsets?

### ISSUE THREAD

**Issue by AntumDeluge** [shlomif/PySolFC#113]
It appears in the [appveyor script](https://github.com/shlomif/PySolFC/blob/de836fe5a06ea8de7627e03185fc94678c27e733/.appveyor.yml#L40) that cardsets are imported for the release tarball on Sourceforge. There is currently no Git repository for PySolFC cardsets?

**Comment by shlomif** [comment]
@AntumDeluge : there is no such git repo currently except perhaps https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets . It should not be hard to set one up.

**Comment by shlomif** [comment]
@AntumDeluge : see https://github.com/shlomif/PySolFC-Cardsets - thanks!

**Comment by AntumDeluge** [comment]
Thank you @shlomif.

**Comment by AntumDeluge** [comment]
Oh, cool! I saw that [GreyWyvern's cardset](http://www.greywyvern.com/?post=183) had been [added to PySolFC](https://github.com/shlomif/PySolFC-Cardsets/blob/917d7a89fb307d1e0bcd7629b96b726b315254e3/cardset-greywyvern/COPYRIGHT), but I didn't realize until just now that it is the set that I ported over.
