### ISSUE TITLE
Unresponsivness caused by long animation sequences

### ISSUE THREAD

**Issue by THEtomaso** [shlomif/PySolFC#116]
### Issue:
During long animation sequences (e.g. when solving a game, and all cards get automatically stacked) the game sometimes freezes and shows a "not responding" message in the title bar.
I've only encountered this issue a couple of times, and on both occasions, the game recovered automatically afterwards.

--

* PySolFC build: v2.6.4
* OS version: Windows 8.1 Pro (x64)

**Comment by shlomif** [comment]
@THEtomaso : can you provide a solitaire variant and its deal number where it happens?

**Comment by THEtomaso** [comment]
It happened once when solving a 'Klondike by Threes' game.
If it happens again, I'll be sure to take notice of the game number.

**Comment by shlomif** [comment]
@THEtomaso : thanks!

**Comment by shlomif** [comment]
Closing for now to avoid clutter.

**Comment by Arcorann** [comment]
Adding more information: this usually happens to me when I'm using Auto Drop. An example is the attached saved game from Triple Easthaven, game 45304189071689859072. When Auto Drop is used in this state on default settings the game gives "not responding" after about 40 cards.

[Triple Easthaven-45304189071689859072_better.zip](https://github.com/shlomif/PySolFC/files/4943371/Triple.Easthaven-45304189071689859072_better.zip)

**Comment by JSBM13** [comment]
I've found that we can fix this issue by calling for a windows update at the end of the loop of _autoPlay() in pysollib/game/__init__.py:

```python
def _autoPlay(self, autofaceup, autodrop, autodeal, sound):
        flipstacks, dropstacks, quickstacks = self.getAutoStacks()
        done_something = 1
        while done_something:
            done_something = 0
            if autofaceup and flipstacks:
                # [...]
            if autodrop and dropstacks:
                # [...]
            if autodeal:
                # [...]
            # This has to be added:
            self.top.update_idletasks()
            self.top.busyUpdate()
        return 0
```

Perhaps only one of those two is necessary, I'm not too sure about it.

**Comment by joeraz** [comment]
I'll try that and see.  Thanks.

**Comment by joeraz** [comment]
It worked.  And adding the same code in another place too limits unresponsiveness while dealing.
