### ISSUE TITLE
Port the kivy version to python 3.x

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#120]
According to https://github.com/kivy/kivy/releases/tag/1.11.0 (which I saw on the recent https://www.pythonweekly.com/ ) kivy will drop support for py 2.x and will be py 3.x-only. py 2.x will be EOLed anyway on 2020.

**Comment by lufebe16** [comment]
Thanks for the hint. I'll keep it in mind.
The Kivy version of PysolFc has been adapted to python 3 earlier. It runs on Linux and also might run on Windows and Mac (not tested due to lack of hardware).
As there was no Android build that supported Python 3, the Android app uses still Python 2.7.

**Comment by shlomif** [comment]
@lufebe16 : thanks for your efforts. What is required to get an android build with Python 3 support?

**Comment by keithbowes** [comment]
Ah, is that the reason that the Kivy interface is so flaky?  I just assumed it was because it wasn't as far along as the Tkinter interface.  Maybe a note should be added to the README not to use the Kivy interface with Python 3 then.

**Comment by shlomif** [comment]
> Ah, is that the reason that the Kivy interface is so flaky? I just assumed it was because it wasn't as far along as the Tkinter interface. Maybe a note should be added to the README not to use the Kivy interface with Python 3 then.

I didn't try the kivy interface a lot, whether with py2 or with py3. Is it less flaky with py2?

**Comment by lufebe16** [comment]
Kivy version has been ported to python 3 erarlier. An android version using python 3 was published ends of october '19 with fdroid. Thanks to @jnumm for his prework. The kivy port runs on all platforms that support python and kivy. It does not (@keithbowes) support all feature and goodies of the tkinter version. The main reason of the port was to bring PysolFC to Android smartphones and tablets.

**Comment by keithbowes** [comment]
Eh, I just wanted to try Kivy for the native Wayland support, as the Tkinter version runs under Xwayland and periodically crashes compositors, but the Kivy version (under Python 3 at least) is buggy and is missing some of the best features of the Tkinter version (e.g. right-clicking cards to move them).

**Comment by shlomif** [comment]
On Mon, 24 Feb 2020 16:55:21 -0800
Keith Bowes <notifications@github.com> wrote:

> Eh, I just wanted to try Kivy for the native Wayland support, as the Tkinter
> version runs under Xwayland and periodically crashes compositors, but the
> Kivy version (under Python 3 at least) is buggy and is missing some of the
> best features of the Tkinter version (e.g. right-clicking cards to move them).
> 

Thanks for trying it, Keith! I hope it can be fixed soon. Do you have a
reproduction recipe?

-- 

Shlomi Fish       https://www.shlomifish.org/
https://youtu.be/KxGRhd_iWuE - Never Give Up!!

 <Su-Shee>  rindolf: yeah because Perl’s crypt() is TOTALLY different from all
            the other crypt()s. ;)
 <rindolf>  Su-Shee: crypts are like snowflakes - no one alike.
  * rindolf has a huge and comprehensive collection of crypts on his disk.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by lufebe16** [comment]
@keithbowes 
The problem has been recognized an added to the pipeline. Thanks for reporting.
But ....
For new problems please open a new issue. This one is closed and has been dedicated to another topic.

**Comment by lufebe16** [comment]
@keithbowes 
The problem has been recognized an added to the pipeline. Thanks for reporting.
But ....
For new problems please open a new issue. This one is closed and has been dedicated to another topic.
