### ISSUE TITLE
Replace pysollib.configobj with configobj from pypi?

### ISSUE THREAD

**Issue by jnumm** [shlomif/PySolFC#122]
It seems like the directory pysollib/configobj is a convenience copy or a fork of [configobj](https://pypi.org/project/configobj/). In the Debian package, there is a [patch to use the packaged version](https://salsa.debian.org/games-team/pysolfc/blob/master/debian/patches/configobj) of configobj, and that's been in place apparently since 2010. (Generally, Debian does not use bundled libraries so that any security vulnerabilities can be patched centrally.)

I can see one complication down the road: when the next release comes (there hasn't been one since 2014) they'll most likely tell you to change your imports: https://github.com/DiffSK/configobj/blob/master/validate.py#L37

According to https://repology.org/project/python:configobj/versions, configobj can be found in many distributions' repositories.

What do you think of replacing pysollib.configobj with pypi's configobj?

**Comment by shlomif** [comment]
Hi!

> It seems like the directory pysollib/configobj is a convenience copy or a fork of [configobj](https://pypi.org/project/configobj/). In the Debian package, there is a [patch to use the packaged version](https://salsa.debian.org/games-team/pysolfc/blob/master/debian/patches/configobj) of configobj, and that's been in place apparently since 2010. (Generally, Debian does not use bundled libraries so that any security vulnerabilities can be patched centrally.)
> 
> I can see one complication down the road: when the next release comes (there hasn't been one since 2014) they'll most likely tell you to change your imports: https://github.com/DiffSK/configobj/blob/master/validate.py#L37
> 

We can try using a try/except hack to avoid that.


> According to https://repology.org/project/python:configobj/versions, configobj can be found in many distributions' repositories.
> 
> What do you think of replacing pysollib.configobj with pypi's configobj?

Sounds good. :+1: I'm all for code reuse and avoiding duplication.
