### ISSUE TITLE
Improve visibility of pysol_cards module revision compatibility

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC#128]
I hadn't realized before that `pysol_cards` was a standalone module. Would be nice to "cheat" and link it into `pysollib/` folder somehow...

Got a traceback message when attempting to execute `pysol.py` (downloaded latest from git and run `setup.py`). Ignored the error initially when doing `gen-html.py`. However, same error message halted `pysol.py`

Traceback message:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pysol.py", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/lib64/python3.6/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/lib64/python3.6/site-packages/pysollib/app.py", line 32, in <module>
    from pysollib.actions import PysolMenubar
  File "/usr/lib64/python3.6/site-packages/pysollib/actions.py", line 28, in <module>
    from pysollib.help import help_about, help_html
  File "/usr/lib64/python3.6/site-packages/pysollib/help.py", line 29, in <module>
    from pysollib.pysoltk import HTMLViewer
  File "/usr/lib64/python3.6/site-packages/pysollib/pysoltk.py", line 45, in <module>
    from pysollib.tile.toolbar import *  # noqa: F401,F403
  File "/usr/lib64/python3.6/site-packages/pysollib/tile/toolbar.py", line 29, in <module>
    from pysollib.ui.tktile.menubar import MfxMenu, createToolbarMenu
  File "/usr/lib64/python3.6/site-packages/pysollib/ui/tktile/menubar.py", line 7, in <module>
    from pysollib.hint import PySolHintLayoutImportError
  File "/usr/lib64/python3.6/site-packages/pysollib/hint.py", line 34, in <module>
    from pysollib.pysolrandom import constructRandom
  File "/usr/lib64/python3.6/site-packages/pysollib/pysolrandom.py", line 38, in <module>
    from pysol_cards.random import match_ms_deal_prefix  # noqa: I100
ImportError: cannot import name 'match_ms_deal_prefix'
```

**Comment by shlomif** [comment]
Bundling it might be useful for the release tarballs. For the git dev version, just upgrade using `pip`.

**Comment by scottfurry** [comment]
That module I can already see as being a pain for package maintainers. Pull in and install another python module unique to a card game. Implementation of pysol_cards module seems like a kludge from my end.

I'll try with pip, but this process can be improved.

**Comment by scottfurry** [comment]
What I find difficult, from past experiences, is that `pip` tends to clash or otherwise interfere with Linux package management. One has to choose - update python packages w/ `pip` or with distribution's packaging - but not both. I think I have a workaround for my use case, but other than `PySolFC`, is there a need for a stand-alone module? Has consideration been given to statement of `pysol_cards` versioning compatibility against `PySolFC` versioning? Seems like a bit of extra work for questionable gains - unless I'm missing something...

**Comment by scottfurry** [comment]
When I built up the package and tripped over the problem above, I did a `quick fix` by installing packaging from distribution. When error message above occurred, I had installed pysol_cards at revision 0.6.2 and ran pysolfc git latest against it. The problem went away when I installed latest pysol_cards from git.

This makes obvious to me that some statement of compatibility about version between pysol_cards and pysolfc is needed in supporting documentation.

**Comment by shlomif** [comment]
> What I find difficult, from past experiences, is that `pip` tends to clash or otherwise interfere with Linux package management. One has to choose - update python packages w/ `pip` or with distribution's packaging - but not both.

There is `--user` and `virtualenv`.

> I think I have a workaround for my use case, but other than `PySolFC`, is there a need for a stand-alone module? Has consideration been given to statement of `pysol_cards` versioning compatibility against `PySolFC` versioning? Seems like a bit of extra work for questionable gains - unless I'm missing something...

We also use it for the board generators at https://github.com/shlomif/fc-solve/tree/master/fc-solve/source/board_gen and it may find use by others. It is also under a more permissive licence.

**Comment by shlomif** [comment]
I guess I can try requiring a certain version of pysol_cards.

**Comment by shlomif** [comment]
@scottfurry : can we close this bug now?

**Comment by scottfurry** [comment]
I think we can.

**Comment by shlomif** [comment]
@scottfurry : thanks!
