### ISSUE TITLE
New name and promotion

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#13]
When you finish porting PySolFC to Python 3 and you add SVG support (to make PySolFC resolution-independent), you can definitely think about a name change. My suggestion is: **PySol+** (BTW, PySolFC was a strange name in the first place).

That would be the right time to think about promotion too:

-- create a very simple website using: https://pages.github.com/ Including info on your efforts as well as on PySol's history and legacy.

--  tell people that PySol is still alive in the form of PySol+ using reddit, Hacker News, Slashdot, and GamingOnLinux (these website are frequented by those who are "in the know", they gonna tell the others about the project). A lot of users are really nostalgic about PySol, but they simply don't know that your repo exists. It took me some time to find it as well.

-- create a Patreon account (nice example: https://www.patreon.com/Nekotekina) to earn some cash because why not?

**Comment by shlomif** [comment]
Hi Jan,

On Sun, 02 Apr 2017 05:54:19 -0700
Jan Kleks <notifications@github.com> wrote:

> When you finish porting PySolFC to Python 3 and you add SVG support (to make
> PySolFC resolution-independent), 

this will take a while and I'm seeking people to help me.

> you can definitely think about a name
> change. My suggestion is: **PySol+** (BTW, PySolFC was a strange name in the
> first place).
>

Possibly, and some people think it's related to FreeCell. I'll think about a
name change but I don't like PySol+.

> That would be the right time to think about promotion too:
> 
> -- create a very simple website using: https://pages.github.com/ Including
> info on your efforts as well as on PySol's history and legacy.
> 

a website is a good idea. I can host it elsewhere but using GitHub pages may
not be too bad.

> --  tell people that PySol is still alive in the form of PySol+ using reddit,
> Hacker News, Slashdot, and GamingOnLinux (these website are frequented by
> those who are "in the know", they gonna tell the others about the project). A
> lot of users are really nostalgic about PySol, but they simply don't know
> that your repo exists. It took me some time to find it as well.

Yes, there are other venues as well such as the Python Weekly newsletter.

> 
> -- create a Patreon account (nice example:
> https://www.patreon.com/Nekotekina) to earn some cash because why not?
> 

I'll read about Patreon.

----

Nonetheless, the priority now is to convert the code to Python 3. Do you know
anyone who can help with that?

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Humour - http://perl-begin.org/humour/

XSLT is the number one cause of programmers’ suicides since Visual Basic 1.0.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

**Comment by jan-kleks** [comment]
You're "da boss" here, the new name does not even have to refer to Python actually. Maybe when thinking about the new name you should also take into consideration that PySolFC does Mahjong and other non-card solitaire stuff too?

Hmm... I think you could already use reddit, Hacker News and Slashdot to ask for help with programming (I'm not kidding there are really a lot of knowledgeable folks there). You just need to remind people about PySolFC, tell what you have done so far and that you want to make PySolFC compatible with modern systems. Possilby GNOME or KDE projects would be interested in adopting PySolFC (or at least some of their programmers)? Check their mailing lists.

Let's not forget that if PySolFC become modernized it would easily compete with the largest solitaire packages on the market such as [Pretty Good Solitaire](http://www.goodsol.com/) or [BVS Solitaire Collection](http://www.bvssolitaire.com) and this is a big deal.

**Comment by jan-kleks** [comment]
BTW, I have just discovered on GitHub this very nice on-line solitaire collection called [solitaire.gg](https://github.com/KyleU/solitaire.gg/). You should definitely check it out!

I have even told the developer about PySolFC in one of the comments and they seem to like it. Maybe you could share some code or cooperate in other areas?

**Comment by shlomif** [comment]
On Sun, 02 Apr 2017 13:08:30 -0700
Jan Kleks <notifications@github.com> wrote:

> BTW, I have just discovered on GitHub this very nice on-line solitaire
> collection called [solitaire.gg](https://github.com/KyleU/solitaire.gg/). You
> should definitely check it out!
>

There's also https://github.com/shlomif/Solitairey which is open source too
and is written in JS instead of Scala. I used it as the basis for a project.
 
> I have even told the developer about PySolFC in one of the comments and they
> seem to like it. Maybe you could share some code or cooperate in other areas?
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Free (Creative Commons) Music Downloads, Reviews and more - http://jamendo.com/

Real men don’t listen to sentences that start with “Real men don’t”.
    — http://whatsup.org.il/article/6023

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jan-kleks** [comment]
So have you finally considered asking for help in these places I wrote about in this comment?: https://github.com/shlomif/PySolFC/issues/13#issuecomment-291009852 

Yeah, it was a nice idea to ask for help at: https://groups.google.com/forum/#!topic/python-il/7RCZuFNkl0g But I'm afraid not enough people are visiting this list...

**Comment by shlomif** [comment]
@jan-kleks : hi! I'm OK with asking for help at those places, but will have to dedicate some time for that. Would you like to take these help requests upon yourself? This will help a lot.

**Comment by jan-kleks** [comment]
Okay, I will do this.

**Comment by jan-kleks** [comment]
I started with Hacker News: https://news.ycombinator.com/item?id=14059434

There is already a first comment: "Sweet! I'd love to contribute. There doesn't seem to be a contribution guide or timeline in the repo. I'd suggest adding a list of modules which require refactoring."

Join the discussion, shlomif, please.

**Comment by mcdemarco** [comment]
How about PySol3?

**Comment by Wombatpm** [comment]
Is there a priority List or a list of tickets to work on.  I'm happy to help just don't want to conflict with someone else's branch.  Essentially, I guess I'm asking how is effort being coordinated?

**Comment by shlomif** [comment]
On Fri, 07 Apr 2017 07:58:15 -0700
"M. C. DeMarco" <notifications@github.com> wrote:

> How about PySol3?
> 

there was a version 3.x of PySol before version 4.x and the many forks thereof
that culminated in PySol FC (which this repo in turn is a fork of).

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Parody of "The Fountainhead" - http://shlom.in/towtf

As every cat owner knows, nobody owns a cat.
    — Source unknown, via Nadav Har’El.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi,

On Fri, 07 Apr 2017 08:25:43 -0700
Wombatpm <notifications@github.com> wrote:

> Is there a priority List or a list of tickets to work on.  I'm happy to help
> just don't want to conflict with someone else's branch.  Essentially, I guess
> I'm asking how is effort being coordinated?
> 

the current top priority ticket is
https://github.com/shlomif/PySolFC/issues/11 .

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Humour - http://perl-begin.org/humour/

He who reinvents the wheel, may actually invent a much better wheel.
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jan-kleks** [comment]
Hmm... Maybe not "Pysol3", but I was thinking, if there was PySol 4 and then PySolFC (let's say it's PySol 5) possibly we could consider after porting to Python 3 going back to the simple PySol name and using 6.00 as a version number. Why do I think this might a good idea?

1) Let's not forget that PySol is **almost 20 years old**! That's quite a legacy. The old name would underline this long history (BTW, we need a detailed website section describing all the contributors, forks, etc.)

2) There were already quite a few forks of PySol with different names (PySolitaire, UltraSol, FlowerSol, and obviously PySol Fan Club Edition), recycling the old name might be seen as a way of unifying PySol development efforts which is a really positive thing.

3) The high version number "6.00" would mean that the application is mature (and in fact it is, with so many solitaires and features). Not that I want to begin the versioning war, but other solitaire suits have already passed the version number "10" for quite some time.

4) I wonder if Markus F.X.J. Oberhumer still needs the pysol.org domain... :P  

Of course, we can always keep the PySolFC name or think of a new one. So here you go.

**Comment by jan-kleks** [comment]
I've found this [nice history of PySol](http://solitaire.vegard2.net/pysol.html). I meant exactly something like this when talking about the PySol history web section.

**Comment by jan-kleks** [comment]
Okay, so after promoting your PySolFC branch on Hacker News and Reddit quite a few people have starred the project (I actually don't remember how many stars there were before :P). Let's see if this with result in more developers joining the project in the long term...

Have you considered asking for help via your Twitter, or you don't want to spam your account with this, possibly?. We can also think about _the second wave of promotion_ in the future.

BTW, does this IRC PySol allow for storing conversation history (I think this is important when it comet to development purposes).

**Comment by jan-kleks** [comment]
This discussion can be continued in [the Google Group for discussing open source card games](https://groups.google.com/forum/#!forum/foss-card-games).
