### ISSUE TITLE
All cardsets duplicated in PySolFC-Cardsets--Minimal-2.0.tar.xz

### ISSUE THREAD

**Issue by jnumm** [shlomif/PySolFC#135]
PySolFC-Cardsets--Minimal-2.0.tar.xz downloaded from https://sourceforge.net/projects/pysolfc/files/PySolFC-Cardsets/minimal/ contains duplicated cardset data.

For example, the directory `PySolFC-Cardsets--Minimal-2.0/cardset-mughal-ganjifa` contains the gif files, as well as the subdirectory `PySolFC-Cardsets--Minimal-2.0/cardset-mughal-ganjifa/cardset-mughal-ganjifa/` with all the same gif files.

As I'm writing this, and looked at scripts/repack-min-cardsets.bash, I think I found a solution to prevent this in the future. I'll submit a PR.

Please upload a fixed version of minimal cardsets to SF.net, preferably under a new filename.

**Comment by shlomif** [comment]
Thanks @jnumm ! Please check the 2.0.1 tarball at https://sourceforge.net/projects/pysolfc/files/PySolFC-Cardsets/minimal/ .

Also note that I want to give you a git push permissions, but it requires github sudo mode. In the meanwhile, you may wish to peruse http://web-cpan.shlomifish.org/offers/o-and-m-2006-08/ .

**Comment by jnumm** [comment]
Thanks! The 2.0.1 tarball seems to have no unexpected directories.

`git grep Minimal` shows that Travis CI's macOS build uses Cardsets--Minimal-2.0, perhaps it could be updated to 2.0.1 as well.

Learning of your plans to trust me with push permissions, I feel very valued. Not sure what you mean with github sudo mode though. The O&M offer is nice and something I'll consider.
