### ISSUE TITLE
Missing Game Entry

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC#140]
I switched from having ver2.6.4 to latest git release installed. Preferences were not cleared.
In my preferences, I had a listing of favorite games to play. I selected today "Picture Gallery" only for the game window to refresh and present a "Klondike" setup - but not the game selected.

My suspicion is that some time recently, the game database was redone, games are still registered, but the entry in a menu is not directed properly to the correct game class. Instead the base foundation is presented.

Diagnosing the problem.

**Comment by scottfurry** [comment]
Digging...

At the bottom of file `[project root]/pysollib/games/picturegallery.py` are numerous `registerGame` functions. From the command line, I used `pysol.py --gameid=7` (gameId given to "Picture Gallery".

PysolFC responded with a new foundation and card deal, but again for "Klondike". However, this time the game returned debugging details:

```
 $ pysol.py --gameid=7
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pysollib/app.py", line 230, in _main_loop
    self.runGame(id_, random)
  File "/usr/lib/python3.7/site-packages/pysollib/app.py", line 408, in runGame
    self.game.create(self)
  File "/usr/lib/python3.7/site-packages/pysollib/game/__init__.py", line 423, in create
    self.createGame()
  File "/usr/lib/python3.7/site-packages/pysollib/games/picturegallery.py", line 220, in createGame
    s.addattr(tableaux=[])     # register extra stack variable
AttributeError: 'GameStacks' object has no attribute 'addattr'
```

**Comment by shlomif** [comment]
@scottfurry : thanks for the report, please try latest git master.

**Comment by scottfurry** [comment]
Winner!!! Thanks for the fix!
