### ISSUE TITLE
[Patch] 13-pile Bisley

### ISSUE THREAD

**Issue by qunka** [shlomif/PySolFC#148]
Bisley as implemented in PySolFC (12 piles à 4 cards) differs from the description given at Wikipedia (4 piles à 3, 9 piles à 4). After a bit of hacking I made this plugin which adds 13-pile Bisley and can be dropped in `.PySolFC/plugins`. You can integrate it into the next release of PySolFC if you want.

https://gist.github.com/qunka/3adac1878b481eb419ff6f3e1726add5

**Comment by shlomif** [comment]
On Mon, 06 Jan 2020 16:22:37 -0800
qunka <notifications@github.com> wrote:

> Bisley as implemented in PySolFC (12 piles à 4 cards) differs from the
> description given at Wikipedia (4 piles à 3, 9 piles à 4). After a bit of
> hacking I made this plugin which adds 13-pile Bisley and can be dropped in
> `.PySolFC/plugins`. You can integrate it into the next release of PySolFC if
> you want.
> 
> https://gist.github.com/qunka/3adac1878b481eb419ff6f3e1726add5
> 

Thanks, qunka! I shall look into it.

-- 

Shlomi Fish       https://www.shlomifish.org/
Humanity - Parody of Modern Life - https://shlom.in/humanity

Only three things are infinite: the universe, human stupidity, and the amount
of patience that Windows Update requires.
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Merged in - thanks! Closing.
