### ISSUE TITLE
README references PKGDIR, but PKGTREE is used instead

### ISSUE THREAD

**Issue by LEdoian** [shlomif/PySolFC#149]
The current README.md in the "Installing from source and running in a python venv" section instructs to export the `PKDGIR` variable, but the contrib/install-pysol.sh uses `PKGTREE` variable, leading to crash on line 7, where `env` does not find the respective path. Setting PKGTREE makes this line pass successfully (I've some more trouble with running the script, so I cannot confirm whether it is sufficient).

This occurs only when PKGDIR other than `/usr/local/packages/PySolFC` is used (since in that case the default PKGTREE is what is expected).

I haven't read the code further (yet), so there may be multiple places where wrong environment variable is used.

OS: Arch Linux
Python v.3.8.1
PKGDIR tried: `/home/ledoian/Dev/PySolFC`

**Comment by jnumm** [comment]
Hi LEdoian,

Please check out the latest master branch with updated README and script and let me know if you can now use the venv script successfully.

**Comment by shlomif** [comment]
Closing as fixed due to lack of response.
