### ISSUE TITLE
Unable to install: "No cardsets were found"

### ISSUE THREAD

**Issue by davidlowryduda** [shlomif/PySolFC#15]
I am unable to follow the installation description and successfully run pysol from the github repo.

I have performed the following steps, taken from the brief installation description in the readme.

```
$ git clone https://github.com/shlomif/PySolFC.git
$ cd PySolFC
$ ln -s html-src html
$ ln -s data/images images
$ tar -xvf PySolFC-Cardsets-2.0.tar.bz2
$ mkdir -p ~/.PySolFC
$ rmdir ~/.PySolFC/cardsets
$ ln -s ~/.PySolFC/cardsets PySolFC-Cardsets-2.0
```

When I then run `python2 pysol.py`, I get the "No cardsets were found" error.

I'll note that I have python and tkinter. I did download the cardsets from sourceforge. I'm not sure about the intention of the final symbolic link, but I tried several variations of this symlink and I didn't succeed.

**Comment by shlomif** [comment]
Hi @davidlowryduda ! Thanks for reporting that. Here are some requests:

1. What is your operating system / distribution and its versions?

2. Can you provide the output of this command when ran instead of the final command:

```
strace -o ~/pysol.strace -f python2 pysol.py
```

and give me ~/pysol.strace . I'll also try to reproduce it inside a VM.

**Comment by saltycraig** [comment]
Hi @davidlowryduda I had the same problem, on OS X Sierra. I get the following traceback:

` 
Traceback (most recent call last):
  File "/Users/craig/workspace/envs/pysol2.7/PySolFC/pysollib/main.py", line 171, in pysol_init
    try: os.makedirs(d)
  File "/Users/craig/workspace/envs/pysol2.7/bin/../lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/craig/.PySolFC/cardsets'
`

I fixed it myself by removing the symbolic link from the final step and just copying the downloaded cardsets into ~/.PySolFC/cardsets.

**Comment by davidlowryduda** [comment]
@saltycraig Thank you. Directly placing the downloaded cardsets does indeed fix this.
