### ISSUE TITLE
pysollib.tile.ttk vs standard library tkinter.ttk

### ISSUE THREAD

**Issue by jnumm** [shlomif/PySolFC#150]
To avoid having to maintain a fork of a standard library, it should be investigated if https://github.com/shlomif/PySolFC/blob/master/pysollib/tile/ttk.py can be replaced by using system-provided ttk (whose source is https://github.com/python/cpython/blob/master/Lib/tkinter/ttk.py).

**Comment by shlomif** [comment]
@jnumm :+1: I agree!

**Comment by shlomif** [comment]
@jnumm: haven't you fixed it since? Can this issue be closed?

**Comment by jnumm** [comment]
@shlomif: Yes I have.

Closing the issue because the operation was completed without complications.
