### ISSUE TITLE
Release PySolFC 2.8.0

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#151]
It's been a while since version 2.6.0 and even 2.6.4, so I'd like to release a new version. If there are any issue reports (or alternatively unreported problems) please mention them here so they will block the upcoming release.

**Comment by jnumm** [comment]
Issue #153 should block the release IMO.

**Comment by shlomif** [comment]
Thanks @jnumm ! Does anyone have any other blocker bugs or can we proceed in making the release?

**Comment by shlomif** [comment]
Since there were no objections, I am proceeding with the 2.8.0 release now. I expect most major breakages to be reported after a stable release anyway.

**Comment by shlomif** [comment]
Released now. Closing.
