### ISSUE TITLE
Playable Preview: AttributeError: 'Application' object has no attribute 'comments'

### ISSUE THREAD

**Issue by jnumm** [shlomif/PySolFC#153]
Having started `python3 pysol.py` in a terminal, the following warning is shown when I open the Select -> Playable Preview... window:

```
$ python3 pysol.py 
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/juhani/Projektit/PySolFC/pysollib/ui/tktile/menubar.py", line 1033, in mSelectGameDialogWithPreview
    bookmark=bookmark)
  File "/home/juhani/Projektit/PySolFC/pysollib/tile/selectgame.py", line 429, in __init__
    self.updatePreview(gameid, animations=0)
  File "/home/juhani/Projektit/PySolFC/pysollib/tile/selectgame.py", line 486, in updatePreview
    comments=self.app.comments.new(),
AttributeError: 'Application' object has no attribute 'comments'
```

The selection window is shown on the screen, but its play area remains empty of any cards. Clicking on either the Rules or Select button then closes down the whole application.

**Comment by jnumm** [comment]
I just pushed a fix for this and some related issues in master.

**Comment by shlomif** [comment]
On Mon, 02 Mar 2020 04:40:15 -0800
Juhani Numminen <notifications@github.com> wrote:

> I just pushed a fix for this and some related issues in master.
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Self-Sufficiency/

Only dead fish go with the flow.
    — via Nadav Har’El

Please reply to list if it's a mailing list post - http://shlom.in/reply .
