### ISSUE TITLE
[SOLVED] TypeError: attrib() got an unexpected keyword argument 'factory'

### ISSUE THREAD

**Issue by radub7** [shlomif/PySolFC#159]
I run Ubuntu 18.04.4 and I've downloaded the 2.8.0 tarball. When I try to run it , I get the errors below:
```python ./pysol.py
PySolFC: WARNING: config file: validation error: section: "general", key: "language"
Traceback (most recent call last):
  File "./pysol.py", line 41, in <module>
    sys.exit(main(sys.argv))
  File "/home/radub7/PySolFC-2.8.0/pysollib/main.py", line 422, in main
    r = pysol_init(app, args)
  File "/home/radub7/PySolFC-2.8.0/pysollib/main.py", line 237, in pysol_init
    import pysollib.games
  File "/home/radub7/PySolFC-2.8.0/pysollib/games/__init__.py", line 23, in <module>
    from . import acesup  # noqa: F401
  File "/home/radub7/PySolFC-2.8.0/pysollib/games/acesup.py", line 23, in <module>
    from pysollib.game import Game
  File "/home/radub7/PySolFC-2.8.0/pysollib/game/__init__.py", line 266, in <module>
    class StackGroups(NewStruct):
  File "/home/radub7/PySolFC-2.8.0/pysollib/game/__init__.py", line 267, in StackGroups
    dropstacks = attr.ib(factory=list)
TypeError: attrib() got an unexpected keyword argument 'factory'```

**Comment by shlomif** [comment]
Hi @radub7 ! You likely need to upgrade [attrs](https://pypi.org/project/attrs/). Try running `pip3 install --user --upgrade attrs`.

**Comment by radub7** [comment]
Yes, that was the problem! Thank you @shlomif

**Comment by shlomif** [comment]
I'm reopening this issue due to the first tip in [this essay](https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/) - the one about fixing user problems permanently.

**Comment by sergiomb2** [comment]
Hello,
I hit this problem on Centos 7 , I don't think I can update python-attrs on EPEL 7  , because   EL7 is near EOL (more or less in 2 years) and people don't want hear about it .
So can we workaround PySolFC-2.15.0 to not use factory and just use it on EL 7 ? or should I go back to PySolFC-2.14.0 on EPEL 7 ? 

Thank you 


https://src.fedoraproject.org/rpms/python-attrs/commits/epel7

**Comment by sergiomb2** [comment]
huch , I just checked and PySolFC-2.8.0-2.el7 already requires python-attrs 18.2.0

**Comment by joeraz** [comment]
This looks like it's been fixed with the attrs version requirement, so closing this for now.
