### ISSUE TITLE
Ascertain Binaries Compatibility with 32-bit MS Windows

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#161]
We recently received a report that the mswin binaries only run on x86-64 and not on 32-bit i586:

https://sourceforge.net/p/pysolfc/discussion/503708/thread/6bc46fd7e0/?limit=25#aac9

We should try fixing it. @Programator2 : any idea?

**Comment by shlomif** [comment]
Assigning to @Programator2 : feel free to unassign yourself.

**Comment by Programator2** [comment]
I'll look into it.

**Comment by shlomif** [comment]
Thanks, @Programator2 ! Please let me know if I can help.

**Comment by Programator2** [comment]
I just booted my old 32-bit XP machine to test the installation. Everything works, the installer doesn't even contain 64-bit version. I'll ask OP for more info.

**Comment by shlomif** [comment]
On Wed, 20 May 2020 04:41:42 -0700
Roderik Ploszek <notifications@github.com> wrote:

> I just booted my old 32-bit XP machine to test the installation. Everything
> works, the installer doesn't even contain 64-bit version. I'll ask OP for
> more info.
> 

Thanks for checking, Roderik! Just to be sure - did you download the 2.8.0 exe
from https://sourceforge.net/projects/pysolfc/files/PySolFC/PySolFC-2.8.0/ ?

-- 

Shlomi Fish       https://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - https://shlom.in/selina

Python - There’s only one way to do it. The one true way of doing it. And then
there are others.
    — https://www.shlomifish.org/humour/ways_to_do_it.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by Programator2** [comment]
Yes, the newest version.

**Comment by shlomif** [comment]
@Programator2 : I wonder if there is an easy way to tell the user that they cannot use the installer on such old OSes as Windows 2000. If there is not, feel free to close this issue.

**Comment by Programator2** [comment]
Actually, there might be. The installer could check for the OS version. I'll work on it.
Also, some information in README would be beneficial.

**Comment by Programator2** [comment]
@shlomif I added version check to the installer and also a note to the README. If everything is ok, you can close the issue.

**Comment by shlomif** [comment]
On Mon, 25 May 2020 02:38:02 -0700
Roderik Ploszek <notifications@github.com> wrote:

> @shlomif I added version check to the installer and also a note to the
> README. If everything is ok, you can close the issue.
> 

Thanks! We may need to mint a new release first.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/ways_to_do_it.html

When there is a PyPy booboo, then PyPy goes byebye!
    — https://www.shlomifish.org/humour.html#pypy_booboo

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
> On Mon, 25 May 2020 02:38:02 -0700 Roderik Ploszek ***@***.***> wrote: @shlomif I added version check to the installer and also a note to the README. If everything is ok, you can close the issue.
> Thanks! We may need to mint a new release first.
> […](#)
> -- Shlomi Fish https://www.shlomifish.org/ https://www.shlomifish.org/humour/ways_to_do_it.html When there is a PyPy booboo, then PyPy goes byebye! — https://www.shlomifish.org/humour.html#pypy_booboo Please reply to list if it's a mailing list post - https://shlom.in/reply .

Release minted - closing. Thanks!
