### ISSUE TITLE
Restart game gives a different set of cards

### ISSUE THREAD

**Issue by RobertAJMarshall** [shlomif/PySolFC#163]
If I play a few moves and then restart the game, the cards that are turned in the initial state are different to the previous start point. The game number appears to be identical - tested with 'Spider (2 suits)' is this a pysol_cards issue? I updated from github earlier today to see this issue.

**Comment by shlomif** [comment]
@RobertAJMarshall : thanks for the report! I'll investigate.

**Comment by shlomif** [comment]
@RobertAJMarshall : hi! There indeed was an issue in pysol_cards - please try again in the latest PySol FC git master, which uses pysol_cards 0.8.17 with the fix. Thanks!

**Comment by RobertAJMarshall** [comment]
Yes that looks better! Thanks for the swift fix!

**Comment by shlomif** [comment]
> Yes that looks better! Thanks for the swift fix!

Thanks for checking and - you're welcome.
