### ISSUE TITLE
Quality cardsets while resize

### ISSUE THREAD

**Issue by Ygarr** [shlomif/PySolFC#167]
Support png(as a case) format or change default cardsets from gif to png to keep quality,  readability and clarity of card images

**Comment by joeraz** [comment]
PNG cardsets are currently supported.

Regarding higher quality cardsets, I just posted a more extensive comment on the subject here: https://github.com/shlomif/PySolFC/issues/50#issuecomment-877691026

**Comment by joeraz** [comment]
This has been completed as of 2.15.
