### ISSUE TITLE
General discussion thread

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#17]
**Update**: Discussions are better held on [the Google Group](https://groups.google.com/forum/#!forum/foss-card-games) .

I've got a question. Should we wait with bug reporting and feature requests until the Python 3 port will be ready? Or maybe we should create new tickets now to facilitate the creation of a roadmap/development plan for the future and discussion? It's obvious that the implementation of some features can take a very long time and that some stuff is low-priority.

Apart from our own ideas, I suggest looking at the biggest solitaire packages on the market, i.e. [Pretty Good Solitaire](http://www.goodsol.com/), [SolSuite](http://www.solsuite.com/), and [BVS Solitaire Collection](http://www.bvssolitaire.com/) (even in a virtual machine), as well as at some open source solitaire apps to see if we find something interesting.

**Comment by jan-kleks** [comment]
Did you get this message, shlomif? :)

**Comment by shlomif** [comment]
Hi Jan,

On Wed, 12 Apr 2017 14:10:05 -0700
Jan Kleks <notifications@github.com> wrote:

> I've got a question. Should we wait with bug reporting and feature requests
> until the Python 3 port will be ready? Or maybe we should create new tickets
> now to facilitate the creation of a roadmap/development plan for the future
> and discussion? It's obvious that the implementation of some features can
> take a very long time and that some stuff is low-priority.
> 

People are welcome to file new issues / tickets / bug entries / etc. at any
time for features or bugs they want to be handled. These tickets will be
prioritised accordingly, but it won't hurt to file them.

> Apart from our own ideas, I suggest looking at the biggest solitaire packages
> on the market, i.e. [Pretty Good Solitaire](http://www.goodsol.com/),
> [SolSuite](http://www.solsuite.com/), and [BVS Solitaire
> Collection](http://www.bvssolitaire.com/) (even in a virtual machine), as
> well as at some open source solitaire apps to see if we find something
> interesting.

That is a good idea, but : 1. We should avoid
https://en.wikipedia.org/wiki/Feature_creep . 2. It is not that of a high
priority.

> 
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Optimising Code for Speed - http://shlom.in/optimise

Good judgement comes from experience.  Experience comes from bad judgement.
    — http://en.wikiquote.org/wiki/Nasreddin

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jan-kleks** [comment]
I know the term "Feature creep", however when it comes to PySol, one of its main advantages is the fact that you can tweak even small things. It is definitely a premium package, Adobe Photoshop of solitaires. So I don't think we should be afraid of feature creep as long as the menus and the interface will follow the KISS principle (i.e. more advanced settings are hidden to avoid the clutter) and you prioritize ideas (but not discard them, I've used the term "discard" on purpose, lol.)

Well, let's see what I (and the others) will come up with. Mind you, that I'm not expecting you, shlomif, to implement all this stuff alone. I really hope that the project will take off, and the tasks could be assigned to different developers...

**Comment by hairspring** [comment]
Would the most important features / bug requests be the issues that have been raised by users on Sourceforge?  Have those already been noted here?

If not, I guess I could volunteer (in my role as "grasshopper apprentice") to go collect them and create them here?

**Comment by jan-kleks** [comment]
@hairspring Hmm... We could look through [the SF bug tracker](https://sourceforge.net/p/pysolfc/bugs/) and see if these bugs are valid/still present. When it comes to [features](https://sourceforge.net/p/pysolfc/feature-requests/) I actually wanted to file many of those present there myself (with even more detailed description, I'm in the process of comparing PySolFC to other solitaire packages BTW), but I can see a few interesting ones too...

**Comment by hairspring** [comment]
'We' is too vague.  So this is an activity you already have on your own list?  That's fine with me, as I've said elsewhere I have much to study to get up to speed with this project.  If at some future point you want me to take that on, just give me a nudge.

**Comment by jan-kleks** [comment]
Maybe it is. :) By we I meant anyone who wants to contribute. If you want to bring these bugs and features to Github bug tracker that is fine with me.

I'm not a native speaker of English, sorry if I'm not clear sometimes.

**Comment by hairspring** [comment]
> I'm not a native speaker of English, sorry if I'm not clear sometimes.

Your English is fine, Jan, don't be modest!  I'm guessing from your name you may be Dutch or Flemish, in which case your English could be better than many natives in England!

I like collaboration, but a kitchen full of chefs all trying to prep the same ingredients leads to chaos and wasted effort.  So we need "I'll do the potatoes, you do the peas, he does the meat, she does the gravy!".

I'm not always good at keeping my commitments, real life intervenes!  So I'll try to review SF some evenings this weekend.  If I fail, we'll reconsider next week.

**Comment by jan-kleks** [comment]
I'm Polish actually. :P 

"I like collaboration, but a kitchen full of chefs all trying to prep the same ingredients leads to chaos and wasted effort."

Well, I suppose this problem might affect every open-source project (or any large project in fact). I don't think we can eliminate it completely -- we should be happy that PySolFC is not the freaking Linux kernel. :) 

Hmm... Yeah, and we should be careful not to drag the discussion off topic in particular ticket issues. I kinda feel like you and shlomif _took over_ my SVG topic with your discussion regarding development (very interesting BTW). I wonder whether shlomif as an admin of sorts has an ability to move the comments to proper topics.

**Comment by jan-kleks** [comment]
Okay, I've changed the name of my topic so that people know it it can be used for meta discussions regarding Github and how to report bugs and suggest features.

**Comment by jan-kleks** [comment]
@hairspring Okay, I've started cleaning stuff up, I have deleted my comment and moved it here. Could you do something similar with your meta-comments, hairspring, please?

**hairspring** regarding the issue ["Find card" -- improvements"](https://github.com/shlomif/PySolFC/issues/19): "We'll find tracking issues difficult if in our enthusiasm we lump multiple unrelated topics together in the same issue? This looks to me like reason to raise those 3 feature requests as 3 separate issues?"

I've called them 'feature requests' because this is neutral. 'Improvement' suggests that something has been pre-judged! :)

You might be right, hairspring. I put all these issues in this topic because they're all related to the "Find card" option (which is a really small portion of PySolFC in my opinion). Shlomif, should I split such suggestions into separate issues? I can fix it if you want.

I called them "improvements" because everyone contributing wants to "improve" PySolFC. :P And I posted these ideas here so that they can be discussed, I'm not saying which ideas are best -- Hans-Joachim Gurt's or mine (or maybe a combination of both?). What is more, everybody is welcome to post their own improvement suggestions or to say why we shouldn't change anything. I am really open to discussion.

**Comment by jan-kleks** [comment]
I have created the topic "Programming solutions for PySolFC and development -- meta-topic for discussion (developers only)", so that developers would have a place to discuss general matters (and they would not have to clutter other topics, see the "SVG graphics" as an example).

I strongly suggest, shlomif, that you put links to this very topic "Project coordination, Github, feature requests and bug reporting meta-topic for discussion" as well as to "Programming solutions for PySolFC and development -- meta-topic for discussion (developers only)" on the main project page. I guess these topics should be enough for the most of general meta-discussions.

**Comment by jan-kleks** [comment]
You can notice that I have changed the topic name a few times because I'm still not sure what would be the best option. :P And I have just realized that we can even call it "PySolFC -- general discussion mailing-list", and rename the "Programming solutions for PySolFC and development -- meta-topic for discussion (developers only)" topic to "PySolFC -- developers mailing-list" and use both topics as **mailing lists** basically.

**Comment by hairspring** [comment]
> I'm Polish actually. :P

Dobry dzien, dziekuje!  (That's my limit, I gave up learning Polish when I discovered how tough it is compared to western euro languages.  Or Python!)

>  I kinda feel like you and shlomif _took over_ my SVG topic with your discussion regarding development

I agree, which was why I said there at the time: "I'm sorry, I'm very conscious I'm dragging this discussion off topic."

**Comment by jan-kleks** [comment]
I have split those "Find card" option suggestions into separate issues. I hope you like it more this way, shlomif. :)

**Comment by jan-kleks** [comment]
@hairspring [in the comment](https://github.com/shlomif/PySolFC/issues/11#issuecomment-295006344): "Remember, most of those interested in running PySol want to press a download button, click install, and if it gets harder than that, game over! Admittedly, right now this github fork (?) is not for them, there's no install media as there is on SourceForge. But eventually, that's the scenario we have to keep in mind if the work here is to be reintegrated with skomoroh's project or to gain widespread support as an alternative."

Yeah, I guess the builds with installers will appear after porting the application to Python 3 and fixing bugs related to issues with modern operating systems, right shlomif? Now this fork is more for developers and advanced users, I think.

I'm, of course, very thankful to skomoroh for developing PySolFC, but you see, hairspring, PySolFC at SourceForge is practically dead. So I don't think there is a chance for reintegration. You may also want to read my discussion with shlomif regarding the future of PySolFC (and PySolFC promotion) here: https://github.com/shlomif/PySolFC/issues/13

**Comment by shlomif** [comment]
Hi Jan,

On Tue, 18 Apr 2017 17:26:00 -0700
Jan Kleks <notifications@github.com> wrote:

> @hairspring [in the
> comment](https://github.com/shlomif/PySolFC/issues/11#issuecomment-295006344):
> "Remember, most of those interested in running PySol want to press a download
> button, click install, and if it gets harder than that, game over!
> Admittedly, right now this github fork (?) is not for them, there's no
> install media as there is on SourceForge. But eventually, that's the scenario
> we have to keep in mind if the work here is to be reintegrated with
> skomoroh's project or to gain widespread support as an alternative."
> 
> Yeah, I guess the builds with installers will appear after porting the
> application to Python 3 and fixing bugs related to issues with modern
> operating systems, right shlomif? Now this fork is more for developers and
> advanced users, I think.
> 

It should be possible to provide python 3-based installers similar to the ones
based on py2. On Linux distributions and similar, most users prefer to install
open source apps using the package manager and it can easily pull in python3 if
it's available. So making PySol py3-only should not be a major concern.

> I'm, of course, very thankful to skomoroh for developing PySolFC, but you
> see, hairspring, PySolFC at SourceForge is practically dead. So I don't think
> there is a chance for reintegration. You may also want to read my discussion
> with shlomif regarding the future of PySolFC (and PySolFC promotion) here:
> https://github.com/shlomif/PySolFC/issues/13
> 

Hopefully we'll be able to take over the project on SF.net, but possibly not.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/KxGRhd_iWuE - Never Give Up!!

The devil created a 10th circle of hell for the inventors of XSLT, because
the first nine circles were too mild for them.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hairspring** [comment]
@jan-kleks 
> Yeah, I guess the builds with installers will appear after porting the...

Yes, I can't imagine any of us are in a hurry to rush out an installable.  There's plenty to do first, ensuring the conversion is solid, improving quality etc.

> I'm, of course, very thankful to skomoroh for developing PySolFC, but you see, hairspring, PySolFC at SourceForge is practically dead. So I don't think there is a chance for reintegration. 

Never say never.  It's some years ago since I contacted skomoroh, I don't still have our mails, but I recall the exchange was very courteous.  Clearly he's not been active with the project, but eventually perhaps someone from here might step forward as a replacement leader.  I wasn't (and am still not) interested in becoming a project leader (here or there) because I see it as a long term commitment I couldn't make.  My life has peaks and troughs.  I'd contacted him with a view to tidying up and submitting some modified card sets I'd made.  But I didn't complete it.  See what I mean about my lacking long term commitment? :/

The other reason I didn't move forward with the card set mods was because, although he was courteous, I didn't get the feeling that he was keen to grab improvements and make a new release promptly, which didn't motivate me.  No doubt his life is busy too.

So you can see why I'm optimistic that, when this fork has made good progress and becomes stable, there's hope that a friendly merge will be [cough] on the cards!  Ouch, the pun police are on my case.

**Comment by jan-kleks** [comment]
@shlomif I'm really sorry that I'm bothering you with my multiple messages, but I would really like to improve communication with users and to avoid spamming other threads.

I have changed the thread name once again, adding the suggestion in the title that users can use GitHub's option to reply via email (like you do most of the time when replying, shlomif) to utilize this thread as a mailing list. I have change the developers thread name in a similar fashion: https://github.com/shlomif/PySolFC/issues/21  If you now **add links to these threads to the main page of this project** it might solve our communication issues. These threads will work as a hybrid between a forum thread/mailing list which I think is fantastic!

**Comment by hairspring** [comment]
@jan-kleks 
> ... users can use GitHub's option to reply via email ...

Really?  How does one do that, I don't see the option.  Though I'd rarely want it (see below).

> ... like you do most of the time when replying, shlomif

Perhaps you're misunderstanding github?  Because I'm subscribed to this project I do get an email each time someone adds a comment.  But that's just a side effect of the person publicly posting a comment, it's not them sending private mail to you.

So I don't think shlomif is replying via email.  At least, I hope he's not usually doing so, because generally it's useful for us all to see discussions and learn.  Private emails are just for flames and love letters! ;)

**Comment by hairspring** [comment]
PS
@shlomif I'm still wondering if it might reduce the need for lengthy chatter in issues if we make use of the project's wiki.  I assume we can all edit it?  Shall I have an initial shot at doing a main page there with various topics?

**Comment by jan-kleks** [comment]
@hairspring 

>Perhaps you're misunderstanding github? Because I'm subscribed to this project I do get an email each time someone adds a comment. But that's just a side effect of the person publicly posting a comment, it's not them sending private mail to you.

Just look at this small mail icon near shlomif's name when he's commenting. :) If you hover over it you can read "This comment left via email reply". You can actually reply to comments via your email client and they will "magically" appear here. :) So this works more or less like a mailing lists without a hassle of setting up one. There's just no "subject" line which one could define when writing to, e.g. "General discussion thread (doubles as mailing list -- use GitHub option to reply via email)", but as long as we are clear on what we are referring to in the comment's content we should be fine. 

>I'm still wondering if it might reduce the need for lengthy chatter in issues if we make use of the project's wiki. I assume we can all edit it? Shall I have an initial shot at doing a main page there with various topics?

The problem with all these wikis, message boards is that you need to set them up and than maintain (which takes your precious development time). That's why, I guess we're trying to use mainly to GitHub. :)

**Comment by jan-kleks** [comment]
@hairspring Oh, sorry I didn't notice the wiki is built-in. I'm learning GitHub as well... So this might be a good idea indeed. :P

**Comment by jan-kleks** [comment]
@hairspring Read more on the reply via email functionality here: https://github.com/blog/811-reply-to-comments-from-email

**Comment by jan-kleks** [comment]
@hairspring Well, I have talked to shlomif on IRC, he does not like the idea of using GitHub as a mailing list. But he might reconsider his position on a **real mailing list**.

**Comment by hairspring** [comment]
I wrote 4 days ago:
> I'm not always good at keeping my commitments, real life intervenes! So I'll try to review SF some evenings this weekend. If I fail, we'll reconsider next week.

I've realised that when reviewing I ought to repro such problems with the code here, in case the issue is already fixed.  It will be a while before I get that far. :(

@jan-kleks 
> Just look at this small mail icon...

Ah, thanks for that!

**Comment by shlomif** [comment]
Hi all!

I set up a google group for discussing PySol and other FOSS card games. The link is here - https://github.com/shlomif/PySolFC . We can continue the discussion there.

**Comment by jan-kleks** [comment]
This discussion can be continued in [the Google Group for discussing open source card games](https://groups.google.com/forum/#!forum/foss-card-games).
