### ISSUE TITLE
[Easily fixable] [Bug] Hanafuda cards: "Gaji" card not lowest November card

### ISSUE THREAD

**Issue by ArchibaldBienetre** [shlomif/PySolFC#172]
Hi,

I discovered a minor issue with Hanafuda-type games.

In Hanafuda, there are 12 suits (for the 12 months), and each suit has 4 cards.
For 11 of them, the last 2 of the 4 cards are "junk cards" with no value, and they are usually interchangeable. 
For the month November ("k" suit), however, this is different: There is only one "junk card", called Gaji.
It even has a special role with one of the games (the eponymous "Gaji"). 

I found that the **Gaji card is mixed up with the "Ribbon" card of the November suit.** 
* It is not the lowest-order card of the suit as it should be
* In the "Gaji" game, it is the Ribbon card that has the special power. 

To prove my point, here are some references: 
* the website of card game researcher John McLeod: https://www.pagat.com/class/flower.html
* ... or Wikipedia (One column lists the number of Junk cards): https://en.wikipedia.org/wiki/Hanafuda#Cards

**How to fix:**
I think that, in order to fix this, **all it takes is exchanging these two images:** 
* https://github.com/shlomif/PySolFC-Cardsets/blob/master/cardset-hanafuda-200-years/03k.gif (currently shows Gaji, a thunderstorm)
* https://github.com/shlomif/PySolFC-Cardsets/blob/master/cardset-hanafuda-200-years/04k.gif (currenly shows the willow plant and a ribbon)  
EDIT: ... for all hanafuda-type decks, of course

PS: Thanks for the great software!!

**Comment by ArchibaldBienetre** [comment]
I created a pull request for this: 

https://github.com/shlomif/PySolFC-Cardsets/pull/3

**Comment by joeraz** [comment]
Corrected this for the remaining hanafuda cardsets.
