### ISSUE TITLE
Test failed on travis_ci

### ISSUE THREAD

**Issue by Neelix57** [shlomif/PySolFC#176]
I tested my files using travis_ci. I got an error with `"tests/style/tidyalhttps://guides.github.com/features/mastering-markdown/l.t".` travis_ci said dubious.

[Here is the log](http://pastebin.fr/66763)

**Comment by shlomif** [comment]
Seems to be ok now: tests/build are passing: https://travis-ci.org/github/shlomif/PySolFC/jobs/731520066 . Thanks!
