### ISSUE TITLE
errors in 'pysol.exe'

### ISSUE THREAD

**Issue by timsoftgit** [shlomif/PySolFC#188]
when you quit the game and windows, you get an error message
Errors in 'pysol.exe'
See the logfile 'c:\Program Files (x86)\PySol Fan Club edition\pysol.log' for details.
there is no log, when run from this location. (probably windows file protection getting in the way).
If I copy the whole directory to c:\games\PySol Fan Club edition\ and run from there, I still get the error message
(this time pointing to a log in the new location), but at least the log exists.
the log contains
Exception ignored in: <bound method PyGameAudioClient.__del__ of <pysollib.pysolaudio.PyGameAudioClient object at 0x0345790>>
Traceback (most recent call last):
  File "C:\projects\pysolfc\pysollib\pysolaudio.py", line 58, in __del__
  File "C:\projects\pysolfc\pysollib\pysolaudio.py", line 80, in destroy
  File "C:\projects\pysolfc\pysollib\pysolaudio.py", line 586, in _destroy
pygame.error: mixer not initialized

This is running without speakers/headphones plugged in (even though there is a soundcard built into the pc).
It happens even if sound is disabled in the game (under options, sound).
obviously the c:\projects\pysolfc\pysollib directory does not exist either, but I assume that is related to how the package is wrapped for windows.

**Comment by shlomif** [comment]
Hi @timsoftgit ! Can you try to see if it is still happening with the newer PyInstaller-based builds in the "artifacts" sectiont of our AppVeyor project: https://ci.appveyor.com/project/shlomif/PySolFC ? Thanks!

**Comment by timsoftgit** [comment]
thanks for looking at it. unfortunately there are no artifacts, and if you look in the build log you see that the tests fail at
Found trailing space in file 'pysollib\tile\selectcardset.py'

**Comment by shlomif** [comment]
> thanks for looking at it. unfortunately there are no artifacts, and if you look in the build log you see that the tests fail at
> Found trailing space in file 'pysollib\tile\selectcardset.py'

See the "master" branch builds e.g: https://ci.appveyor.com/project/shlomif/pysolfc/builds/35769260/artifacts . The build with the failing tests and no artefacts was likely the recent pull req.

**Comment by timsoftgit** [comment]
that seems to have fixed it, thanks.

**Comment by shlomif** [comment]
> that seems to have fixed it, thanks.

You're welcome! Note however that technically speaking the bug is not fixed yet because we have not released a new stable version yet. https://en.wikipedia.org/wiki/It_ain%27t_over_till_the_fat_lady_sings . 😊
