### ISSUE TITLE
[ Task ] Prepare a new stable release ( 2.12.0 )

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#190]
Since there are quite a few installers, build system and other fixes on the git master branch, and some people contact us about difficulties running the latest version ( 2.10.1 ) I think we should prepare a new release soon.

Some stuff I'd like to include:

1. Put `freecell-solver.dll` and `black-hole-solver.dll` in the PATH in the windows installer and bundle the python3/cffi interfaces ( https://pypi.org/project/black-hole-solver/ and https://pypi.org/project/freecell-solver/ ) for an improved user experience.

Anything else?

**Comment by divinity76** [comment]
why not 2.11.0? skipping all odd numbers or something?

**Comment by shlomif** [comment]
On Fri, 20 Nov 2020 13:15:15 -0800
divinity76 <notifications@github.com> wrote:

> why not 2.11.0? skipping all odd numbers or something? 
> 

Hi! See:
https://producingoss.com/en/development-cycle.html#release-number-even-odd-strategy
; "stable/production" versions use an even minor version digit.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://github.com/shlomif/Freenode-programming-channel-FAQ

A man in love is incomplete until he is married.  Then he is finished.
    — Zsa Zsa Gabor, "Newsweek"

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
@shlomif Just wondering what it would take to make a new release happen at this point?

**Comment by shlomif** [comment]
> @shlomif Just wondering what it would take to make a new release happen at this point?

hi @joeraz ,

see https://github.com/shlomif/PySolFC/blob/master/CONTRIBUTING.md#the-release-process

**Comment by joeraz** [comment]
@shlomif Right.  Thanks.

Would it be possible to do a release now or in the next couple weeks or so, or is there anything that should be handled first?  I've added quite a bit, and it's been a while since the last one.

Looking through those steps, I was able to test the Windows installer based on my last commit, though I'm having some issues getting gmake to run (looks like an environment issue, not a code issue), and I also don't know who has SourceForge upload access.

**Comment by shlomif** [comment]
> @shlomif Right. Thanks.
> 
> Would it be possible to do a release now or in the next couple weeks or so, or is there anything that should be handled first? I've added quite a bit, and it's been a while since the last one.
> 
> Looking through those steps, I was able to test the Windows installer based on my last commit, though I'm having some issues getting gmake to run (looks like an environment issue, not a code issue), and I also don't know who has SourceForge upload access.

I can give you sourceforge rights, and I trust your judgement on when to release a new version: https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/ .

**Comment by joeraz** [comment]
Okay.  I'll message you on SourceForge.  Could I also have a commit bit for the website repo?  If I make a release, I'd need to add the announcement there too.  Thanks.

**Comment by shlomif** [comment]
> Okay. I'll message you on SourceForge. Could I also have a commit bit for the website repo? If I make a release, I'd need to add the announcement there too. Thanks.

@joeraz : you should have the permissions now. [drive safely, the keys are inside](https://www.shlomifish.org/humour/Selina-Mandrake/ongoing-text.html#is-moshes-ben-amram-the-jewish-prophet). ;)

**Comment by joeraz** [comment]
Thanks.

**Comment by joeraz** [comment]
2.12.0 has been released.

**Comment by shlomif** [comment]
On Sun, 11 Jul 2021 10:59:11 -0700
"Joe R." ***@***.***> wrote:

> 2.12.0 has been released.
> 

That's Great! Thanks!


-- 

Shlomi Fish       https://www.shlomifish.org/
Free (Creative Commons) Music Downloads, Reviews and more - https://jamendo.com/

Some people grow older and wiser. Not I. I grow older and more foolish.

Please reply to list if it's a mailing list post - https://shlom.in/reply .
