### ISSUE TITLE
Installing perl failed in appveyor build

### ISSUE THREAD

**Issue by Guillaumegaillard** [shlomif/PySolFC#195]
Hi,
I am trying to make the stacks spread over the X axis without changing the card size, like in old Windows XP spider.exe.

Doing so, and following https://github.com/shlomif/PySolFC/blob/master/CONTRIBUTING.md
I passed Travis but not AppVeyor:
https://ci.appveyor.com/project/Guillaumegaillard/pysolfc/builds/36385204
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\StrawberryPerl\5.32.0.1\strawberry-perl-5.32.0.1-64bit.msi" /qn /norestart ] was not successful. Exit code was '1603'

This while the same choco install strawberryperl worked here:
https://ci.appveyor.com/project/shlomif/pysolfc?fullLog=true

I don't really know how to proceed from here :)
Guillaume

**Comment by shlomif** [comment]
Hi @Guillaumegaillard ! Thanks for your contribution. You can try clearing the appveyor caches and issuing a rebuild. I've queued a rebuild for a recent commit and installing strawberryperl seems fine there: https://ci.appveyor.com/project/shlomif/pysolfc/builds/36399164 . It may have been a temporary hiccup (see e.g: https://www.shlomifish.org/humour/fortunes/show.cgi?id=tim-berners-lee-the-WWW-and-the-dexter-model ).

**Comment by Guillaumegaillard** [comment]
Hi, 
I tried cleaning the appveyor build cache, following:
https://www.appveyor.com/docs/build-cache/#addchange-dependency
But still the same failure:
https://ci.appveyor.com/project/Guillaumegaillard/pysolfc/builds/36400447

I guess it's a Windows/Perl related problem...

**Comment by shlomif** [comment]
> Hi,
> I tried cleaning the appveyor build cache, following:
> https://www.appveyor.com/docs/build-cache/#addchange-dependency
> But still the same failure:
> https://ci.appveyor.com/project/Guillaumegaillard/pysolfc/builds/36400447
> 
> I guess it's a Windows/Perl related problem...

1. Please move the commits to a separate, non-master, git branch. This will make rolling back, squashing, etc. easier.

2. I don't think you need to pin the "choco install" perl version in `appveyor.yml`. The dependencies should work fine with 5.30.x or even somewhat earlier versions.

3. We can still merge a PR/etc. with a failing appveyor build. We should not always be the slaves of our tools, as we can fix the CI build later.

Thanks again.

**Comment by Guillaumegaillard** [comment]
> * Please move the commits to a separate, non-master, git branch. This will make rolling back, squashing, etc. easier.
> 
> * I don't think you need to pin the "choco install" perl version in `appveyor.yml`. The dependencies should work fine with 5.30.x or even somewhat earlier versions.
> 
> * We can still merge a PR/etc. with a failing appveyor build. We should not always be the slaves of our tools, as we can fix the CI build later.

Done those three points.
While building the pull request, AppVeyor passes, but no Travis....
https://travis-ci.org/github/shlomif/PySolFC/jobs/744702339
-> The job exceeded the maximum time limit for jobs, and has been terminated.

Let's see:)

**Comment by shlomif** [comment]
> > * Please move the commits to a separate, non-master, git branch. This will make rolling back, squashing, etc. easier.
> > * I don't think you need to pin the "choco install" perl version in `appveyor.yml`. The dependencies should work fine with 5.30.x or even somewhat earlier versions.
> > * We can still merge a PR/etc. with a failing appveyor build. We should not always be the slaves of our tools, as we can fix the CI build later.
> 
> Done those three points.
> While building the pull request, AppVeyor passes, but no Travis....
> https://travis-ci.org/github/shlomif/PySolFC/jobs/744702339
> -> The job exceeded the maximum time limit for jobs, and has been terminated.
> 
> Let's see:)

I'll try to take a look - thanks! may take some  time though.

**Comment by jnumm** [comment]
Hi, I think we can close this issue for now as [Appveyor for _shlomif/PySolFC_](https://ci.appveyor.com/project/shlomif/pysolfc) runs successfully and is not affected.
