### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [shlomif/PySolFC#201]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
> @mondlicht-und-sterne closed this as completed on Feb 11, 2021

https://f-droid.org/packages/org.lufebe16.pysolfc/ — F-Droid still doesn't show screenshots of this app. It is difficult to choose an application from several, focusing only on their brief descriptions.
