### ISSUE TITLE
confirm dialog before resetting game

### ISSUE THREAD

**Issue by NickLeippe** [shlomif/PySolFC#210]
The reset game button is right next to the undo move button.
(Android, spider, other games)

Occasionally when undoing rapidly you can accidentally fat finger the reset game button and boom, the entire game is restarted. To avoid this, some options are:
1) add an option to ask confirmation (via dialog) before resetting the game
2) put the reset game into the undo stack so the reset itself can also be undone and game resumed where it was before resetting

**Comment by davux** [comment]
I'm bitten by this all the time. It's so frustrating when you're carefully planning a move and them you just reset the game because you tapped one pixel too high.

**Comment by Butterfly** [comment]
I've probably only been bitten a couple times by it, but yeah, definitely. It could be seen as an "accessibility" update, too. Maybe as an accommodation or consideration for people with disabilities related to mobility... :+1: :100:
