### ISSUE TITLE
Prebuilt 2.12.0 on macOS unavailable

### ISSUE THREAD

**Issue by daemonspudguy** [shlomif/PySolFC#214]
It tries to import all_games.py, which fails with `Traceback (most recent call last):
  File "/Users/spud/PySolFC/./scripts/all_games.py", line 10, in <module>
    import pysollib.games
ModuleNotFoundError: No module named 'pysollib'`

**Comment by daemonspudguy** [comment]
By cloning the repo, running `make mo` & `make rules`, and then running `python3 ./setup_osx.py py2app`

**Comment by daemonspudguy** [comment]
Also, I don't think strace is available on macOS

**Comment by shlomif** [comment]
On Wed, 21 Jul 2021 12:06:09 -0700
daemonspudguy ***@***.***> wrote:

> Also, I don't think strace is available on macOS
> 

True, but there are similar tools:
https://stackoverflow.com/questions/1925978/equivalent-of-strace-feopen-command-on-mac-os-x
.

-- 

Shlomi Fish       https://www.shlomifish.org/
Chuck Norris/etc. Facts - https://www.shlomifish.org/humour/bits/facts/

Only dead fish go with the flow.
    — via Nadav Har’El

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by jnumm** [comment]
Dear daemonspudguy & Shlomi,

the workaround for this particular problem is to use _PYTHONPATH_, i.e. run `PYTHONPATH="." python3 ./setup_osx.py py2app`.

I have managed to set up a GitHub Action that runs py2app, you might be able to download and try out either of the two “Artifacts” (pysolfc-app, pysolfc-dmg) from https://github.com/shlomif/PySolFC/actions/runs/1055183833.

**Comment by shlomif** [comment]
On Wed, 21 Jul 2021 23:53:34 -0700
Juhani Numminen ***@***.***> wrote:

> Dear daemonspudguy & Shlomi,
> 
> the workaround for this particular problem is to use _PYTHONPATH_, i.e. run
> `PYTHONPATH="." python3 ./setup_osx.py py2app`.
> 
> I have managed to set up a GitHub Action that runs py2app, you might be able
> to download and try out either of the two “Artifacts” (pysolfc-app,
> pysolfc-dmg) from https://github.com/shlomif/PySolFC/actions/runs/1055183833. 
> 

Thanks for your help

-- 

Shlomi Fish       https://www.shlomifish.org/
List of Portability Libraries - https://shlom.in/port-libs

“Did you sleep well?”
“No, I made a couple of mistakes.”
    — https://en.wikiquote.org/wiki/Steven_Wright via Nadav Har’El

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by daemonspudguy** [comment]
@jnumm some cardsets are 100% invisible with your builds.

**Comment by daemonspudguy** [comment]
This has been renamed as it has turned into an attempt to get 2.12.0 running on macOS

**Comment by daemonspudguy** [comment]
Also, for some reason autoscaling cards is gone. Why is that gone?

**Comment by joeraz** [comment]
> 
> 
> Also, for some reason autoscaling cards is gone. Why is that gone?

A number of the advanced graphics options are dependent on the Python Imaging Library (also called Pillow or PIL).  This includes auto-scaling.  If this library is missing, PySol will still run, but options like auto-scale that are dependent on it will be missing.  I know Pillow is included in the Windows Installers, but I don't know if it's in the Mac packages (don't really know much about Mac).

**Comment by daemonspudguy** [comment]
Of course, I'm an idiot who for some reason thought Pillow would be included in Python 3.9 for macOS.

**Comment by joeraz** [comment]
Closing because a Mac package has been provided for newer PySol versions.
