### ISSUE TITLE
Jnumm build artifacts are unusable

### ISSUE THREAD

**Issue by daemonspudguy** [shlomif/PySolFC#216]
The cards are 100% invisible with most cardsets using @jnumm's builds.

**Comment by joeraz** [comment]
Hi, @daemonspudguy - could you provide a little more detail?  Could you list for me a few cardsets that are visible for you and a few that aren't?

**Comment by daemonspudguy** [comment]
The 2k cardset, xpat cardset, and aisleriot cardset are all visible. Neo, Chris Aguilier, and Dondorf are among the ones invisible.

**Comment by daemonspudguy** [comment]
@jnumm, any idea as to why this happens?

**Comment by jnumm** [comment]
I tried to fix the issue (https://github.com/shlomif/PySolFC/commit/dade1ce20dccb14cb12e70dde4a1748668d1f98b) and the [current build](https://github.com/shlomif/PySolFC/actions/runs/1123844492) might work better.

It matters what kind of Python interpreter is used to create the package. GitHub's and Homebrew's Python executables apparently [link against broken Tcl/Tk](https://bugs.python.org/issue42480#msg382033), while Python.org supplies builds that come bundled with a better Tcl/Tk. PySol interface uses Tcl/Tk so we need to download our python directly from python.org.

**Comment by daemonspudguy** [comment]
I thought that might be why. My original builds had similar issues, but I installed the Python SDK from their website and it compiled.
