### ISSUE TITLE
python module formatter was removed from python 3.10 

### ISSUE THREAD

**Issue by sergiomb2** [shlomif/PySolFC#217]
https://docs.python.org/3.9/library/formatter.html

import formatter 
ModuleNotFoundError: No module named 'formatter' with python 3.10 and we can't play pysol in Fedora Rawhide 

Thank you

**Comment by shlomif** [comment]
@sergiomb2 : hi! Can one separately install `formatter.py` using `dnf` or `pip`? I also think there is a fedora ticket about it.

**Comment by sergiomb2** [comment]
looking for fedora ticket.
meanwhile from https://docs.python.org/3.10/whatsnew/3.10.html 
- Removed the formatter module, which was deprecated in Python 3.4. It is somewhat obsolete, little used, and not tested. It was originally scheduled to be removed in Python 3.6, but such removals were delayed until after Python 2.7 EOL. Existing users should copy whatever classes they use into their code. (Contributed by Dong-hee Na and Terry J. Reedy in bpo-42299 https://bugs.python.org/issue42299.)

**Comment by sergiomb2** [comment]
`cp /var/lib/mock/fedora-34-x86_64/root/usr/lib64/python3.9/formatter.py /var/lib/mock/fedora-rawhide-x86_64/root/usr/lib64/python3.10/` fixes the problem

**Comment by sergiomb2** [comment]
I know, I wrote this issue  after the read the fedora ticket , because I'm one of the maintainer of PySolFC package , and it is not a packing bug  so we should inform upstream , which is you and here ...

**Comment by shlomif** [comment]
A pullreq that tries to fix this issue: https://github.com/shlomif/PySolFC/commit/06d2fd5b90c29cbfe9b938676cc85c514cbbcca1 .

**Comment by joeraz** [comment]
Closing as this has been released with 2.14.
