### ISSUE TITLE
Mouse/click behaviour in Spaces game changed

### ISSUE THREAD

**Issue by protegh** [shlomif/PySolFC#220]
The new 2.12 version changed the mouse/click behaviour in the Spaces game. In the old 2.6.4 version one could click with the right or left mouse on a free field and the matching card was placed there. With version 2.12 you have to find the card you want to move and click on that card. Please go back to the old behaviour or at least implement an option to switch to this old behaviour.

**Comment by joeraz** [comment]
This seems to be related to an issue with invisible card bases combined with using the Auto-Scale or Center Layout options.  Just posted a commit that should fix this for Spaces and other Montana-type games.
