### ISSUE TITLE
Prepare 2.14 release

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#221]
Python 3.10 will release on October 4.  The current main 2.12 release is not compatible with Python 3.10, though the latest development code should be as a result of the fix to issue #217 - the app could use some additional testing with Python 3.10, but I personally haven't seen any issues from my end.

I know PySol 2.12 wasn't released that long ago, but I think it would be a good idea to have a Python 3.10 compatible stable release before it's released.  I'd also kind of like to get the new Mac download packages up on SourceForge.  Unless there are any objections, I would like to cut a 2.14 release in the next couple weeks, or by the end of the month at the latest.  I have one half-finished game (Yukonic Plague) I hope to finish for this release, and a few cleanup items related to some of my previous changes, but aside from that, things seem pretty stable from my end.

Are there any objections to this plan, or is there anything else that people would like to include in this release?

**Comment by shlomif** [comment]
@joeraz : hi. I have no objections to minting a pysolfc 2.14 release. :+1:

**Comment by cardset** [comment]
I still see disregarding the rules of the games
 as a serious bug. 
Will you really release a new version without fixing it?

[Issue report](https://github.com/shlomif/PySolFC/issues/199)

**Comment by Butterfly** [comment]
Speaking as a Debian User (currently on Bookworm), some of the decision can be attributed to which "suite" is being addressed, i.e. stable, unstable, experimental. Some portion of stable releases possibly won't accept this as an upgrade. They'll stay with whatever they already have. They would only upgrade if a release corrects a major security flaw.

For unstable and experimental, bugs are expected and are persistently encountered. They're just part of the game that one acknowledges and accepts if one is going to go those routes... e.g. Bookworm. :smile:

**Comment by shlomif** [comment]
@Butterfly : what do the debian branches have to with PySol FC's upstream releases?

**Comment by Butterfly** [comment]
Hi, @shlomif! It was a suggested "scenario" that was attempting to help explain why packages are regularly released even though possible bugs are still open. Bugs that don't stop a program from working don't stop operating systems from pulling from your upstream offerings. :+1:

**Comment by joeraz** [comment]
There is no such thing as a completely bug-free program.  Of course, that doesn't mean I'm not going to do everything I can to eliminate as many bugs as I can before the release (I'm aware of a few that I'm looking into).

Though #199 is a bit of a can of worms, and I'm not sure whether it's really a bug or just a different variation of the games in question.  I'll put up more detail there.

**Comment by daemonspudguy** [comment]
What happened to 2.13?

**Comment by joeraz** [comment]
Based on my latest tests, I got all the major bugs that I'm aware of, and did some testing with the latest Python 3.10 RC without issue.  Unless anything else comes up, I'll cut the release this weekend.

**Comment by joeraz** [comment]
2.14.0 has been released.

**Comment by daemonspudguy** [comment]
Mac binary?

**Comment by daemonspudguy** [comment]
The entire screen is black for the mac binary.
