### ISSUE TITLE
Bug with table tiles

### ISSUE THREAD

**Issue by cardset** [shlomif/PySolFC#222]
(Version 2.12. Windows)
If I enlarge the playing cards with ctrl +, 
the table tiles no longer fill the entire playing area. 

[https://i.imgur.com/DkALlEJ.jpeg](https://i.imgur.com/DkALlEJ.jpeg)

**Comment by joeraz** [comment]
I've seen this happen before.  I think it's something to do with the way the table is created when the game is loaded, but thus far, I haven't been able to reliably reproduce the issue.  I'll take a closer look.

**Comment by joeraz** [comment]
Okay, I think I have a fix in place for this one.

**Comment by joeraz** [comment]
Closing since based on my testing, this has been resolved and included in the 2.14 release.  If this issue returns, feel free to reopen the ticket.
