### ISSUE TITLE
2.14.0 is broken on macOS

### ISSUE THREAD

**Issue by daemonspudguy** [shlomif/PySolFC#223]

**Comment by joeraz** [comment]
Unfortunately, I can't test the Mac build personally.  Could you try this file and see if it runs any better?
[pysolfc-dmg-test2.zip](https://github.com/shlomif/PySolFC/files/7193266/pysolfc-dmg-test2.zip)

**Comment by daemonspudguy** [comment]
Nope, also all black.

**Comment by daemonspudguy** [comment]
I made a build that works but it is incredibly unstable, often crashing when being ran.

**Comment by joeraz** [comment]
The build I posted was just based on the instructions and script from @jnumm - he might be able to offer more insight.

I'll set the default Mac package back to the 2.8.0 one on SourceForge for now.

**Comment by daemonspudguy** [comment]
@jnumm can we have some help here? It's been nearly two months and I still only a semi-working build of 2.14.

**Comment by daemonspudguy** [comment]
@joeraz can I have the instructions jnumm sent? He appears to be gone.

**Comment by joeraz** [comment]
The instructions can be found in the contributing.md file - https://github.com/shlomif/PySolFC/blob/master/CONTRIBUTING.md.

See step 8 under the release process.  The script will generate a .dmg file for the Mac OS release when I tag a new release.  I can also trigger this manually if needed.

**Comment by daemonspudguy** [comment]
The commands in that script create my builds that barely work. I'll send one over and someone here might understand what's going on with it.

**Comment by daemonspudguy** [comment]
I don't know what it means, but GitHub is saying "is not included in the list" when I upload the zip file.

**Comment by daemonspudguy** [comment]
testbuild.zip

**Comment by daemonspudguy** [comment]
I got it uploaded somewhere. It will disappear after either 5 downloads or one week, whichever comes first. https://send.vis.ee/download/f954747a042ea3bc/#CuIuzODTKW4cFa7RiTLmCw

**Comment by joeraz** [comment]
Looks like a GitHub bug.  I grabbed a copy for now, but will see about getting this reposted more permanently for archival purposes.

I pulled down a copy and will take a look.  I don't know much about MacOS packages, but I should at least be able to see if something's up in the PySolFC code.

**Comment by daemonspudguy** [comment]
Shame that @jnumm has disappeared again.

**Comment by daemonspudguy** [comment]
If you have VMware, you can patch it and install macOS in a virtual machine, and test these builds on it.

**Comment by joeraz** [comment]
I do have VMware, but I have thus far not been able to setup a macOS VM.

**Comment by daemonspudguy** [comment]
2.14.1 works!
