### ISSUE TITLE
Hanafuda decks can be slow to load

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#228]
Could use another opinion or some extra testing on this if anyone's available.

As part of my effort to improve the look and feel of PySolFC, I've created a higher resolution Hanafuda cardset based on some Creative Commons images I found online.  Very nice looking cardset - problem is it takes a very long time to load.  I think it has something to do with the fact that Hanafuda cardsets require a large number of unique card bottoms - load times got worse when I added those in.  Unfortunately, performance issues are not really my specialty and it could just be the computer I'm testing on.  I tried using a second computer, which has much higher specs than the first.  It loads at a reasonable speed there, but there's still some noticeable lag.  Could use a few more tests to determine how much of an issue this could be.

I think the slowness is coming from the use of Pillow's paste method, though replacing this could be a rather major refactor.  If the extra bottoms are involved, adding some universal Hanafuda suit icons to replace the cardset specific bottoms might be another option, but I'd have to find some.

Here is the cardset in question - I plan to PR this to the cardset repo once I feel a little better about the functionality:

[cardset-louie-mantia-hanafuda.zip](https://github.com/shlomif/PySolFC/files/7403841/cardset-louie-mantia-hanafuda.zip)

Note that some of the Hanafuda games do currently have layout issues with this cardset.  I'm aware of these and working on fixing those.

**Comment by cardset** [comment]
Besides the loading problems.
Is there any reason why the playing cards load once, and the bottoms twice?


> My results are inconsistent. The issues I had with Pillow are unrelated - the actual slowness occurs after the image is loaded, when it is being pasted into tkinter.
> 
> Transparency plays a role - when I changed the alpha value of the card bottoms from 0 to 1 (except in the corners), the speed of the image loading increased dramatically.

Is it possible to change the alpha value after loading the bottoms and before pasting it?

**Comment by joeraz** [comment]
I'm still looking into this, but I was able to eliminate most of the loading issues for now by adding common bottom images for all of the remaining cardset types.  The loading problems only seem to occur with the cardset-specific bottoms (which are only used if Pillow is not present).

Ideally, in the future, I'd like to be able to add an option to switch between using the cardset-specific bottoms or the generated bottoms from Pillow.

**Comment by cardset** [comment]
> Ideally, in the future, I'd like to be able to add an option to switch between using the cardset-specific bottoms or the generated bottoms from Pillow.

I think we need some option in options/cardset
like "load_custom_bottoms_if_exist" = yes/no

**Comment by cardset** [comment]
> The loading problems only seem to occur with the cardset-specific bottoms (which are only used if Pillow is not present).

One of the problems is, we load and resize the bottoms twice.
Please remove in pysollib/images.py
The lines from abpit 200 to 235 (load bottoms, load letters)
and you will see what happens.

Second problem is, in def resize() in the same file
we check, load and resize these bottoms every time,
instead resizing the bottom images in memory.
Change or workaround these section and you get a glimpse, how fast resizing of the cards on the table can be.

Third problem is, i don't know why these special bottoms load and resize so much slower than the faces. But i am still researching.

**Comment by cardset** [comment]
Okay, things work now for me.

But as i still have my problems with github,
you have to try the the code here.
https://github.com/cardset/PySolFC
Changes are in 
pysollib/images.py
and 
pysollib/ui/tktile/tkutil.py

To test make sure ../pysol/images/cards/bottoms
is blocked by renaming, so pysol can't call its
own bottoms.

To see the differences best, use the original
louie-mantia-hanafuda cardset from this thread.

**Comment by joeraz** [comment]
I tested this.  Works excellently when Pillow is installed.

However, I looked deeper into the double loading of the bottoms.  One minor issue here - the resize method is only triggered if Pillow is installed.  So if Pillow is not installed, no bottoms will load.  Instead of removing that code, I would wrap it in a `if not USE_PIL:` block.  Do that, and we should be good.

Otherwise, it runs well.  I'll follow-up on your GitHub issues in the other ticket.  Thanks.

**Comment by cardset** [comment]
Okay, changed and pulled.

And here i have a modified Louie Mantia Hanafuda Set.
[cardset-louie-mantia-hanafuda-modified.zip](https://github.com/shlomif/PySolFC/files/7926268/cardset-louie-mantia-hanafuda-modified.zip)
It should work good even with 2.1.4.
And the bottoms from it, could be used as defaults for pysol itself.

**Comment by joeraz** [comment]
Okay.  I'll add that updated cardset to my hi-res cardsets PR.

Everything looks good here.  I'll close this after merging your PR.

**Comment by cardset** [comment]
Because of the bug with the transparency, 
if several cards placed above another.
It is better to copy the original face cards and backs,
to the modified bottom, letters and shadow cards.

**Comment by joeraz** [comment]
I think this has been resolved at this point.
