### ISSUE TITLE
No music plays on non windows versions

### ISSUE THREAD

**Issue by natewrench** [shlomif/PySolFC#229]
Hi I am trying to figure out why the music doesn't play on non windows systems, I am on Manjaro and right now I am using openmpt to see if I can convert the music to a static file like mp3.

Addendum. Yes I could but it would increase the file size to about 5 meg each music file so 5 times 5 that's 25 megabytes for damn good tracker music

**Comment by shlomif** [comment]
@natewrench : thanks for the report! Please try https://github.com/shlomif/PySolFC/tree/issue229-tentative-fix .

**Comment by natewrench** [comment]
that worked, sorry I was wondering why there was no music, it wasnt there by default like the windows version.
