### ISSUE TITLE
Find card/tile option -- support for other games

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#23]
It would be nice to implement the "Find card" option for other PySol card games as well (now it only works with French cards, I guess.) We can also think about searching options for mahjong tiles.

**Comment by joeraz** [comment]
Added support for Tarock, Hex A, Hanafuda, and Mahjongg decks already.  Currently looking into expanding that to include Ganjifa and Trump Only decks.

**Comment by joeraz** [comment]
The find card option now works for all games.
