### ISSUE TITLE
Cardset and tile choosing windows empty though sets available 

### ISSUE THREAD

**Issue by Lakrits** [shlomif/PySolFC#231]
**Description**
When I choose the _Cardset_ or _Table tile_ entries in the _Options_ menu, the corresponding window opens, but is empty. When I close it, PySolFC closes as well. I made sure I have cardsets and table tiles available in the app's installation folder, and I have also reinstalled the program, for good measure. To see if it was just a matter of slow loading, I waited 30 minutes, but nothing happened.

**Installation**
I'm using PySolFC 2.14.0 for Windows (installed through _PySolFC_2.14.0_setup.exe_).

**System**
OS: Windows 11, 64-bit, x64-based

**To reproduce the problem**
Go to the _Options_ menu > Click _Cardsets..._ or _Table tiles..._

**Screenshots**
![pysol_cardsets](https://user-images.githubusercontent.com/1184718/144462818-f4e695a6-35a1-4abc-a1ff-873553917efe.png)
![pysol_tiles](https://user-images.githubusercontent.com/1184718/144462823-936c2cf1-8b46-4cbb-a7ad-45f1c87d8cd7.png)

Best regards,

Mikael Hiort af Ornäs

**Comment by cardset** [comment]
Bug is solved.
See here:
https://github.com/shlomif/PySolFC/issues/226

**Comment by Lakrits** [comment]
Unfortunately, I know next to nothing about coding. So I'll have to wait until the changes mentioned in #226 are implemented in the next official Windows installer release. But, thanks for the link :)

**Comment by joeraz** [comment]
@Lakrits It's going to be a while before the next release - in the meantime, you can pull an installer off AppVeyor and get the latest develop version from there: https://ci.appveyor.com/project/shlomif/pysolfc/builds/41752518/artifacts

**Comment by Lakrits** [comment]
Thank you, @joeraz :)

BTW, the same issue occurs for the _All games..._ window (_Select_ menu > _All games..._ entry).

**Comment by cardset** [comment]
It is not good, to let a final release in a buggy version 
for so long time online.

Please publish version 2.14.1

**Comment by joeraz** [comment]
@cardset I was planning on releasing a 2.14.1 if I got a fix for issue #223, and put the two fixes for those issues in there - but I haven't been able to get anywhere with that because I don't have a Mac testing environment.  I think this would be better discussed as a separate issue.

**Comment by joeraz** [comment]
@cardset See #232
