### ISSUE TITLE
2.14.1 or 2.16 release?

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#232]
I was not planning to do another big release so soon, nor do I think the code is quite ready for a 2.16 release.  Nonetheless, there are a couple notable fixed bugs that should probably be patched.  Since @cardset brought up a request to release a 2.14.1 in another thread, I figure it's worth opening a discussion.

I had considered making a 2.14.1 release for bugfixes #223 and #226, though #223 is not fixed, and without access to a Mac environment, I'm not sure what I can do about it - I tried, but couldn't get anywhere.  Since 2.14's release, 16 new games have already been added to master, which is the same as the number that was added in 2.14 (plus a couple unfinished ones I've yet to add), so I'd guess it's a little more than a 2.14.1 at this point.

I'm trying to decide between a few options:
- Cherry pick the major bugfix commits from after 2.14 into a 2.14.1 branch and release that?
- Tie up my current loose ends and move up the release of 2.16, saving my remaining plans for a 2.18?
- Hold a bit longer to see if someone can figure out #223?
- Just hold for now and release 2.16 when it's ready?

Maybe I'm just overthinking it, but I'm still kind of new at handling of releases, and I'm not completely sure how this situation was handled previously?

**Comment by cardset** [comment]
2.4.1 with the bugfixes as soon as possible.

Take all the time you need for all of your other plans.

**Comment by shlomif** [comment]
@joeraz I'm leaning toward the 1st bullet too.

**Comment by joeraz** [comment]
Alright, I'll start working on cherry-picking the post 2.14.0 bugfixes into a new branch.

**Comment by joeraz** [comment]
Here we go - in case anyone wants to test before I run the release process: https://github.com/shlomif/PySolFC/tree/2.14.1

Unless there are any more bugfixes/critical enhancements in the next couple days, this should be it - all it needs is the version to be updated to 2.14.1, and I'll do that right before release to make sure I get the date right.

**Comment by joeraz** [comment]
Unless something comes up, I'll run the release process tomorrow.

**Comment by joeraz** [comment]
All done.
