### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by cardset** [shlomif/PySolFC#240]
Github:

Hello, maybe you can help me.

I have successfully modified two files.
And for testing the game directly
from my fork without further modifications,
I added some image files.

Now I just want to send these two code files.
But github wants to send more than hundred files,
because they are new to the Master.
What can I do to avoid this behavior?

Second question:
PysolFc runs some tests on these pull requests.
How do I need to set up my fork so I can do just 
these tests before uploading the files or before running 
any pull request.

**Comment by joeraz** [comment]
You can't pull request a part of a branch.  You'd have to soft reset the branch back to before the extra changes were committed, then re-commit without the extra files, and force push.

I looked at your fork, and I think doing the following will help:
- Cardsets should be moved to a cardsets sub-folder in the data folder.  This folder will automatically be ignored as the cardsets are in a separate repo.
- Your html-src folder is missing.  Adding it back should remove a lot of extra changes.

As for the tests, you can install flake8 and run it against the code.  Flake8 validation is a large part of the tests.  As for the tests themselves, there are two of them:
- GitHub CI actions - Go to the Actions tab in your repository, and run the "CI Tests at GitHub" against the master branch.
- AppVeyor - I've never been able to get this working properly in my fork - the builds always fail for me.  If you want to try and set this up, you'd have to set up an AppVeyor account and tie it to your fork.  You can then try to build it through AppVeyor.  This attempts to do a full build using a Windows environment, and is how the installers are generated.

Does this help, or do you need more details?

**Comment by cardset** [comment]
Thanks
I will have a look at it and try.
I hardly know anything about git until now.
