### ISSUE TITLE
PySolFC 2.15 or 2.16 release

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#242]
Looking at the recent changes, quite a bit has happened since the last release, and I'd like to try and get the next release out sometime in early to mid March if there aren't any objections.

There are still a few issues I'd like to try and sort out first if possible (if it turns out they need more time, I'll hold them for the next release):
- Hi-Res Cardsets - I think it's about time to finally switch out the default PySol cardsets with hi-res versions now that I have a hi-res cardset of each type.  With this, I would also make Auto-Scaling the default option which should be a huge step towards modernizing the layout.  Just need to get the remaining hi-res cardsets in the cardsets repo, and prepare a new version of the cardsets package that includes them first.
- Overlapping text - When using auto-scaling with certain cardsets, the scaling can cause lines of text to overlap with each other.  This is most commonly seen in Forty Thieves type games.  Would want to add a failsafe to the resize logic to prevent this.
- Playable Preview for Mahjongg Tile games - I noticed that when using my hi-res Mahjongg cardset, the playable preview for Mahjongg games looks off (the gaps between tiles are too big).  Will want to look into this.
- Possibly a few more minor features that I come up with in the next month or so.

Hi-res cardsets are a major change - I'm considering making this release a beta 2.15 release, so we can get a little more feedback on some of the implications of this change so it can be further refined for a stable 2.16.

Any objections to any of this?  Or any additional items we'd like to get sorted out for the next release?

**Comment by cardset** [comment]
>      With this, I would also make Auto-Scaling the default option 

This is my opinion too. We need Auto-Scaling or the last used size of the cardset. In the moment i have unhappy behaviour in the game. 
For example: I open "Recent Games" Kalis Game with small cardset. Then i increase the cards to play. Then i switch to Big Sumo Game with Louie Mantia Set, and i get very very big cards that are unplayable. Resizing takes very long time too.


> should be a huge step towards modernizing the layout.  Just need to get > the remaining hi-res cardsets in the cardsets repo, and prepare a new 
> version of the cardsets package that includes them first.

Have also a look at the cardsets from grevex.
https://sourceforge.net/p/pysolfc/discussion/503708/thread/06823f00ef/

>   Playable Preview for Mahjongg Tile games - I noticed that when using my hi-res Mahjongg cardset, the playable preview for Mahjongg games looks off (the gaps between tiles are too big).  Will want to look into this.

We talked here about Mahjongg earlier. May it helps.
https://github.com/shlomif/PySolFC/issues/46#issuecomment-704011648

> Hi-res cardsets are a major change - I'm considering making this release a beta 2.15 release, so we can get a little more feedback on some of the implications of this change so it can be further refined for a stable 2.16.
> 

Good idea to offer here a Beta version first.
But we need people who test.

**Comment by daemonspudguy** [comment]
I also think we need to implement gttk[https://github.com/RedFantom/python-gttk](url) support.

**Comment by joeraz** [comment]
@cardset Thanks for the links.  I have at least one hi-res cardset of each type to use for a new default, just need to sort out the logistics of releasing a new PySolFC Cardsets 2.1.  I think I may need a few extra permissions for that, or I can just use my fork for the moment.  Though I'll certainly accept new cardsets for this release (especially hi-res ones), I won't feel right adding pre-made cardsets without the creator approaching me and giving permission.  I'll take a closer look at the posts about the Mahjongg cardsets.

@daemonspudguy I'll have to take a closer look at that library to see how difficult it would be to add.

**Comment by joeraz** [comment]
@shlomif If you're around, could I get commit access on the PySolFC Cardsets repo?

**Comment by daemonspudguy** [comment]
@joeraz I recommend adding the radiance theme now that you addedd ttkthemes, since gttk hasn't been implemented yet.

**Comment by joeraz** [comment]
@daemonspudguy It has already been added.  All of the themes in ttkthemes should be accessible from Options > Select theme if it's installed.

I looked into the gttk package, but was having issues installing it.  Though I haven't been able to look much yet.

**Comment by joeraz** [comment]
So, an update:

- This next release will be beta release 2.15.  I'll announce it on the main page like every other release to hopefully get some testers, just emphasizing it's a beta release.  My plan is to do a stable 2.16 in the next couple months based on feedback, and further refinement of some of the more recent changes.
- As I have not been able to get access to the cardsets repo, I'll be releasing a Cardsets 2.1 off my fork, with the intention of merging the changes in if I do get access to the main repo later.  If anyone has any cardsets they'd like to add to this release (esp. hi-res ones), please PR to my fork.  Once I do some brief cleanup, I'll start setting the new default options based on the included hi-res cardsets.
- I was able to resolve the issues regarding Mahjongg scaling in preview mode.
- I was not able to resolve the text overlap issue.  The variables it needs are never available where they need to be.  Given that this is the most notable display issue with auto-scaling, unless someone else wants to take a stab at it, I'll look into reorganizing the text labels from the affected games as a work-around.
- Still no luck with python-gttk.  I'll try again later, but at this point, I'm not sure if this is worth holding up the release over.

I'm currently hoping to release on either the weekend of March 12 or March 19, depending on how other things play out.

**Comment by joeraz** [comment]
The current version is my release candidate.  Probably not going to make any more significant changes (maybe a few minor ones if something comes up), but unless I find something major or get some serious objections, I'll proceed with the release next weekend.

**Comment by joeraz** [comment]
Release completed.
