### ISSUE TITLE
Issue with SourceForge cardset downloads for MacOS package

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#246]
While doing the 2.15 release, I ran across an issue with the wget being used to retrieve the minimal cardsets package for the Mac package.  It seems that SourceForge was tacking on ?viasf=1 to the end of the file names.  I had to improvise to resolve it by adding this to the end of the filename in the script (sorry about the force push, it was the only way to avoid screwing up the tags).  Nonetheless, I feel like this has a chance of resurfacing for the next release (especially given the short timeframe I'm planning for 2.16), and I'm afraid I don't know enough about how the release scripts to be able to do anything more.

There are reports of this being a bug in SourceForge, but it was claimed to be resolved.  I don't believe it has anything to do with the minimal cardsets 2.1.0 package, as I generated that using the normal scripts, and AppVeyor was able to extract it just fine.

**Comment by kingjon3377** [comment]
Passing the `--content-disposition` option to `wget` might be enough to make it give the file the desired name.

**Comment by joeraz** [comment]
Thanks, but I just double-checked and the `--content-disposition` option is being passed in.

**Comment by joeraz** [comment]
Closing, as this seemed to be a one-time issue with 2.15, and did not occur with 2.16 or 2.18 (had to revert the workaround for 2.16).  I think this might have been the result of a bad mirror during that release.
