### ISSUE TITLE
PySolFC 2.16 release

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#247]
I know we just released 2.15, but as it was a beta release, I'd like to proceed with the stable 2.16 in the next month or two.  For 2.16, I'm planning on limiting changes to resolving bugs and feedback related to the hi-res display, rather than go crazy with new games and features, and other potentially breaking changes.  Here are the current items I'm planning on looking into in the near future:

- I'd like some kind of option to allow a user to set all of their display options with a single click, mostly so a user can set up all the hi-res options on a previous install without needing to wipe their options.cfg, or so they can choose to revert to the old low-res default options if they prefer those.
- I'd like to look further into the table tile logic - I can think of a few ways to improve the background displays.
- Look further into python-gttk
- Continuing adding rules to games that are missing them.

Anyone else have anything?

**Comment by joeraz** [comment]
I'm thinking about pulling the trigger on the 2.16 release next weekend, unless there are any significant objections.

The only thing I still want to add is the feature for mass updating display options.  I've been working on this, but it's either messy or half-functional.  I'll see if I can get it working this week - if so, I'll throw it in, but if not, I'll probably hold on that feature for the following release so as not to hold up getting a new stable release after 2.15.

**Comment by joeraz** [comment]
Had a slight delay because of issues with the scripts, but 2.16 has been released.

Probably going to take a little break while I decide on plans for the next version.

**Comment by shlomif** [comment]
On Tue, 10 May 2022 18:05:22 -0700
"Joe R." ***@***.***> wrote:

> Had a slight delay because of issues with the scripts, but 2.16 has been
> released.
> 
> Probably going to take a little break while I decide on plans for the next
> version.
> 

+1. Thanks for everything.

https://www.youtube.com/watch?v=k84QxVJd0tI

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/Google-Discontinues-Services/

Dax: yep, space. Nothing but nothing all around.
    — https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
