### ISSUE TITLE
Clean up images

### ISSUE THREAD

**Issue by MorsMortium** [shlomif/PySolFC#249]
There are many images that have white pixels around them. They look bad with darker themes.
![Screenshot_20220407_125727](https://user-images.githubusercontent.com/44305161/162184816-e84e783e-cbed-4922-8196-a421d46d8516.png)
![Screenshot_20220407_130313](https://user-images.githubusercontent.com/44305161/162185026-7a7eed18-0e5c-451d-8976-61d62e2714d1.png)
![Screenshot_20220407_130346](https://user-images.githubusercontent.com/44305161/162185105-63b675db-1618-4d0d-9f4a-f2be2025b885.png)

**Comment by joeraz** [comment]
I can take a stab at this, but my image editing skills are pretty basic.  Would need someone on the team with better image editing skills to perfect this.

Though as for the toolbar icons, you may be able to switch those out for a style that looks better with the dark interface.  In 2.15, this can be done by going to Options -> Toolbar -> Icon Style, but in older versions, you can change the toolbar_style value in the options.cfg to change the icon style to a different one (i.e. crystal or human).

**Comment by MorsMortium** [comment]
On arch 2.14.1 is packaged, so I didn't see the option, but editing the config, I saw that crystal also needs cleanup:
![crystal](https://user-images.githubusercontent.com/44305161/162572825-92351de9-da22-499e-971d-7e94bc2014bd.png)
But human is perfect, so that's what I'll use:
![human](https://user-images.githubusercontent.com/44305161/162572875-3520d5ab-a541-45b2-ba82-72abae323eee.png)
There are newer icon styles, but they're added in 2.15, so I don't have them.
On the editig itself I recommend only editing the highest resolution icons and downscaling from that, and the same with the jester/joker images, to make it less work.

**Comment by daemonspudguy** [comment]
@MorsMortium how did you get PySol to use gtkTtk?

**Comment by joeraz** [comment]
I checked the icon styles added in 2.15 and they don't appear to have this issue (though Remix uses pure black outlines, so I went ahead and added a white version of it for better contrast with a darker theme).

I was able to fix the Bluecurve icons by re-copying the icons from a copy of the original icon library.  I don't have the original library for Crystal (or at least not the version the previous developers used) - I'm going to need that anyway for another planned change, so I'll have to get back to that one later.  The jester images will need to be done manually, and while I tried briefly, I always ended up cutting off more than I needed to.

**Comment by joeraz** [comment]
I updated the joker images to try and remove the borders.  Though someone with better image editing skills than me could probably tweak them further to make them look even better.

**Comment by joeraz** [comment]
With today's commits, I updated to the newest version of the crystal icon set, which should resolve the last of this bit of image cleanup.  Though I'm going to leave this ticket open in case someone with even better image manipulation skills wants to take a stab at cleaning the joker images up even better.

**Comment by MorsMortium** [comment]
A bit late, but i rechecked every icon style and image, and all looks good. Thanks, and great work!
