### ISSUE TITLE
pysol-sound-server

### ISSUE THREAD

**Issue by codebykevin** [shlomif/PySolFC#250]
Is there any reason the Mac build of PySolFC is released without the ability to play sound? Can pysol-sound-server be included in the next release?

**Comment by joeraz** [comment]
Pysol-sound-server has largely been replaced by pygame, as it's more capable.  I didn't create the Mac packager, so I don't know if it was left out by accident or if there was a reason.

Nonetheless, I tried adding it and generated a new DMG file.  Unfortunately, I don't have access to a Mac environment to test with.  Could you verify that the audio works (and this doesn't break anything else)?  If it's good, I can add this change for the next release.

https://github.com/joeraz/PySolFC/suites/6166582930/artifacts/216118311

**Comment by codebykevin** [comment]
Thank you - the sound works reasonably well and doesn't seem to break anything, as far as I can tell.

**Comment by joeraz** [comment]
Fix added.
