### ISSUE TITLE
Version 2.15 (Windows) - (Greater Wheel) Cannot Drag cards onto the last 3 foundations of each row.

### ISSUE THREAD

**Issue by UncreativeHub** [shlomif/PySolFC#252]
In the game "Greater Wheel". You cannot manually drag cards onto the last 3 foundations of each row. All other foundations work correctly and the last three can still be used via right click.

I have not checked if other games are affected.

![image](https://user-images.githubusercontent.com/58356183/165459253-e05599ac-a235-4ef6-9449-3aabfebbbfe3.png) ... This foundation works (You can see it highlighted)

![image](https://user-images.githubusercontent.com/58356183/165459418-a0610d24-c596-4289-ba81-e63496c3907c.png) ... This one does not

**Comment by joeraz** [comment]
Thank you for the report.  I think I've got a fix ready - will test and confirm.

**Comment by joeraz** [comment]
Fixed for the next release.  Thanks.
