### ISSUE TITLE
Pysol dosen't run in Ubuntu 22.04

### ISSUE THREAD

**Issue by feenix3k** [shlomif/PySolFC#253]
It would seem a python module named 'formatter' is no longer available. PysolFC will not start without it, 

Distributor ID: Ubuntu
Description: Ubuntu Jammy Jellyfish (development branch)
Release: 22.04
Codename: jammy
pysolfc:
  Installed: 2.6.4-3
  Candidate: 2.6.4-3
  Version table:
 *** 2.6.4-3 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64
Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status
Traceback (most recent call last):
  File "/usr/games/pysolfc", line 36, in <module>
    from pysollib.main import main # noqa: E402,I202
  File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/share/games/pysolfc/pysollib/app.py", line 32, in <module>
    from pysollib.images import Images, SubsampledImages
  File "/usr/share/games/pysolfc/pysollib/images.py", line 28, in <module>
    from pysollib.pysoltk import copyImage, createBottom, createImage,
loadImage
  File "/usr/share/games/pysolfc/pysollib/pysoltk.py", line 35, in <module>
    from pysollib.tile.tkhtml import * # noqa: F401,F403
  File "/usr/share/games/pysolfc/pysollib/tile/tkhtml.py", line 29, in
<module>
    from pysollib.ui.tktile.tkhtml import Base_HTMLViewer
  File "/usr/share/games/pysolfc/pysollib/ui/tktile/tkhtml.py", line 24, in
<module>
    import formatter
ModuleNotFoundError: No module named 'formatter'

**Comment by joeraz** [comment]
The "formatter" module of Python was removed in Python 3.10.  We've since updated PySolFC to account for its absence, though versions of PySolFC prior to 2.14.0 are not compatible with Python 3.10.

In order to fix this, you can either update PySolFC to 2.14.0 or later, or downgrade Python to 3.9 or earlier.

**Comment by joeraz** [comment]
Just to confirm, the latest PySolFC releases do not have this issue.  It sounds like the people maintaining the app bundles for Ubuntu are behind a few releases, and if you run across this issue (with any distribution), I'd suggest contacting them.  I only maintain the releases posted on the main PySolFC site.

Will leave this open for a little bit so people are aware of this.

**Comment by joeraz** [comment]
I added an FAQ page to the main website, with this issue being the first item in it.

Closing now.
