### ISSUE TITLE
Missing credits for Penguin

### ISSUE THREAD

**Issue by salty-horse** [shlomif/PySolFC#268]
Penguin was invented by [David Parlett](https://www.parlettgames.uk/patience/penguin.html) and I think was first published in the Penguin Book of Patience.

Since other games with known inventors have a Notes section with credits, I think Penguin deserves it as well (along with a link to the game's official web page).

**Comment by joeraz** [comment]
Updated.

When inventors are known, the main way we've been keeping track of them is the "by Inventors" category in the select game window.  I've tried to add any historic details/notes I know to the docs for the games I personally write up, but it's easy to miss that.
