### ISSUE TITLE
Global stats "playing time" and "moves" counts only data from the winning games

### ISSUE THREAD

**Issue by VedVid** [shlomif/PySolFC#271]
As in the issue title, it seems that the statistics only count the "playing time" and "moves" based on the games won.

So far I had only one winning game, and exactly its stats are shown on the statistics screen - please see below.

![obraz](https://user-images.githubusercontent.com/16949680/188977958-4a06bef5-566f-403e-aeb0-9d4f23c9b782.png)

![obraz](https://user-images.githubusercontent.com/16949680/188977987-44c0d016-3fcd-40da-96ad-1b0a3b95e1a5.png)

I am not sure if is bug or it works like that by design, but subjectively it gives the impression of inconsistency.

Version: 2.16.0
OS: Windows 10 x64

**Comment by joeraz** [comment]
Confirmed.  Will review further.

**Comment by joeraz** [comment]
Those stats are actually "average time to win" and "average moves to win".  I will update the descriptions accordingly.

**Comment by joeraz** [comment]
I updated the labels to reflect the correct statistics.
