### ISSUE TITLE
Some table backgrounds don't preserve aspect ratio

### ISSUE THREAD

**Issue by ssokolow** [shlomif/PySolFC#275]
Due to bug #273, when I went to open the table background picker, I wound up previewing images with a near 3:1 aspect ratio on the preview pane and, because of that, I discovered that, both in the preview pane and the main game window, some backgrounds don't preserve their aspect ratio when scaling. (This is most noticeable with Castle and Sunset.)

See below:

![b1](https://user-images.githubusercontent.com/46915/189779317-325ca5c2-2eec-4d44-8125-680a7092e426.png)
![b2](https://user-images.githubusercontent.com/46915/189779323-54b2a6b4-1fc6-4edc-9fd4-1bd3265a5d21.png)

**Comment by joeraz** [comment]
Not a bug.  Backgrounds in the tiles/stretch folder are designed to stretch when the screen is resized, while backgrounds in the tiles/save-aspect folder have their aspect ratio preserved.  This is the way it's designed.

Though I should consider moving sunset and castle to the other folder.

**Comment by ssokolow** [comment]
I actually discovered the issue with one of the fractal backgrounds. Maybe I should open a feature request for a dropdown to let the *user* select the scaling behaviour. (Possibly right next to a feature request for an easy "Browse for image" button if one hasn't already been put up.)

**Comment by joeraz** [comment]
I had considered adding that feature before, but held off because I didn't think there would be much interest.  It shouldn't be too difficult to add.

**Comment by joeraz** [comment]
Okay, a bit trickier than expected, but I just added this option.  Had to disable it for tiles, as attempting to stretch or scale certain tiles can be expensive enough of an action to freeze or crash the app (and there seems little point in doing so regardless), but it will work for all the full images.

**Comment by ssokolow** [comment]
Looks good. Thanks. :)
