### ISSUE TITLE
Montana: Redo after Undo shuffles again

### ISSUE THREAD

**Issue by protegh** [shlomif/PySolFC#278]
Old behaviour of the Montana game:
- When I can't find any moves in round 1 I click on the button below the cards (with the recycle symbol) to enter the round 2 and the cards are shuffled.
- Doing some moves in round 2 but then I decide to go back by doing "undo" until I get back to the previous round.
- Changing my mind again I want to return to round 2 by doing "redo" and round 2 is entered again with all the cards on the same positions as when I entered round 2 the first time.

Can't tell with which version it changed to the new behaviour (2.16?):
- Changing my mind again I want to return to round 2 by doing "redo" and round 2 is entered again with the cards reshuffled.

I like the old behaviour more. Wasn't there an option to switch between these two behaviours?

**Comment by joeraz** [comment]
Noted.  Will review.

There was a recent change to this logic, but the change was because of a possible game-breaking error if the wrong sequence of undo and redo moves is performed, so I can't just revert that change, but will have to review the code more closely.

**Comment by joeraz** [comment]
Okay, this isn't my recent change.  I was able to reproduce it with version 2.8.0, so it's older than that (my current dev environment has issues running older versions than that because of some incompatible dependencies).  This will be more difficult to figure out than I originally thought.

**Comment by joeraz** [comment]
I finally figured out what's going on here - the issue is with the pysol_cards library, where the logic for saving and loading the random state is not working correctly.  I'm going to open an issue over at https://github.com/shlomif/pysol_cards.

**Comment by joeraz** [comment]
Okay, the latest version of the pysol_cards library fixes this issue.  This can be tested with the current dev builds, but currently, old saves made prior to the update will not load.  Will look into fixing this and will deploy the updated library in the next release.
