### ISSUE TITLE
"How to play" text might be a bit confusing

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#28]
I mean the text in "Help" -> "How to play", it might be taken by the user for "rules" at first glance. Change it something like "How to play PySol" or "How to use PySol".

**Comment by jan-kleks** [comment]
@shlomif I think this one should be quite easy to fix, if you agree with me shlomif, of course? :)

**Comment by shlomif** [comment]
@jan-kleks : yes, it should be easy to fix.

**Comment by joeraz** [comment]
Done.  It's been updated to "How to use PySol".
