### ISSUE TITLE
Pysol 2.18 android no file/storage permissions.

### ISSUE THREAD

**Issue by DanKrabach** [shlomif/PySolFC#284]
Pysol 2.18 on Android 11 has permission only for photo and media, not file/storage. This prevents saving games, settings, options, etc.  This is not the case on 2.8.

**Comment by joeraz** [comment]
I think this would be a question for @lufebe16.

**Comment by lufebe16** [comment]
I had no access to a android 11 target. Thanks for your feedback.

Android 11 has restricted access to 'external storage' drastically. Maybe no more access through simple os calls will be allowed. On the buildstep for fdroid, the gradle program, that does the final assembly forced to set the api level to 32, which is android 11.

But interesting is that 2.8 still runs. Based on this information it might be possible to get it running when the build could be set up for a earlier API version. You can try it, if you have a Linux system (Debian or similar). Build instruction are on the repo.

**Comment by joeraz** [comment]
This should be resolved with the 2.20 release.
