### ISSUE TITLE
Hints

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#291]
When requesting a hint, pysol keeps track, and at the end shows a message like
"Game finished, but not without my help...".

I would like to have this more detailed,
ie. how many hints were requested, 
and how many suggestions were made.

I mean, if the game cannot give a hint,
it shouldn't count as 'help'...

Also, it might be nice to have a count of possible moves displayed in the statusline,
for Spider, Picture-Gallery, etc. or on the table-background, as in Mahjongg.

**Comment by joeraz** [comment]
I don't think a hint not finding any possible moves means that the hint failed - you do still get a hint, it's just the hint is telling you there are no possible moves and you need to redeal, and you're still checking if there's an available move you missed.  Though I personally always felt the way hints were handled was a bit heavy-handed, hence why I added the Free Hints option.

PySol does keep track of the number of hints used (in the Status window), so I should be able to add that to the game end message.

**Comment by joeraz** [comment]
Okay, that last commit should add a hint count to the completed game with help message.

**Comment by joeraz** [comment]
Confirmed that if using a hint doesn't find a move, it doesn't count against the player.  Same as if you use other assist options, like highlighting same rank, etc.
