### ISSUE TITLE
PySolFC 3.0?

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#296]
Several recent releases have had some pretty major features/updates:

- 2.12.0 - Lots of graphical enhancements - centering the display and fixed a lot of the most glaring polish issues.
- 2.15.0 - Full support for hi-res cardsets, completely revamped the default display to look more modern.
- 2.18.0 - Finally complete game rule documentation and advanced search options.

PySolFC has come a long way since version 2.0, so I figured I should ask what other people think about a 3.0 release (after 2.20) - if there are any specific features that would be a must-have for the 3.0 release, if you think it's still too soon, or any other opinions on what version 3.0 would look like?

**Comment by Alucard648** [comment]
I think, 3.0 should have proper scripting engine for making your own solitaire games that cannot be done with Solitaire Wizard. It`s one of natural evolution points for one of the best solitaire collections ever made for PC.

**Comment by joeraz** [comment]
> I think, 3.0 should have proper scripting engine for making your own solitaire games that cannot be done with Solitaire Wizard. It`s one of natural evolution points for one of the best solitaire collections ever made for PC.

It's actually possible to script new games with the current version using plugins, it's just very poorly documented.  If you write the python scripts for the games, and put them in the same plugins folder as the wizard games are saved, PySolFC will recognize them and add the games appropriately.  This uses the exact same scripting functions I use when I write new games to the app.  Here's a couple sample plugin scripts I wrote based on a couple games I previously added to PySolFC - both way more complex than the current Solitaire Wizard can handle.

[plugins.zip](https://github.com/shlomif/PySolFC/files/10715170/plugins.zip)

Is this the sort of thing you're looking for?

**Comment by Alucard648** [comment]
> Is this the sort of thing you're looking for?

Yes. If it`s poorly documented, it needs to be done.

**Comment by joeraz** [comment]
I added a short page of documentation explaining how plugins can be used, and I uploaded the sample plugins to SourceForge.

**Comment by vavavr00m** [comment]
Graphical interface for customizing game rules?

I have seen one

**Comment by joeraz** [comment]
> Custom rules for other types?
> 
>     * [250+ Solitaire Collection](https://play.google.com/store/apps/details?id=com.anoshenko.android.solitaires) - supports Canfield, Algerian Patience, Retinue of King, Royal Secrets, Scorpion, Golf, Pyramid types.
> 
>     * [Solsuite](https://www.solsuite.com/) - undocumented (?) but have tried Baker's Dozen and it's possible to customize

So you're basically suggesting adding additional solitaire wizards that can set custom rules for different types of games (i.e. one for Montana-type games, one for pairing/pyramid-type games, etc.)?

**Comment by vavavr00m** [comment]
@joeraz Exactly and also add whatever's missing, if possible.

**Comment by joeraz** [comment]
I've considered doing something like that previously.  I'll review what would be needed to do something like that.

@vavavr00m What do you mean by "whatever's missing"?

**Comment by vavavr00m** [comment]
> What do you mean by "whatever's missing"?

If there are games & types from those two that can be added to PySolFC

**Comment by joeraz** [comment]
> > What do you mean by "whatever's missing"?
> 
> If there are games & types from those two that can be added to PySolFC

Oh, adding missing games.  I'm already doing that with about five or six different solitaire collection apps.  See the "Games by Compatibility" section in both the app and the gamedb.py file.

As a side note, if anyone wants to help with that, I could always use cross-references of the games with different solitaire collections to add to that list.

**Comment by joeraz** [comment]
Okay, so it sounds like the big things are enhancements to the solitaire wizard/plugin logic to be more flexible/accessible, and more games.  I'll add those to my list.

So now that I left the question open for a bit, I'm going to share my own thoughts - I have my own roadmap for the next year or two of PySolFC development, which will lead to a version 3.0.  I want to share my thoughts because version 2.0 was released in 2009, and I don't want to slap a "version 3.0" on a release lightly.  Just to be clear, nothing here is set in stone - some new ideas may come or features may change, so I'm not promising anything.  My development style is very impulsive and chaotic at times.

First, I'm planning a version 2.20.1.  Since the 2.20 release, most changes have been bugfixes and enhancements, so I'd like to get those out before I proceed on the bigger things.  Going to open an issue for this later.  The only other major thing I want before I push this release is to update the version of Python and the other dependencies in the Windows/Mac release packages, which requires a new version of PyInstaller to be released (see issue #272).

After that, I'm going to start on 3.0 features.  Aside from what I mentioned above, my main item is a change to the cardset format.  There are two additional types of cardsets I want to add, I want to add joker support for French cardsets, and a few other options.  I do plan to do these changes in such a way that existing cardsets will still work, but I consider this a 3.0 feature because the cardsets package is separate, and releasing one big update for this would make it easier for the people maintaining the Linux distro builds, rather than constantly forcing them to update the cardsets package after each change.

The two types of cardsets I currently wish to add are as follows:
- Picture Puzzle - These were actually present in older versions of PySol, as a type of matrix cardset.  For a while, I thought they were lost to history, but I was able to recover the cardsets from an old UltraSol release.  Basically, these let you play matrix games where you're trying to assemble a picture rather than just putting numbers in order.  I can also make a simpler tile puzzle game where you just freely switch pieces with each other to assemble the picture correctly.
- Ishido - Ishido is a tile board video game from the early 90s.  It uses a set of 36 tiles consisting of six colors and six symbols (36 total).  I've seen many Ishido clones and variations, so it would be an interesting game to add, but more importantly, a simple tile cardset like that is pretty versatile, and can be used to make a number of other new games.

I'm also looking into other ways to revive features from older versions that have been lost - I previously found some lost Mahjongg layouts that I wish to bring back, if I can confirm that they're good and playable (see issue #301), and there may be other lost content hidden in the PySol code, or UltraSol or FlowerSol.

Honestly, I could use a little help on some things.  I can probably handle it solo, but aside from coding, some help with graphics, testing, research into older versions of PySolFC, and spreading the word about a 3.0 release, would make things a lot easier.  I may post a request on the forums or the main website at some point.

Some of these might take a while, so I may cherry-pick some of the smaller features into a version 2.21 or 2.22, to make sure the project appears active while I'm working on the big stuff.

So that's my current plan.  I personally think with the hi-res support enhancements added since 2.12, there's enough for me to use the "version 3.0" label justly, but if anyone has any thoughts, I'd love to here them.  Thanks for reading this entire long post.

**Comment by Alucard648** [comment]
What about a cardset type that has 16+ suits and other miscellaneous cards for crazy solitaire games? I have found images from mod for the game called Tabletop Simulator. Credit goes to original creators: Giga Otomia and Synth Rose.
https://steamcommunity.com/sharedfiles/filedetails/?id=788257179
https://steamcommunity.com/sharedfiles/filedetails/?id=629179934
[16+suitcards.zip](https://github.com/shlomif/PySolFC/files/11130706/16%2Bsuitcards.zip)

**Comment by joeraz** [comment]
> What about a cardset type that has 16+ suits and other miscellaneous cards for crazy solitaire games? I have found images from mod for the game called Tabletop Simulator. Credit goes to original creators: Giga Otomia and Synth Rose. https://steamcommunity.com/sharedfiles/filedetails/?id=788257179 https://steamcommunity.com/sharedfiles/filedetails/?id=629179934 [16+suitcards.zip](https://github.com/shlomif/PySolFC/files/11130706/16%2Bsuitcards.zip)

If we want to add new cardset types, now is the time to do it.

However, I don't see any licensing information on those cards.  Unless the card images are open licensed (i.e. something GPL compatible, creative commons, or public domain), or we have the creator's direct permission to re-license them, we can't legally use them.  Also, I'd need to have a few sets of rules for games that would use that type of cardset.

**Comment by GigaOtomia** [comment]
Hello, I'm the creator of the linked set of cards. They were something I'd just drawn up in my spare time - I don't believe any proper licensing applies to them, especially considering I used art that doesn't exactly belong to me, which I just detailed in three comments on the steam page. I can draw up a more generic set of sixteen suits, if you'd like.

**Comment by joeraz** [comment]
> Hello, I'm the creator of the linked set of cards. They were something I'd just drawn up in my spare time - I don't believe any proper licensing applies to them, especially considering I used art that doesn't exactly belong to me, which I just detailed in three comments on the steam page. I can draw up a more generic set of sixteen suits, if you'd like.

If you can offer something like that, sure, we can use it.  Thanks.

Though we'd still need to come up with a few more sets of game rules that can use such a deck - I have a couple ideas, but they'll need some playtesting (further down the line).

**Comment by GigaOtomia** [comment]
I've got the base images ready, just need to populate them with ranks. Could we set up some other, more immediate method of communication than this comment section? My Discord handle, for example, is Giga#2931.

**Comment by shlomif** [comment]
On Sun, 02 Apr 2023 20:45:27 -0700
Giga Otomia ***@***.***> wrote:

> I've got the base images ready, just need to populate them with ranks. Could
> we set up some other, more immediate method of communication than this
> comment section? My Discord handle, for example, is Giga#2931.
> 

https://twitter.com/shlomif/status/1642561575805394948 

-- 

Shlomi Fish       https://www.shlomifish.org/
Let’s talk about restores instead of backups - https://is.gd/WatQqu

The Messiah will come when everybody assume his role.
    — https://www.shlomifish.org/philosophy/the-eternal-jew/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
> I've got the base images ready, just need to populate them with ranks. Could we set up some other, more immediate method of communication than this comment section? My Discord handle, for example, is Giga#2931.

We don't currently have anything like that set up - there used to be an IRC channel, but it hasn't really been active lately.  Personally, I find IRC a bit awkward to use, and I like to have a record of the conversations for later reference.

I know a few people here have issues with Discord, and I've been working on my own a lot lately, so I haven't had a chance to spin anything else up.

**Comment by joeraz** [comment]
@GigaOtomia I tried spinning up a chat on Zulip, if that would work better for more immediate/direct communication.  https://pysolfc.zulipchat.com/join/wybkcbxzgt2dc66767goaosy/

Mostly just trying this out at the moment.

**Comment by joeraz** [comment]
Been a little quiet here, but I've been doing some preliminary setup work (and some smaller updates).  First step would be to change the cardset format to allow for a cardset sub-type, so that within a type of cardset, some cardsets can be handled differently (i.e. French decks with or without jokers, or being able to create puzzle sets of different sizes without making each size a separate type).  This is going to require some changes in the cardset format, of course, so I'm also currently planning some cleanup/organization in the cardsets repo.  I currently don't expect this will break the existing cardsets, but the repo needs some cleanup anyway.

I think I have a good idea where I'm going with 3.0, but I'll leave this issue open for further comments.

**Comment by joeraz** [comment]
I've got the cardset subtype logic built, with support for joker decks.  Building off this should make it possible to add some of the new types of games and cardsets I mentioned.  If anyone wants to review, it's in PR #330.

**Comment by joeraz** [comment]
It's been quiet lately, but I am hoping to push the 3.0 release in January/February.  The enhanced solitaire wizard isn't yet in (working through some practicality issues), but if anyone wants to help with beta testing, let me know.  I could use some more beta testing support.

**Comment by joeraz** [comment]
I think the enhanced solitaire wizard might have to wait until 4.0.  There are a number of UI/design issues I'd have to sort out to get that working.  Might need another set of eyes on the design details.  I'll create a new issue for this later.

For now, I'll close this one, as there hasn't been any new comments recently, and I should probably put a cap on the new features for 3.0 soon, so we can actually get it released.
