### ISSUE TITLE
Pysol - Spider

### ISSUE THREAD

**Issue by Citron-99** [shlomif/PySolFC#297]
when playing spider sometimes descending sequences of cards which should be free to move and append to other  sequences become locked in place. I can free up a sequence some times by undoing last card or cards add this sequence. I am using The Fan Club Edition a world domination project version 2.18.0.
![Screenshot 2023-02-17 101233](https://user-images.githubusercontent.com/125676115/219692449-3bb07bbc-948e-4156-b681-335f05fbf2d5.png)

**Comment by joeraz** [comment]
I played a few rounds of Spider, but did not run across this issue.

Can you provide more details about what you were doing when it started, or send me a save game where the issue is occurring?

**Comment by Citron-99** [comment]
Hello,

 here is what happens to me when I play spider. The sequence terminating with the 10 of diamonds is frozen. I have, yesterday, installed a new copy of pysol which I download from Sourceforge , the problem remains. I have not had any problems with other types of solitaire. I have as requested a saved game with a frozen sequence. I have also included screen shots of the frozen sequence and a list of all types of solitaire played which, aside from spider all work. The PC is an  Acer Nitro AN515-44, the processor is an AMD Ryzen 5 4600H with Radeon Graphics 3.00 GHz and 32.0 GB of installed RAM. The operating system is Windows 10 Home, Version 22H2, OS build 19045.2604. Thank you for your quick response.

                Citron-99

![spider game](https://user-images.githubusercontent.com/125676115/220134076-fd3d9466-a0f8-4d34-9d16-9010137220bd.jpg)

![game list](https://user-images.githubusercontent.com/125676115/220134133-f98acd14-65c0-493a-af35-21ce87c7290b.jpg)


[Spider-06858685536734711808.zip](https://github.com/shlomif/PySolFC/files/10785424/Spider-06858685536734711808.zip)

**Comment by joeraz** [comment]
Based on what I see, this is working correctly.  In Spider, you can only move sequences of cards as a unit if they're all of the same suit.

**Comment by Citron-99** [comment]
problem solved, I was not following the rules.  You live and learn. thank-you for your help.

                    Citron-99
