### ISSUE TITLE
Switching between games in "Playable Preview" is slow (because of card dealing animation)

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#30]
Before you can see the next game all the cards/tiles of the previous game have to be dealt. Maybe animations should be disabled for this mode altogether, I guess the user wants to "preview" a given game as quickly as possible, and animations don't help with that.

**Comment by joeraz** [comment]
There already was logic in play to speed up the dealing animation for playable preview, though it would only apply for games that had particularly slow dealing animations.

Nonetheless, I reconfigured this logic so it would just skip the animation in preview mode.
