### ISSUE TITLE
Verify Flathub entry as official

### ISSUE THREAD

**Issue by ssokolow** [shlomif/PySolFC#300]
The [beta version of Flathub's UI](https://beta.flathub.org/apps/io.sourceforge.pysolfc.PySolFC) adds support for marking entries as approved by the upstream developers.

It's basically the same process as verifying that you should be allowed to access something like the Google Search console for site admins.

1. Log into https://beta.flathub.org/userpage (it uses GitHub or GitLab OAuth)
2. Hit the "Developer Settings" button under PySolFC
3. Click "Website verification"
4. The wizard will prompt you to add a file to the PySolFC website to prove that you are or are working with the upstream developer.

I believe you'll need to have enabled the GitHub OAuth login option for it to pick up PySolFC as something you're authorized to verify.

**Comment by joeraz** [comment]
I just attempted this.  The file is up at pysolfc.sourceforge.io, but Flathub is just checking sourceforge.io, ignoring the subdomain.

**Comment by ssokolow** [comment]
Ugh. Given that the same bug would appear with GitHub Pages, that's a very surprising bug on their end.

I'll look into who to report it to later tonight.

**Comment by ssokolow** [comment]
OK, it looks like the place to report the problem is here:

https://github.com/flathub/website/issues

Since you're the one actually looking at the symptoms first-hand, it'd probably be better for you to file the bug, but I could if you'd prefer that.

**Comment by joeraz** [comment]
I created the issue, thanks.

**Comment by joeraz** [comment]
Note for reference - the user page URL has moved to https://beta.flathub.org/my-flathub.

**Comment by joeraz** [comment]
So a PR was created, that I think would have resolved this, and let us finally get PySol verified.  But then drama ensued.

See ticket 1939 over on the Flathub website repo.

**Comment by joeraz** [comment]
The issue with SourceForge domains has been sorted, and I've been able to get PySol successfully verified.
