### ISSUE TITLE
apk does not install on pixel 7

### ISSUE THREAD

**Issue by Caramellegommose** [shlomif/PySolFC#303]
i cannot install the apk on pixel 7, that might be because of the only 64bit lock or android 13

**Comment by lufebe16** [comment]
The current fdroid version does only support armeabi-v7a (32 bit). I hear the first time that google now skipped 32 bit support for some devices. Thanks for that hint.
So I plan to also support arm64-v8a with the next f-droid version.

In the mean time, if you own the necessary equipment, it would be an alternative to
homebrew your 64 bit version. You will have to change the entry  'android.archs' in ./buildozer/buildozer.spez to:

android.archs = arm64-v8a

and then apply the steps for building. Consult ./buildozer/build-instructions.txt to learn how.
