### ISSUE TITLE
Cant find/remember location for android cardset location?

### ISSUE THREAD

**Issue by lex81** [shlomif/PySolFC#304]
I forgot where to place cardsets for android pysolfc... Thank you for your work and thank you for updating/improving android version!

**Comment by lex81** [comment]
I just tried ~/PySolFC/cardsets but it still does not load my cardset

**Comment by joeraz** [comment]
It's ${HOME}/.PySolFC/cardsets/

But this only works in Android 9 or lower due to permissions limitations with Android 10.

**Comment by lex81** [comment]
joeraz, thank you for your help. Could you add an option in the future to use any local folder that would be accessible by android permission?

**Comment by joeraz** [comment]
I'd have to ask @lufebe16 about that one.

**Comment by lufebe16** [comment]
@lex81
As already mentioned (and double checked on my android emulator):

From Android 10 (API 30) and more you can allow access to media files on external storage only. Thus ~./.PysolFC is not accessible to the app any more.

Maybe this might work still (for a while) for older apps, not built with androidx. But as the build procedure for the app uses gradle (a Google build tool), that forces developpers to build for the latest possible API version, these new access restrictions will apply immediatly.

 So (unless you have a rooted device) you will not be able to find the location to store your card sets. On a rooted device you may try to install your cardsets under: /data/data/org.lufebe16.pysolfc/files/.PysolFC/Cardsets

**Comment by lex81** [comment]
ok. The other option I have is to include the cardset in private.tar. Im just not sure how you guys are compressing the archive. Thank you @lufebe16
