### ISSUE TITLE
cardset contribution "z minimal" by lexterror

### ISSUE THREAD

**Issue by lex81** [shlomif/PySolFC#305]
Hi, I just finished a new cardset design using inkscape.

Feel free to distribute/modify!!!

[cardset-z_minimal.zip](https://github.com/shlomif/PySolFC/files/11058706/cardset-z_minimal.zip)

![preview](https://user-images.githubusercontent.com/68161611/227434587-d4e870d5-ea7e-4aed-b0d3-0144c1a08d3b.png)

**Comment by lex81** [comment]
Ive just updated the cardset with some more features Im also providing the vectors svg. its included in the zip.

Thank you!
[cardset-qcolorminimal.zip](https://github.com/shlomif/PySolFC/files/11062047/cardset-qcolorminimal.zip)

![PreviewQColorMinimal](https://user-images.githubusercontent.com/68161611/227522181-2d8058ba-3d48-4d6d-884b-2faa26a66dca.png)

**Comment by joeraz** [comment]
Thanks.  Will review when I get a chance.

**Comment by lex81** [comment]
You can use the same GPL as PySolFC. lex81 is fine. Also, go ahead with including the cardset at the moment. I will work on the jokers very soon. As soon as I have them done I will post them for you. If you have further questions let me know @lex81 or @LexTerror. Thank you so much!

**Comment by joeraz** [comment]
Okay, added.

No rush on the jokers - it's going to be a while before I might need them.
