### ISSUE TITLE
Red/Green Felt 4K Background Contribution

### ISSUE THREAD

**Issue by lex81** [shlomif/PySolFC#307]
Hi joeraz, 

Im still working on the jokers. I wanted to provide you with two 4k felt backgrounds. Im also providing the xcf gimp template I created which allows you to control the color of the felt in case you wanted a different color as well. the jokers will be my last contribution to pysolfc. Thank you for your time.

https://www.mediafire.com/file/49m0tsu3vn2uw4x/PySolFC_4k_Felt.7z/file

![PySolFC_4k_green_felt](https://user-images.githubusercontent.com/68161611/229003025-99ac3da7-d55d-4761-bc8b-54f2438c3b49.jpg)

![PySolFC_4k_red_felt](https://user-images.githubusercontent.com/68161611/229003062-1d2309bb-833c-4acc-a6a4-525d3d6368e9.jpg)

**Comment by joeraz** [comment]
I'll add those.  Thanks.

**Comment by joeraz** [comment]
Added.
