### ISSUE TITLE
Joker / Wood Gloss Background Update

### ISSUE THREAD

**Issue by lex81** [shlomif/PySolFC#308]
Hi joeraz,

I finished the joker. Im providing the templates in a zip file on mediafire. Also, Im providing an update for wood gloss background I created for your game a few months ago, this version is 4k. I was thinking you could just replace/update the background with the new one so that the backgrounds dont become redundant. Thank you!

![joker](https://user-images.githubusercontent.com/68161611/229499616-3dcb5385-f1a5-49b8-a8e0-c6c85e4e5fad.png)

![joker](https://user-images.githubusercontent.com/68161611/229500198-b1442b8f-5ddb-4af9-967d-b137d63c5133.svg)

![WOODSY_4K_PySolFC -Release](https://user-images.githubusercontent.com/68161611/229500231-53bcc74d-d52d-474f-bcb3-6161358fe610.jpg)

**Comment by lex81** [comment]
https://www.mediafire.com/file/jlb3oqnx8sn2290/JoKer_Woodsy4k.zip/file

**Comment by lex81** [comment]
Hi joeraz,

I just edited the previous joker. this is my final modification, see which one you like better.:

![joker_final](https://user-images.githubusercontent.com/68161611/229553619-a0880768-6475-41e2-8929-473fae203745.png)

![joker_final](https://user-images.githubusercontent.com/68161611/229553708-bc470b20-3bf5-4a60-96f0-a776dddd631e.svg)

**Comment by lex81** [comment]
this is the vector for the file above:

![joker_final_fx](https://user-images.githubusercontent.com/68161611/229555257-d0787789-ab57-4e46-90c9-151fea3dc7a1.svg)

**Comment by joeraz** [comment]
Will review and add these, thanks.

**Comment by joeraz** [comment]
Updated the tile.  Jokers set aside for later use.  Thanks.

**Comment by lexterror** [comment]
Hi @joeraz 

I've had some extra time to work on things. I've updated the joker card... I think this one is not bad at all and would like it to be the final version of the two above if that's ok.

![joker_final](https://github.com/shlomif/PySolFC/assets/16135535/7c1b48c0-74dc-4fa1-8783-7a3f70e4db8c)


![JOKERfinal](https://github.com/shlomif/PySolFC/assets/16135535/59921b3c-b2fd-4860-8b35-bb74a7b14100)

**Comment by joeraz** [comment]
Yes, I do like that design.  Will see how it works in the cardsets - thanks.

**Comment by lexterror** [comment]
@joeraz 

Thank you so much for your time... This is a variation of the last one.. Feel free to comment/have final word. Thank you! I think I'm now going to focus on other things. If needed I'm here.

![myjokerminimal](https://github.com/shlomif/PySolFC/assets/16135535/812cca2e-ed2d-4acf-b082-bae6ec3793b3)

![myjokerminimal](https://github.com/shlomif/PySolFC/assets/16135535/93e6f6e4-859a-4948-b9cc-faa7adb76ef2)

**Comment by lexterror** [comment]
@joeraz 

Hi, I just wanted to share this background I made with Inkscape. It's a vector. The color gradient can be changed to any color combination possible. Also, what makes it nice is the miniature dots that are arrange according to a specific golden ratio. I'm proving you with the vector. However the size of the vector is about 40MB which does not fit here so I'm going to post it on mediafire. If you like it it's available for everyone. It's similar to the felt one but I think it's much nicer in my opinion. 

![goldenratiobackground](https://github.com/shlomif/PySolFC/assets/16135535/7417cd31-5084-45fa-8f5f-7eb48f27d0dd)

**Comment by lexterror** [comment]
This is a colored version of the Joker card. Thank you! Feel free to change/modify

![myjokerminimal_colored](https://github.com/shlomif/PySolFC/assets/16135535/a737c050-ff80-4f8d-82cd-6a0b6450f8e4)

![myjokerminimal_colored](https://github.com/shlomif/PySolFC/assets/16135535/a2d1dda2-d27b-4cdd-b249-92e662728b99)

**Comment by lexterror** [comment]
Lastly, here is a colored gradient version of the complete cardset. Thank you!

![previewgrad](https://github.com/shlomif/PySolFC/assets/16135535/1696b313-61a6-4775-ab89-454e85c495de)

[SVG_Zminimal_Grad.zip](https://github.com/shlomif/PySolFC/files/13195512/SVG_Zminimal_Grad.zip)

**Comment by joeraz** [comment]
Thanks.  Adding a version of that golden ratio background.

Any chance I could get a copy of the SVG files from the original two-color Z Minimal?  I'd like to try and regenerate them all to make sure the PNGs are all in a consistent size and style, and I only have the four color version.

**Comment by lexterror** [comment]
@joeraz 

Hi, try the first four color version I posted... all the svg elements for each card are separated for ultimate customization. Its the exact same as the two color version only its four colors not two. I deal with a lot of files and I often misplace/delete old projects. I dont have the 2 color version on disk Im going to repost the four colored version from a few months ago. It only takes about 20-30 minutes max to change all the card colors in inkscape/illustrator...

**Comment by lexterror** [comment]
this is the one from the other post. All elements separated for each card. It includes all the svgs. They are located in the "Svg" folder. Thank you!

[cardset-qcolorminimal.zip](https://github.com/shlomif/PySolFC/files/13198939/cardset-qcolorminimal.zip)

**Comment by lexterror** [comment]
Ok Done!!! I've edited the above cards with only black/red. I also used a slightly gray white and a dull black/red for good contrast. Feel free to modify/change/distribute as you wish. Thank you so much! All are svgs!

![Screenshot_2023-10-29_18-22-04](https://github.com/shlomif/PySolFC/assets/16135535/a67f6f7c-8f04-46e5-a047-13b54d38bb4a)

[svgblackredfulldeck.zip](https://github.com/shlomif/PySolFC/files/13199397/svgblackredfulldeck.zip)

**Comment by lexterror** [comment]
@joeraz 

Hi, I really need to get back to doing other things... but I just tried to mimic the background from Mahjong Titans in "Gimp" on Xubuntu Linux (I did a pretty good job with it) I've seen similar backgrounds in other card playing games too. But I also did this one by scratch... Again just the PNG is 40MB so I'm posting the large one I just made on mediafire... I made a 4K background as usual... 

https://www.mediafire.com/file/9op5tu5v9xivqr1/MyTitanBasketWeave.png/file

It's a woodsy weave background (let me know what you think) 

![MyTitanBasketWeave_preview](https://github.com/shlomif/PySolFC/assets/16135535/3fb0461f-f6f4-420a-ace8-8a5af9ac2571)

I based the idea on the background for this game:

![3218780-mahjong_1](https://github.com/shlomif/PySolFC/assets/16135535/c598e0aa-dce3-477d-adbd-3883e991b9aa)

**Comment by lexterror** [comment]
Ok I found the exact weave they use. It's called a "Rattan" mat weave. Here is another one of my versions again: 

https://www.mediafire.com/file/cnee63v4mwso261/TitanBasketWeaveRattan4K.png/file

![TitanBasketWeaveRattan4Kpreview](https://github.com/shlomif/PySolFC/assets/16135535/50e0cd02-64e7-4d2c-80d2-ce6625580720)

**Comment by joeraz** [comment]
Thanks!

**Comment by lexterror** [comment]
@joeraz 

hi, those last two textures are rough drafts, just because I spent very little time with them please do not include them as they are not acceptable imo, unless you think otherwise.. I was wondering whether my latest wallpaper that has nothing to do with pysolfc might be acceptable.. I just remembered there is a game with such a type of wallpaper. it makes it relaxing to play card games with a bluesky/beach/sand background...this is what my latest wallpaper looks like. I would just have to render it without the sculpture???.

**Comment by joeraz** [comment]
I'll never say no to more background images/tiles - will add that last one to the list, didn't yet add the other two.  Though I've added some myself, for the most part, the ones I've added are just images from various public domain picture sites that I test out and think look good in game.  So we don't have any specific requests concerning table tiles at the moment.

We do have a couple non-table tile related image editing tasks open, if you're interested in the details on them, though they're more about editing some existing images rather than creating new ones.

Just note that 4K table tile images will likely be filtered out of the Android builds going forward due to their large file size.  It's not yet an issue for the Windows and Linux builds, but if we get enough that they start to inflate the download package sizes too much, I might have to increase the image compression further.

**Comment by lexterror** [comment]
Ok, so this basket weave texture is final and you should include it if you think its good enough. Its a 3d model weave I made in Blender and then edited in Gimp. The detail is really nice!

[Img]https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/68d205c1-6126-4b75-88fc-e620e9a1afa6/dgewzv3-973174a2-c461-4ec4-870b-fa34b82f3310.png/v1/fill/w_1280,h_1280,q_80,strp/basket_weave_texture_3d_4k_by_electrolex_dgewzv3-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcLzY4ZDIwNWMxLTYxMjYtNGI3NS04OGZjLWU2MjBlOWExYWZhNlwvZGdld3p2My05NzMxNzRhMi1jNDYxLTRlYzQtODcwYi1mYTM0YjgyZjMzMTAucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.kIEbno-N7EaTcI7jqLT-VWd-QbG1Y52A1H1m6IfmXlI[/img]

**Comment by joeraz** [comment]
I'll add it then, thanks.

**Comment by joeraz** [comment]
No problem, and thanks.

(Yeah, I know this is more for managing the project - tried to set up a Zulip chat, but there wasn't any interest.  So we just got here and SourceForge)
