### ISSUE TITLE
Issue with pl_pysol.po file (and pot as well?)

### ISSUE THREAD

**Issue by Arthusppp** [shlomif/PySolFC#316]
I am struggling the following: the pl_pysol.po (and the pysol.pot) contains:

```
#: pysollib/tile/playeroptionsdialog.py:50
#: pysollib/tk/playeroptionsdialog.py:90
msgid ""
"\n"
"Please enter your name"
msgstr ""

```

And in the code we have slightly different text:

```
        widget = tkinter.Label(frame, text=_("Please enter your name"),
                               # justify='left', anchor='w',
                               takefocus=0)

```

Given this, I am unable to translate the text in this window:,
![image](https://github.com/shlomif/PySolFC/assets/85434237/e90e2d9c-f88a-4863-b5b6-9f557e8726f9)

When I manually remove new line, everything works as intended - the translation works fine:
```
#: pysollib/tile/playeroptionsdialog.py:50
#: pysollib/tk/playeroptionsdialog.py:90
msgid "Please enter your name"
msgstr "Podaj swoje imię"

```

![image](https://github.com/shlomif/PySolFC/assets/85434237/2a555003-235a-4ff1-9ed9-07e315308460)

The issue I am raising here: how to solve this? For example: can we refresh the pot file based on current source code? Or should I change this manually in the pot file and all po files? (but I am not 100% sure how many texts are affected by this problem).

**Comment by joeraz** [comment]
There currently isn't a way to auto-generate the pysol.pot file - I've just updated it manually when adding new strings, then used POEdit to update the PO files to use the updated POT (or just update them manually too, depending on the nature of the change).

The games.pot file, on the other hand, is automatically generated.
