### ISSUE TITLE
Please add lock rotation options for android/mobile

### ISSUE THREAD

**Issue by bps86** [shlomif/PySolFC#320]
I enjoyed playing this version of solitaire on mobile, best so far. Sadly, I haven't see an option to lock rotation and it gets annoying when the screen keeps rotating. Please consider on adding that feature, I appreciate it.

**Comment by falsifian** [comment]
I would also like this. Most other apps respect my systemwide rotation setting; is PySolFC going out of its way to deliberately implement its own rotation or something?

Lovely app btw!

**Comment by joeraz** [comment]
@lufebe16 Do you know anything about this?

**Comment by lufebe16** [comment]
Thanks for Your feedbacks. I just made a note for my next updates to study the case.

**Comment by theolaa** [comment]
Just bumping as I am also running into this issue. It's basically impossible to play while lying on my side as the screen will rotate sideways regardless of whether my phone is set to autorotate or not.

**Comment by theolaa** [comment]
Apologies, I see that this has been addressed. Any word on when an update might be available on F-Droid?

**Comment by joeraz** [comment]
I'd need to release the next version of the app first, which is getting there, but not quite ready yet - probably another month or so, but it depends on when certain critical items get fixed.  Once that update goes out, F-Droid will probably get an update soon after.

@lufebe16 - Can you confirm if we can close this issue?  Or is there something that still needs to be done on it?

**Comment by lufebe16** [comment]
The screen rotation lock implemented in the current master
has been implemented as a temporary lock. It locks as soon as you
begin to play. It unlocks on pause and when selecting a menu.

@joeraz 
The Kivy/Android version is ready and waits to be released. 
As far as I'm used to test it, it seems quite stable.
Originally I planned to release in the first months of next
year. A fully perfect desktop release with all new features
is not strongly required. Could also be a fairly stable
prerelease.

**Comment by theolaa** [comment]
> It locks as soon as you begin to play. It unlocks on pause and when selecting a menu.

I'm not sure that's a great solution either. I still don't want the app to rotate if I open the menu when I'm lying down. Wouldn't it be best to just have it follow the system-wide autorotation setting? Or at least have an option somewhere to make it behave that way?

**Comment by joeraz** [comment]
> @joeraz The Kivy/Android version is ready and waits to be released. As far as I'm used to test it, it seems quite stable. Originally I planned to release in the first months of next year. A fully perfect desktop release with all new features is not strongly required. Could also be a fairly stable prerelease.

I'm admittedly holding this next release to a higher standard than usual - I think this will be version 3.0 after all.  But at this point, outside of new games, most of the new features I'm adding are minor enhancements, QOL things, or just bugfixes.  I'd also like to finally get it out in January/February.

**Comment by lufebe16** [comment]
@theolaa There is no global system setting that obligates apps.
Apps are in general free to rotate the screen as it is needed.

With the current app, some games need to be played better
in portrait, others better in landscape mode. Its the
users decision.

How would you like to unlock locked screen rotation if not
restarting the app. Any suggestion ?

**Comment by lufebe16** [comment]
@joeraz Thats o.k. for me, thanks.

**Comment by falsifian** [comment]
> @theolaa There is no global system setting that obligates apps. Apps are in general free to rotate the screen as it is needed.
> 
> With the current app, some games need to be played better in portrait, others better in landscape mode. Its the users decision.
> 
> How would you like to unlock locked screen rotation if not restarting the app. Any suggestion ?

There is a global setting that at least hints to apps whether the user would like the screen to automatically rotate. I am not an Android developer and do not know how it works, but on my settings panel there is an "Auto-rotate" toggle. When it is enabled, then in most apps, the screen will automatically rotate when I tilt the phone. When it is disabled, none of my apps automatically rotate the screen, *except PySolFC*. This is the setting I, and I believe others, are talking about.

**Comment by theolaa** [comment]
@falsifian Yeah, that's exactly what I'm thinking of.

@lufebe16 As for solutions, my personal ideal solution would be for the app to strictly follow the system autorotation setting, with an option to allow free rotation regardless (the way it currently behaves). I wouldn't even mind if the current behaviour is the default behaviour, but at least having the option to disable the free rotation somehow would be really nice.

**Comment by theolaa** [comment]
@lufebe16 Having poked around the app, there's a couple free-standing settings at the bottom of the options menu for the starting splash and the winning splash. I think that would be the perfect spot for this option, something to be toggled on or off like "+/- Lock screen rotation", "+/- Free screen rotation", etc.. However it's best to word it.

**Comment by bps86** [comment]
@falsifian yes, there is that in most apps. However, I think what lufebe meant was whether the player want the screen to be locked at portrait or landscape.

@lufebe16 Hmm, I don't know how this game developed for android or the android studio stuff. I only used unity engine and they have something like screenorientation variable. I was wondering if that variable is available here and can be set from code. If its possible, then user can set variable to auto, landscape and portrait at settings, then save it to config. If it requires restart, you can add notification to user with something like "Restart the app to apply these changes..."

**Comment by theolaa** [comment]
@joeraz @lufebe16 Thanks for the update guys, works great for me now!
