### ISSUE TITLE
Merge "All games..." with "Playable preview..."

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#33]
"Playable preview..." offers the same functionality as the "All games..." option + much more. Thus, I suggest renaming "Playable preview" to "All games...", and getting rid of the old "All games..." view altogether.

Of course, for this change to make any sense, [the problem with slow switching between games in "Playable preview..."](https://github.com/shlomif/PySolFC/issues/30) has to be fixed first.

To fully understand my vision of enhancing "Playable preview..." (or the "All games..." view after renaming) check these issues too: https://github.com/shlomif/PySolFC/issues/34 https://github.com/shlomif/PySolFC/issues/35

**Comment by joeraz** [comment]
As I already disabled the animation in Playable Preview, I went ahead and merged these screens.  Done.
