### ISSUE TITLE
Android: toolbar buttons are too close together in landscape mode

### ISSUE THREAD

**Issue by sahi1l** [shlomif/PySolFC#333]
Might just be my phone, but the toolbar buttons are much too close together for landscape mode (and in portrait mode the cards are usually too small to see).  I frequently, accidentally press the "new game" or "refresh game" when I am trying to undo multiple moves, which is very frustrating.
If I may make a few suggestions:
- Ideally, let me customize the toolbar and deactivate any buttons I like.  This would probably be a pain.
- Remove a few buttons so that they can spread out a little more.  The "Exit" button is unnecessary on a phone or tablet, for instance, and I have no idea what the two arrows button is supposed to do.
- Split the toolbar into two parts: the first five icons on the left, the other five on the right.  Or make that an option.
- Maybe add an optional "Are you sure?" dialog box to the buttons that are irreversible.

**Comment by joeraz** [comment]
Mostly been working on the desktop version, but I do know a thing or two about the toolbar buttons:

- The option to select which buttons are visible on the toolbar does exist in the desktop version.  I'm not sure if there's a reason it wasn't added to the Android version's menu - if there isn't, it can probably be easily added.
- The two arrows button is shuffle tiles.  It's only used for Mahjongg games, so it shouldn't show for other games.  If it is, I'd consider that a bug.
- I'd like it if there was a way to configure toolbar buttons to not appear in Android - there are a couple additional buttons I was considering adding for options that wouldn't work in Android.
- The confirmation message for some options was previously requested as issue #210 - I agree that should be a thing, just not sure how to set up a confirmation window in Kivy.

I'll add the Android label to this one for now.  @lufebe16 might some thoughts on this.
