### ISSUE TITLE
Jokers are referenced in the dev build in games like Golf"thieves" but no way to access them.

### ISSUE THREAD

**Issue by LinuxBeaver** [shlomif/PySolFC#335]
![image](https://github.com/shlomif/PySolFC/assets/78667207/1ef952a0-83d4-452b-8ad0-038862d14730)

Here's an example. Is there any way to download a joker deck and play a game with the jokers?

**Comment by LinuxBeaver** [comment]
It ask me to select a french deck, but none of the french decks are obviously compatible.

**Comment by joeraz** [comment]
Yes.  If you're using the develop version, use the cardsets from the latest version of the cardsets repo: https://github.com/shlomif/PySolFC-Cardsets - this contains some joker decks and any other new cardsets/cardset types used by the latest code.

**Comment by LinuxBeaver** [comment]
ok, it works thanks.

**Comment by joeraz** [comment]
No problem.
