### ISSUE TITLE
Logo Tweaks

### ISSUE THREAD

**Issue by bubonicfred** [shlomif/PySolFC#336]
Hi, thought I'd give a stab at polishing the logo a bit (not the most pressing issue I know).
Started with the bit that annoyed me most, the composition of the dashed line, I tried this first some months ago without success, but recently found a new method.
Made the dashes follow the shape outline, made them consistant sizes, made the corners nice, realigned the two circles on the corners.
Can of course change the sizes of the dashes etc. but thought I'd post here for any feedback.
![logo](https://github.com/shlomif/PySolFC/assets/1294298/1ea327e5-43ec-474d-901b-7b8da5a54d66)

**Comment by joeraz** [comment]
Not bad.  The dotted lines do look cleaner.  Although it also looks like the upper corner of the card is cut off.  Also, was the font of the A changed?

**Comment by joeraz** [comment]
Never mind about the font - it just looks different on different computers.  A quirk of SVG, I guess...

**Comment by bubonicfred** [comment]
> Not bad. The dotted lines do look cleaner. Although it also looks like the upper corner of the card is cut off. Also, was the font of the A changed?
Easy fixes
![logo](https://github.com/shlomif/PySolFC/assets/1294298/635a7c64-9d0e-46e1-b608-be5a00634c4d)

**Comment by joeraz** [comment]
Looks good to me.  Anyone else have any thoughts?

**Comment by bubonicfred** [comment]
I'll mirror the changes over to the horizontal version and try to figure out how to export the raster variants (hopefully with a script), then put in a PR

**Comment by joeraz** [comment]
Great!  Thank you.

**Comment by bubonicfred** [comment]
Realised while exporting raster versions that the original svg used Myriad Pro as the font for the A, given I don't have Adobe fonts I can't export that properly. I've substituted in Open Sans (which uses the same OFL license as Trueno) which is in the same style and is a variable font, meaning I can adjust the weigh and width as well as the size.
here's a size by size comparison, managed to get Open Sans looking pretty close.
![logoA](https://github.com/shlomif/PySolFC/assets/1294298/58509823-f267-4446-87df-7d45e240300a)

**Comment by joeraz** [comment]
Good catch - using open fonts will make it easier for anyone else who wants to work with the logo later on.

**Comment by joeraz** [comment]
Updated logo merged.  Thanks.
