### ISSUE TITLE
Game ideas: Short Picture Gallery (one deck variation of the classic game)

### ISSUE THREAD

**Issue by LinuxBeaver** [shlomif/PySolFC#338]
Is it possible to make two new games for Pysol that feature Picture Gallery with both one deck and four decks? I'd like to see that.

**Comment by joeraz** [comment]
I actually did some experimenting on the idea of a one-deck Picture Gallery sometime last year.  I found that Picture Gallery doesn't really work too well as a one-deck game.  It's a lot more difficult to free up the tableau piles, so usually, the player is barely able to make any moves, and quickly gets critical cards blocked, and loses.  It's also not that uncommon to get a deal where the player can't free up any tableau piles, and can't do anything other than futilely deal through the talon.  If you'd like a plugin for this, or a branch, I can set it up, but I think a single deck Picture Gallery needs something a bit more to work.

Four-deck, on the other hand, not a problem.  I did previously add some three or four deck variants of some Picture Gallery variants, but never did anything with the original Picture Gallery.

**Comment by LinuxBeaver** [comment]
So, is the plugin like a .py file I put somewhere in Pysol to get the game. 

yes sure. I'll experiment with 1 deck and a 3 or 4 deck variation of picture gallery via the plugin.

**Comment by joeraz** [comment]
Yes.  A plugin is just a .py file you can stick in your plugins folder to add an additional game, or content.  See https://pysolfc.sourceforge.io/doc/plugins.html

I'll set something up and get back to you soon.

**Comment by joeraz** [comment]
Here you go - this contains a copy of the Picture Gallery code, along with a simple one-deck, three-deck, and four-deck version.
[picturegallerytest.zip](https://github.com/shlomif/PySolFC/files/12825519/picturegallerytest.zip)

**Comment by LinuxBeaver** [comment]
Ok, I got the (Plugin) picture galleries in the game list. Thanks!

**Comment by LinuxBeaver** [comment]
I played several games of  three and four deck PG, nice. 

![image](https://github.com/shlomif/PySolFC/assets/78667207/d0164d56-5346-4be2-b861-58cc108b1206)


But you are right, 1 deck just doesn't come out. Unless of course modification exist such as possibly 1 deck PG with a 2,3, and 4 in their correct slots. But I'm not sure if that would increase the likelyhood of winning the game.

**Comment by joeraz** [comment]
That lines up with my thoughts.  I'll make a note to put the three and four deck versions in the main gamedb.

If you want to try a version where the twos, threes, and fours are pre-dealt to the right piles, the _shuffleHook from the game Mount Olympus could probably be easily rewritten to do that.

**Comment by joeraz** [comment]
I added the three and four deck versions to the main app.  We might be close enough to having enough picture gallery variants now to give them their own category.

Would you like to continue reviewing one-deck variants to try and come up with one that works, or should we leave it be?

**Comment by joeraz** [comment]
Since I haven't heard anything else, I'll leave this be for now and close this.  Though I'll accept a PR or a patch file if anyone finds a combination of game rules that would work for a one-deck picture gallery type game.
