### ISSUE TITLE
Problem with 'Napoleon's Tomb'

### ISSUE THREAD

**Issue by DetRellim** [shlomif/PySolFC#348]
The Middle pile was to go 65432A65432A6f432A etc. What happens is that the middle pile goes 65432A23456789JQKA2345 etc. The 4 Corners appear to work from 7 - K okay.

First time doing this, I hope it is okay. Love the game! A great piece of work! Been using it for years.

Version 2.16.0

**Comment by joeraz** [comment]
The foundations for Napoleon's Tomb were fixed in version 2.18.0.
