### ISSUE TITLE
Hanafuda Four Seasons Win Not Recognized

### ISSUE THREAD

**Issue by ThickMcPunchhard** [shlomif/PySolFC#354]
Hanafuda Four Seasons will repeatedly say you are stuck, but the game is possible to solve. Once solved, it does not recognize the game as a win. Image is the game I finished with after being told I was "stuck" 5 or 6 times with no recognized win. "Stuck" message often happens when there is an empty row, but also during moves when all rows have at least one card. Happens both on Android and Windows. 
![Screenshot 2023-12-13 132838](https://github.com/shlomif/PySolFC/assets/128434580/53dd361c-3fe5-47ad-bde8-807a3e751531)
![Screenshot 2023-12-13 131821](https://github.com/shlomif/PySolFC/assets/128434580/14bc5aa2-c174-416d-a0e8-d0e9fc4a63e2)

**Comment by joeraz** [comment]
In Hanafuda Four Seasons, the sequences have to be placed in the correct hanafuda suit order for the game to be won.

**Comment by ThickMcPunchhard** [comment]
Thank you for the update, I'm new to this kind of game. It would be great to have the suit order in the game rules. I still can't find that after going back and looking at them, the General Hanafuda Rules, General Rules, Glossary, or Fan Rules links that are in the instructions. I tried Demo about 20 times, but they all wouldn't "come out" and stopped.

**Comment by joeraz** [comment]
The suit order is a trait of Hanafuda decks, and is important in many Hanafuda deck games - it's mentioned in the general hanafuda rules page, but I can try to update the doc for clarity.

This image shows the correct suit order:
![hanahelp](https://github.com/shlomif/PySolFC/assets/2691813/b12c9e48-f345-47e5-887d-aabf1291742b)

**Comment by joeraz** [comment]
I added another section to the Hanafuda general rules page to provide a little more clarity on the order of the suits, and its importance to the games.

This should hopefully help alleviate the confusion.
