### ISSUE TITLE
Themes aren't working for me in Windows 11.

### ISSUE THREAD

**Issue by LAPIII** [shlomif/PySolFC#361]
Has anybody else experienced this issue?

**Comment by joeraz** [comment]
Just tested this myself on my Windows 11 computer, and themes are working fine for me.

Can you let me know which themes you're trying, and what's happening when you try to change theme?

**Comment by LAPIII** [comment]
I've been trying to set different themes including Blue and Plastik. After I select the theme I get:

These settings will take effect
the next time you restart PySol
