### ISSUE TITLE
Klondike 3 draw

### ISSUE THREAD

**Issue by AndyM48** [shlomif/PySolFC#370]
On the PC version I edited Klondike to make it three card draw. The edit function is not available in the android version.

 Is there a 3 draw klondike version available among the myriad of games in the android version?

**Comment by joeraz** [comment]
Yes, the game you're looking for would be "Klondike (Draw 3)".  It exists in both the PC and Android versions.

It may also be called "Klondike by Threes" in older versions.

**Comment by AndyM48** [comment]
Thank you. I found it under French games.
