### ISSUE TITLE
Clean up duplicate images - GIFs and PNGs

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC#371]
I noticed throughout PySol, there are a number of duplicate image files - one GIF image and one PNG image.  I believe we should be able to clean up some of these duplicates to reduce the size of the app.  Due to PNG being an overall superior format, I think we can just get rid of the GIFs where there's an equivalent PNG file.

This is probably because PNG was still an emerging format in the late 90s to early 2000s, though it's a standard today.  However, even Python 2.7 supports PNG.  Plus, some of the newer images are PNG format only, and there have not been any reported issues with these images.

I mainly want to confirm if there's a specific reason we need both before proceeding with a major change like this (i.e. some platform I'm not thinking of that requires the GIFs).

**Comment by shlomif** [comment]
Hi! I think it is OK as far as I am concerned. :+1:

**Comment by joeraz** [comment]
Okay, I'll get started on this cleanup sometime in the next couple days then.

**Comment by joeraz** [comment]
Cleaned up most of the files.  The finder images is all that's left (there are some duplicate folders and unused smaller images there, so it might need a closer look).

**Comment by joeraz** [comment]
Okay, all the old images should be cleaned up now.  Closing.
