### ISSUE TITLE
game finished message buggy? (zero used hints)

### ISSUE THREAD

**Issue by Duke-M-commits** [shlomif/PySolFC#372]
![image](https://github.com/shlomif/PySolFC/assets/69652463/c1f70d2b-57f8-4ce2-9fc5-0d2a2e9a567e)
Is this behaviour on purpose? 
Getting a notification about not finishing the game without hints, because of 0 used hints :D

STR:
* i played a round of Spider Solitair
* pressed accidentially Ctrl+D (start Demo animation) instead of Ctrl+S (save)
* pressed escape (game went into pause mode)
* resumed from pause mode (clicked on the pause text)
* at this point the demo animation had moved some of my cards, i pressed undo until everything looked as before
* finished the game regulary and got the message

**Comment by joeraz** [comment]
In addition to using hints, that message can also be triggered by using the demo (hence why PySol asks to confirm before you start the demo on a partially completed game).

That being said, you're right that the verbiage of the message is a bit misleading.  I'll look into updating that.

**Comment by joeraz** [comment]
Okay, I've updated the game finished messages for clarity.  Thanks.
