### ISSUE TITLE
rules / doc mismatch in KingCell

### ISSUE THREAD

**Issue by bmillwood** [shlomif/PySolFC#377]
KingCell [docs](https://github.com/shlomif/PySolFC/blob/master/html-src/rules/kingcell.html) say "Like FreeCell, but only Kings can be played on empty spaces."

However, it seems like FreeCell demands sequences have alternating colours, but KingCell doesn't (any descending sequence is fine). The behaviour matches another KingCell I found online (though another one did something else instead :shrug: ), so I guess this is a documentation bug.

(I think there are more discrepancies like this, e.g. not mentioning changed rules on whether you can move arbitrary sequences or not, but I unfortunately don't remember any other examples. Can go looking if you'd like, especially if it's easier to make these changes in a batch.)

**Comment by joeraz** [comment]
Noted.  Will update.

Information on any other issues you notice would be appreciated - the docs could definitely use some review and editing in general.

**Comment by bmillwood** [comment]
I think BigCell seems to allow arbitrary stacks to be moved, and doesn't mention this in the rules. (In this case I don't know whether the rules or the doc are correct.)

**Comment by joeraz** [comment]
My personal opinion in situations like that - we should assume the playable rules are correct, unless there's evidence to suggest otherwise.

**Comment by joeraz** [comment]
So I've updated the documentation to correct these rule errors (and made a few other corrections I identified).  Let me know if you find anything else, thanks!
