### ISSUE TITLE
samegame should avoid autodrop

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#386]
With autodrop active, samegame runs instantly to completion.
And when selecting the cancel-button after that, the game enters a  loop
that cannot be stopped, except by closing the program.

Btw, it looks like all changes to options are only written to file
at a 'normal' program-exit, and are lost on such an abort.

**Comment by joeraz** [comment]
Noted, will disable autodrop for Samegame.

**Comment by joeraz** [comment]
Disabled autodrop for Samegame for the next release.  That should fix this.
