### ISSUE TITLE
Ganjifa cardset types - failed to recognize empty spot indicators in custom cardset.

### ISSUE THREAD

**Issue by Alucard648** [shlomif/PySolFC#411]
In this screenshot, foundation empty spots use default suit icon, not custom provided one (bottom##.png).
![Безымянный](https://github.com/user-attachments/assets/a018398c-4009-4a28-b2c3-b1fb41d182a5)

Here is the custom cardset.
[cardset-master.zip](https://github.com/user-attachments/files/17639585/cardset-master.zip)

Double-checked file names, should work fine. If error was on maker`s side, tell me.

**Comment by joeraz** [comment]
The cardset-specific bottoms will only be used if PySol is not able to generate the standard bottoms, or the cardset-specific bottoms are enabled in your options.cfg file.  In the options.cfg file, set the value of use_cardset_bottoms to true.

**Comment by Alucard648** [comment]
I have yet to find that config file.

**Comment by joeraz** [comment]
It's in your user application data folder.

On Windows, this would be at C:\Users\[Your User Name]\AppData\Roaming\PySolFC

On Linux (Debian), this location can vary.  For a flatpak install, try /home/[User Name]/.var/app/io.sourceforge.pysolfc.PySolFC/.PySolFC, or just /home/[User Name]/.PySolFC for other installs.

**Comment by Alucard648** [comment]
Thanks for help. After fixup, bottoms loaded succefully.
[cardset-master.zip](https://github.com/user-attachments/files/17647118/cardset-master.zip)

**Comment by joeraz** [comment]
Great!
