### ISSUE TITLE
Arachnida allows to get cards back from foundations

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#414]
Arachnida is a game from the spider-family, so you can only move a complete set K-A to the foundations.
Accidentially  getting a single card back will make a game unwinnable.
The location the foundation is just  adjacent to the top row of the tableau,
so it is easy to make such a mistake, see savegame:
[Arachnida-27380765364592631808_stuck+1.zip](https://github.com/user-attachments/files/17691487/Arachnida-27380765364592631808_stuck%2B1.zip)

I suggest to move the location of the foundations, 
eg. to the lower-right corner. 

That savegame also has several bookmarked positions
with false stuck-alerts.
And the logic for moving cards with rightclick seems really stupid with this game,
eg. missing the opporunity to move an ace to  an almost complete stack...

**Comment by joeraz** [comment]
Instead of moving the foundations, it would probably be better to just disallow moving cards down from the foundation on this game.  Much easier to implement, and much more failure-proof.

**Comment by joeraz** [comment]
Also, the right-click shortcut is not very smart by design.  It's supposed to be a shortcut rather than a hint, so no logic to determine the best possible move is used there.

**Comment by joeraz** [comment]
I updated Arachnida so cards can't be moved off the foundation.
