### ISSUE TITLE
switching demo-logos doesn't always work

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#415]
the checkmark in the options-menu gets updated, 
but the selected logo doesn't show up

**Comment by joeraz** [comment]
Could you provide a little more detail as to what's happening?  Are you still seeing the old demo logo?  Are you changing it to/from "None"?  Any other details?

**Comment by joeraz** [comment]
I tested switching the demo logo, and was not able to see any issues.

**Comment by hajo4** [comment]
> Could you provide a little more detail as to what's happening?

On Win10, start pysol 3.1, the demo-logo is set to Arcade.
Select any game (say spider), start demo -> demo-logo looks like big bitmap-graphics - ok so far.

Goto Options/OtherGraphics/Demo-logo, (demo stops) select Classic, 
Continue demo - demo-logo is still Arcade (but maybe in a differenet color)
Goto Options/OtherGraphics/Demo-logo, - demo stops, checkmark is at classic - but the logo used is still Arcade.

Select Gold, continue demo - thin golden demo-logo is shown  --> sometimes switching works

Now goto Options/OtherGraphics/Demo-logo, (demo stops) select Classic,, 
continue demo - still using gold logo instead of Classic.

Quit game, Restart, check setting: checkmark for demo-logo is at Gold
Select Classic, start demo -  blue demo-logo shows up --> sometimes switching works

Select Komika, continue demo -  still the blue demo-logo is used

Maybe seitching only works the first time after the game was started ?

**Comment by joeraz** [comment]
I did a little looking based on that.  Based on what I see, it looks like the logo does not change properly if you try to change it while the demo is actively running.  If you stop the demo before changing it, it changes without issue.

The relationship between pause/demo and refresh (which is done when changing the demo logo, among other things), has always been a bit finicky.  I'd have to take a closer look.

**Comment by joeraz** [comment]
I think this update should fix that.
