### ISSUE TITLE
Documentation: key bindings: Ctrl+r not in "Undocumented key bindings" list

### ISSUE THREAD

**Issue by CharlesMAtkinson** [shlomif/PySolFC#416]
https://pysolfc.sourceforge.io/doc/howtoplay.html has a list of "Undocumented key bindings".  Ctrl+r is not in it.  

Ctrl+r selects the game (by cycling through a list of 1000+ games?) on my version of 3.1.0 running in an unprivileged user's venv on Debian Bookworm.

**Comment by joeraz** [comment]
The Ctrl+R key is the shortcut for File/Select random game/All games.  This randomly selects a game and starts it.

It is not listed in the "Undocumented key bindings" as it is documented as a shortcut for a menu item.  That section only lists key bindings that are not shown in the menus.
