### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by saltycraig** [shlomif/PySolFC#43]
I'd like to add function/class/method documentation using ReStructed Text (RST), which is usable by Sphinx and other tools. This would make it easier to view documentation in one place and to quickly see what a function/method is returning and does, as I've noticed quite a few functions being rather opaque when trying to debug my local copy.

Reference and example file:
http://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html 
http://docutils.sourceforge.net/docutils/statemachine.py

**Comment by shlomif** [comment]
@saltycraig : hi! Thanks for your enthusiasm. I tend to be more skeptical of documenting code internals (given what I wrote in
