### ISSUE TITLE
OS X/Windows OSError when pysol.py run directly

### ISSUE THREAD

**Issue by saltycraig** [shlomif/PySolFC#44]
Traceback:
```
Traceback (most recent call last):
  File "pysol.py", line 32, in <module>
    sys.exit(main(sys.argv))
  File "/Users/craig/Envs/py2-pysolfc/pysollib/main.py", line 369, in main
    r = pysol_init(app, args)
  File "/Users/craig/Envs/py2-pysolfc/pysollib/main.py", line 183, in pysol_init
    app.dataloader = DataLoader(args[0], f)
  File "/Users/craig/Envs/py2-pysolfc/pysollib/util.py", line 146, in __init__
    str(filenames))
OSError: pysol.py: DataLoader could not find ('html/license.html',)
```

Replicated master branch into empty python 2.7.13 environment like such:
```
$ git clone ...
$ cd PySolFC
$ python2 -m virtualenv .
$ source bin/activate
$ pip install six
$ python pysol.py
```

Happens on the Windows 7 computer I tried it on too. I believe the issue is the naming of the directory, I've tested a change and got it to run. I will submit a pull request for it when I make sure it is not affecting anything else.

**Comment by shlomif** [comment]
On Thu, 24 Aug 2017 19:29:14 +0000 (UTC)
Craig MacEachern <notifications@github.com> wrote:

> Traceback:
> ```
> Traceback (most recent call last):
>   File "pysol.py", line 32, in <module>
>     sys.exit(main(sys.argv))
>   File "/Users/craig/Envs/py2-pysolfc/pysollib/main.py", line 369, in main
>     r = pysol_init(app, args)
>   File "/Users/craig/Envs/py2-pysolfc/pysollib/main.py", line 183, in
> pysol_init app.dataloader = DataLoader(args[0], f)
>   File "/Users/craig/Envs/py2-pysolfc/pysollib/util.py", line 146, in __init__
>     str(filenames))
> OSError: pysol.py: DataLoader could not find ('html/license.html',)
> ```
> 
> Replicated master branch into empty python 2.7.13 environment like such:
> ```
> $ git clone ...
> $ cd PySolFC
> $ python2 -m virtualenv .
> $ source bin/activate
> $ pip install six
> $ python pysol.py
> ```
> 
> Happens on the Windows 7 computer I tried it on too. I believe the issue is
> the naming of the directory, I've tested a change and got it to run. I will
> submit a pull request for it when I make sure it is not affecting anything
> else.
> 
> 

Hi Craig!

Thanks for the report, but it seems like you have not followed the instructions
in the README ( https://github.com/shlomif/PySolFC ) about doing "ln -s html-src
html".

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Favourite FOSS - http://www.shlomifish.org/open-source/favourite/

Cast your bread upon the waters, for after many days you will find it again.
    — Ecclesiastes 1:11

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by saltycraig** [comment]
Very sorry, got ahead of myself :P At least it got my looking into the code base a bit more! Closing.
