### ISSUE TITLE
Cannot build in debian

### ISSUE THREAD

**Issue by Ygarr** [shlomif/PySolFC#49]
The Step 2 - build PySol. is not suitable for Debian: no gmake nad urpmi.
The default Card-sets PATH installed form Debian repostiories is - /usr/share/games/pysolfc

**Comment by shlomif** [comment]
Hi Ygarr!

On Wed, 11 Oct 2017 18:13:19 -0700
Ygarr <notifications@github.com> wrote:

> The Step 2 - build PySol. is not suitable for Debian.
> 

1. What did you try?

2. What didn't work?

3. Can you paste a shell session or scReenshot it?

4. Please be more coherent.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Freecell Solver - http://fc-solve.shlomifish.org/

Only perl and Chuck Norris can parse Perl.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Closing due to lack of response.
