### ISSUE TITLE
If the black-hole-solver cannot be found in the path, the error is "Iterations count exceeded"

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#51]
If the black-hole-solver cannot be found in the path, the error is "Iterations count exceeded", instead of some thing more accurate and helpful. This should be fixed with a test.

To reproduce:

1. Select a "Black Hole" game.

2. Make sure black-hole-solver is not in the path.

3. Invoke Assist -> Solver and press start.

**Comment by Programator2** [comment]
Working on it.

**Comment by shlomif** [comment]
Fixed by Pull-Req #55 - thanks!
