### ISSUE TITLE
shishensho crashes

### ISSUE THREAD

**Issue by lufebe16** [shlomif/PySolFC#54]
current master: shishensho.py, line 352:

cl.reverse()
AttributeError: 'xrange' object has no attribute 'reverse'

change to:
cl = reversed(cl)

**Comment by shlomif** [comment]
On Sat, 24 Feb 2018 10:31:54 +0000 (UTC)
lufebe16 <notifications@github.com> wrote:

> current master: shishensho.py, line 352:
> 
> cl.reverse()
> AttributeError: 'xrange' object has no attribute 'reverse'
> 
> change to:
> cl = reversed(cl)
> 
> 

thanks for the report - i will take a look.

Regards,

	Shlomi

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Original Riddles - http://www.shlomifish.org/puzzles/

The Angel of Death cannot keep up with Chuck Norris’s throughput of killing.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Fixed! Thanks.
