### ISSUE TITLE
Modernized icon set

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#6]
I think PySolFC looks to me a bit outdated, mainly because of the current icon set. I guess it could be refreshed. 

Of course, I don't mean that you have to code and create new graphics. :P It just would be good to look for some designer (maybe let's post this on various Linux forums?).

**Comment by shlomif** [comment]
This may be the case. Fixing it is not a high priority and I'm not sure where to find a designer.

**Comment by jan-kleks** [comment]
Actually, we might be able to deal with this issue without our own designers. There are a lot of CC-licensed free vector icons resources, for instance:

[Noun Project](https://thenounproject.com/)

**Comment by joeraz** [comment]
Looks like this one was closed by mistake.

Regardless, in more recent versions, I added a new icon set based on https://remixicon.com/ and restored some dummied out logic allowing the user to change the icon set while the app is running, so I think this has been resolved for real.
