### ISSUE TITLE
make dist fails on current master

### ISSUE THREAD

**Issue by lufebe16** [shlomif/PySolFC#61]
Cannot make a dist on current master:

lb@lb7520 ~/PySolFCwork $ make dist
PYTHONPATH=`pwd` ./scripts/all_games.py > docs/all_games.html
Traceback (most recent call last):
  File "./scripts/all_games.py", line 257, in <module>
    create_html(sort_by)
  File "./scripts/all_games.py", line 176, in create_html
    all_games(sort_by)
  File "./scripts/all_games.py", line 142, in all_games
    rules_fn = getGameRulesFilename(gi.name)
  File "./scripts/all_games.py", line 36, in getGameRulesFilename
    return latin1_normalize(n) + '.html'
NameError: global name 'latin1_normalize' is not defined
make: *** [Makefile:26: all_games_html] Fehler 1

When I check with flake8:

lb@lb7520 ~/PySolFCwork $ flake8 scripts/all_games.py
scripts/all_games.py:14:1: F401 'pysollib.games.mahjongg' imported but unused
scripts/all_games.py:18:1: F401 'pysollib.mfxutil.latin1_to_ascii' imported but$
scripts/all_games.py:36:12: F821 undefined name 'latin1_normalize'

Needs manual testing because skipped in tests/style/py-flake8.t. But -
is it allowed to ask why such a skipping list exists ?

**Comment by shlomif** [comment]
Hi!

This is now fixed in commit 0e105a9463a54e83cc6226e3146218bd976d90e2 in master - with a travis-CI test. Thanks! We need the skipping list because flake8 is unhappy with some files due to "unused" imports and stuff like that. If you can figure out a way to test them with some exceptions to the rules, then send me a pull req.

**Comment by lufebe16** [comment]
On Mon, 19 Mar 2018 10:47:59 +0000 (UTC)
Shlomi Fish <notifications@github.com> wrote:

Hi,

An inline comment like this works (e.g):

import re  # noqa
or
import re  # noqa: F401

(exactly one <space> after #)
see: https://github.com/PyCQA/flake8, Readme.rst

> Hi!
> 
> This is now fixed in commit 0e105a9463a54e83cc6226e3146218bd976d90e2 in master - with a travis-CI test. Thanks! We need the skipping list because flake8 is unhappy with some files due to "unused" imports and stuff like that. If you can figure out a way to test them with some exceptions to the rules, then send me a pull req.
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/shlomif/PySolFC/issues/61#issuecomment-374171261


--

**Comment by shlomif** [comment]
On Mon, 19 Mar 2018 16:51:13 +0000 (UTC)
lufebe16 <notifications@github.com> wrote:

> On Mon, 19 Mar 2018 10:47:59 +0000 (UTC)
> Shlomi Fish <notifications@github.com> wrote:
> 
> Hi,
> 
> An inline comment like this works (e.g):
> 
> import re  # noqa
> or
> import re  # noqa: F401
> 
> (exactly one <space> after #)
> see: https://github.com/PyCQA/flake8, Readme.rst
> 

thanks! i'll try that.

> > Hi!
> > 
> > This is now fixed in commit 0e105a9463a54e83cc6226e3146218bd976d90e2 in
> > master - with a travis-CI test. Thanks! We need the skipping list because
> > flake8 is unhappy with some files due to "unused" imports and stuff like
> > that. If you can figure out a way to test them with some exceptions to the
> > rules, then send me a pull req.
> > 
> > 
> > 
> > -- 
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/shlomif/PySolFC/issues/61#issuecomment-374171261  
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)

What do you mean by “WDYM”?
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
