### ISSUE TITLE
pysol-sound-server not ported to python3

### ISSUE THREAD

**Issue by rezso** [shlomif/PySolFC#63]
pysolfc now ported to python3, and requires python3 modules on install.
But the required pysol-sound-server is python2-only.

**Comment by shlomif** [comment]
On Mon, 19 Mar 2018 15:22:11 +0000 (UTC)
rezso <notifications@github.com> wrote:

> pysolfc now ported to python3, and requires python3 modules on install.
> But the required pysol-sound-server is python2-only.

right. Porting it will be nice.

> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
NSA Factoids - http://www.shlomifish.org/humour/bits/facts/NSA/

Objective Visual Turbo Global jIronOpenPerl++.NET™ Enterprise Edition♭
Professional Home Premium Ultimate 64-bit Single-user.
    — based on a Freenode #perl conversation ( http://is.gd/cCUBY2 )

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@rezso and all: please see https://github.com/shlomif/pysol-sound-server

**Comment by rezso** [comment]
I tried this, but not enough, because of C API changes in python:

` pysol
Traceback (most recent call last):
File "/usr/lib/python3.5/site-packages/pysollib/pysolaudio.py", line 183, in startServer
import pysolsoundserver
ImportError: /usr/lib/python3.5/site-packages/pysolsoundserver.cpython-35m-i386-linux-gnu.so: undefined symbol: Py_InitModule4`

**Comment by rezso** [comment]
With this commit it works with python3: https://github.com/shlomif/pysol-sound-server/commit/3b3315884f73d49a48546c91e302cf57800e321c

**Comment by Neelix57** [comment]
Hi. I compile pysol-sound-server successfully, but got no sound in PySolFC.

**Comment by Neelix57** [comment]
Tried PySolFC without installation. Here the sound works.
