### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#65]
I can see there are more contributors now. Do you think that creating some kind of roadmap might be useful?

EDIT: You could possible use these tools for this: https://help.github.com/articles/about-project-boards/

**Comment by shlomif** [comment]
Hi Jan!

On Tue, 20 Mar 2018 23:10:21 +0000 (UTC)
Jan Kleks <notifications@github.com> wrote:

> I can see there are more contributors now. Do you think that creating some
> kind of roadmap might be useful?
> 

I read the opening of https://en.wikipedia.org/wiki/Technology_roadmap and it
is full of buzzwords. Anyway, this being a voluntary project which is mature
and usable, people can just contribute as they see fit and work on open issues.
So I don't see the point of a roadmap.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Can-I-SCO-Now/ - “Can I SCO Now?”

Do not meddle in the affairs of Dragons, for you are crunchy and taste good
with ketchup.                                       — Unknown source.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Closing this issue to avoid clutter.
