### ISSUE TITLE
Better integration with operating system theme

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#74]
I gotta say that I'm a great fan of how well, for instance, internet browsers integrate with various operating systems when it comes to the look & feel (there are exceptions, but I hope you understand the concept).

PySol FC has got a few themes (some look really outdated), what if it could just nicely adapt to colors, textures, and the current system theme in general.

**Comment by shlomif** [comment]
This will require creating a https://en.wikipedia.org/wiki/WxPython backend or perhaps one based on https://en.wikipedia.org/wiki/PyQt or https://en.wikipedia.org/wiki/PySide - they will all require a lot of work. As a result, I am closing this issue to avoid clutter.

**Comment by daemonspudguy** [comment]
There is a project called gttk, which lets you not have to rework the entire UI but still offer far better integration, and is specifically made for pythontk.

**Comment by shlomif** [comment]
On Mon, 14 Jun 2021 13:04:59 -0700
daemonspudguy ***@***.***> wrote:

> There is a project called gttk, which lets you not have to rework the entire
> UI but still offer far better integration, and is specifically made for
> pythontk.
> 

Thanks for the tip!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/ways_to_do_it.html

He has a high degree of idealism, a high degree of stubbornness, and an even
higher degree of inability to distiniguish between the two.
    — https://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .
