### ISSUE TITLE
Provide a link to a ready made Android package

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#75]
@lufebe16 : can we provide a link to a ready made Android package? See https://www.reddit.com/r/opensourcegames/comments/8cnko4/new_stable_release_of_pysolfc_an_opensource/dxghc62/ . Perhaps get Travis-CI to generate it? Is it available on the play store?

**Comment by lufebe16** [comment]
On Mon, 16 Apr 2018 15:53:18 +0000 (UTC)
Shlomi Fish <notifications@github.com> wrote:

There is a version based on the bitbucket repo (version 0.8), based actually on version 2.0 from sourceforge. Published with fdroid (https://f-droid.org/packages/).

A merge	request	for for	a new version is pending since more than a week at the fdroiddata repo. It will publish version 2.1.4. once it get accepted.

With play store I do not have any experience.

The build is quite a heavy load and should preferably not be run with the Travis-CI on each commit. As the scripts would be published in the repo I also see a problem of keeping the secrets, when building a release-apk. (Also to consider: the size of the apk file is ca. 15M.)

> @lufebe16 : can we provide a link to a ready made Android package? See https://www.reddit.com/r/opensourcegames/comments/8cnko4/new_stable_release_of_pysolfc_an_opensource/dxghc62/ . Perhaps get Travis-CI to generate it? Is it available on the play store?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/shlomif/PySolFC/issues/75


--

**Comment by shlomif** [comment]
On Wed, 18 Apr 2018 09:40:36 +0000 (UTC)
lufebe16 <notifications@github.com> wrote:

> On Mon, 16 Apr 2018 15:53:18 +0000 (UTC)
> Shlomi Fish <notifications@github.com> wrote:
> 
> There is a version based on the bitbucket repo (version 0.8), based actually
> on version 2.0 from sourceforge. Published with fdroid
> (https://f-droid.org/packages/).
> 
> A merge	request	for for	a new version is pending since
> more than a week at the fdroiddata repo. It will publish version 2.1.4. once
> it get accepted.
> 
> With play store I do not have any experience.
> 
> The build is quite a heavy load and should preferably not be run with the
> Travis-CI on each commit. As the scripts would be published in the repo I
> also see a problem of keeping the secrets, when building a release-apk. (Also
> to consider: the size of the apk file is ca. 15M.)
> 

thanks for the info! Let's hope it gets updated quickly.

> > @lufebe16 : can we provide a link to a ready made Android package? See
> > https://www.reddit.com/r/opensourcegames/comments/8cnko4/new_stable_release_of_pysolfc_an_opensource/dxghc62/ .
> > Perhaps get Travis-CI to generate it? Is it available on the play store?
> > 
> > -- 
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/shlomif/PySolFC/issues/75  
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/

By the time it takes Windows Update to download a 22 MB update without
installing it, Mageia Linux’s urpmi was already able to download and install a
game whose package is 900 MB (and there was still a lot of time to spare).
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by lufebe16** [comment]
On Wed, 18 Apr 2018 03:05:18 -0700
Shlomi Fish <notifications@github.com> wrote:

> On Wed, 18 Apr 2018 09:40:36 +0000 (UTC)
> lufebe16 <notifications@github.com> wrote:
> 
> > On Mon, 16 Apr 2018 15:53:18 +0000 (UTC)
> > Shlomi Fish <notifications@github.com> wrote:
> > 
> > There is a version based on the bitbucket repo (version 0.8), based actually
> > on version 2.0 from sourceforge. Published with fdroid
> > (https://f-droid.org/packages/).
> > 
> > A merge	request	for for	a new version is pending since
> > more than a week at the fdroiddata repo. It will publish version 2.1.4. once
> > it get accepted.
> > 
> > With play store I do not have any experience.
> > 
> > The build is quite a heavy load and should preferably not be run with the
> > Travis-CI on each commit. As the scripts would be published in the repo I
> > also see a problem of keeping the secrets, when building a release-apk. (Also
> > to consider: the size of the apk file is ca. 15M.)
> > 
> 
> thanks for the info! Let's hope it gets updated quickly.

PySolFC, version 2.2.0 is now available on f-droid: https://f-droid.org/packages/

> 
> > > @lufebe16 : can we provide a link to a ready made Android package? See
> > > https://www.reddit.com/r/opensourcegames/comments/8cnko4/new_stable_release_of_pysolfc_an_opensource/dxghc62/ .
> > > Perhaps get Travis-CI to generate it? Is it available on the play store?
> > > 
> > > -- 
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/shlomif/PySolFC/issues/75  
> > 
> > 
> 
> 
> 
> -- 
> -----------------------------------------------------------------
> Shlomi Fish       http://www.shlomifish.org/
> Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/
> 
> By the time it takes Windows Update to download a 22 MB update without
> installing it, Mageia Linux’s urpmi was already able to download and install a
> game whose package is 900 MB (and there was still a lot of time to spare).
>     — http://www.shlomifish.org/humour/bits/facts/Windows-Update/
> 
> Please reply to list if it's a mailing list post - http://shlom.in/reply .
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/shlomif/PySolFC/issues/75#issuecomment-382335227

--

**Comment by shlomif** [comment]
On Mon, 30 Apr 2018 02:10:26 -0700
lufebe16 <notifications@github.com> wrote:

> On Wed, 18 Apr 2018 03:05:18 -0700
> Shlomi Fish <notifications@github.com> wrote:
> 
> > On Wed, 18 Apr 2018 09:40:36 +0000 (UTC)
> > lufebe16 <notifications@github.com> wrote:
> >   
> > > On Mon, 16 Apr 2018 15:53:18 +0000 (UTC)
> > > Shlomi Fish <notifications@github.com> wrote:
> > > 
> > > There is a version based on the bitbucket repo (version 0.8), based
> > > actually on version 2.0 from sourceforge. Published with fdroid
> > > (https://f-droid.org/packages/).
> > > 
> > > A merge	request	for for	a new version is pending
> > > since more than a week at the fdroiddata repo. It will publish version
> > > 2.1.4. once it get accepted.
> > > 
> > > With play store I do not have any experience.
> > > 
> > > The build is quite a heavy load and should preferably not be run with the
> > > Travis-CI on each commit. As the scripts would be published in the repo I
> > > also see a problem of keeping the secrets, when building a release-apk.
> > > (Also to consider: the size of the apk file is ca. 15M.)
> > >   
> > 
> > thanks for the info! Let's hope it gets updated quickly.  
> 
> PySolFC, version 2.2.0 is now available on f-droid:
> https://f-droid.org/packages/
> 

Wonderful, thanks! Do you think this bug can be closed now?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Favourite FOSS - http://www.shlomifish.org/open-source/favourite/

If the mountain will not come to Muhammad, then Muhammad will go to the
mountain. If the mountain will not come to Chuck Norris, then the mountain
will suffer Norris’s wrath for not complying with his whims.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Alucard648** [comment]
Let`s hope that the app will be available on GooglePlay.

**Comment by shlomif** [comment]
@lufebe16 : can we close this bug?

**Comment by lufebe16** [comment]
Yes.

**Comment by shlomif** [comment]
@lufebe16 : thanks! Closing.
