### ISSUE TITLE
Degrade gracefully if no sound card

### ISSUE THREAD

**Issue by PhilHudson** [shlomif/PySolFC#78]
I have PySolFC installed on Gnu/Linux host A. I'm sitting at Gnu/Linux host B. I can SSH into host A and run most X11 apps there using my local X server on host B. I have Emacs running in this way at the same time.

(Remember that X reverses the usual client-server model: your local display is the server, the remote app is the client).

If I try to run PySolFC on host A, the splash/progress-bar frame appears on host B's display as expected, the progress bar gets about halfway, then PySolFC aborts, with a stack trace ending with:

    pygame.error: No available audio device

I don't want or need sound. I just want my Forty Thieves. Please fix it for me when you have a chance.

I know little Python and no Python3 or I'd try myself. To be clear, I'm not asking for a build/install-time configuration option. I want smarter runtime exception handling, recovery and graceful degradation, please.

**Comment by shlomif** [comment]
Hi Phil,

sorry for the inconvenience.

On Wed, 25 Apr 2018 15:52:31 -0700
Phil Hudson <notifications@github.com> wrote:

> I have PySolFC installed on Gnu/Linux host A. I'm sitting at Gnu/Linux host
> B. I can SSH into host A and run most X11 apps there using my local X server
> on host B. I have Emacs running in this way at the same time.
> 
> (Remember that X reverses the usual client-server model: your local display
> is the server, the remote app is the client).
> 
> If I try to run PySolFC on host A, the splash/progress-bar frame appears on
> host B's display as expected, the progress bar gets about halfway, then
> PySolFC aborts, with a stack trace ending with:
> 
>     pygame.error: No available audio device
> 

Can you give the full stack trace? That will help a lot.

> I don't want or need sound. I just want my Forty Thieves. Please fix it for
> me when you have a chance.
> 
> I know little Python and no Python3 or I'd try myself. To be clear, I'm not
> asking for a build/install-time configuration option. I want smarter runtime
> exception handling, recovery and graceful degradation, please.
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/shlomif/Freenode-programming-channel-FAQ

Inigo Montoya: You seem a decent fellow. I hate to kill you.
The Man in Black: You seem a decent fellow. I hate to die.
    — http://en.wikiquote.org/wiki/The_Princess_Bride_%28film%29

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by PhilHudson** [comment]
Of course, my bad for not doing it first time.

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/usr/games/pysolfc", line 32, in <module>
    sys.exit(main(sys.argv))
  File "/usr/share/games/pysolfc/pysollib/main.py", line 359, in main
    r = pysol_init(app, args)
  File "/usr/share/games/pysolfc/pysollib/main.py", line 314, in pysol_init
    app.audio.connectServer(app)
  File "/usr/share/games/pysolfc/pysollib/pysolaudio.py", line 445, in connectServer
    self.mixer.init()
pygame.error: No available audio device

**Comment by shlomif** [comment]
On Wed, 25 Apr 2018 18:42:24 -0700
Phil Hudson <notifications@github.com> wrote:

> Of course, my bad for not doing it first time.
> 

thanks! I'll look into it.

> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver
> returned error: No such file or directory ALSA lib
> confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib
> conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error:
> No such file or directory ALSA lib confmisc.c:1246:(snd_func_refer) error
> evaluating name ALSA lib conf.c:4528:(_snd_config_evaluate) function
> snd_func_refer returned error: No such file or directory ALSA lib
> conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default Traceback
> (most recent call last): File "/usr/games/pysolfc", line 32, in <module>
> sys.exit(main(sys.argv)) File "/usr/share/games/pysolfc/pysollib/main.py",
> line 359, in main r = pysol_init(app, args)
>   File "/usr/share/games/pysolfc/pysollib/main.py", line 314, in pysol_init
>     app.audio.connectServer(app)
>   File "/usr/share/games/pysolfc/pysollib/pysolaudio.py", line 445, in
> connectServer self.mixer.init()
> pygame.error: No available audio device
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/lecture/C-and-CPP/bad-elements/

<mst> I find it’s usually safe to assume that whatever shlomif’s doing, there
isn’t a good reason for it.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
On Wed, 25 Apr 2018 18:42:24 -0700
Phil Hudson <notifications@github.com> wrote:

> Of course, my bad for not doing it first time.
> 
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver
> returned error: No such file or directory ALSA lib
> confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib
> conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error:
> No such file or directory ALSA lib confmisc.c:1246:(snd_func_refer) error
> evaluating name ALSA lib conf.c:4528:(_snd_config_evaluate) function
> snd_func_refer returned error: No such file or directory ALSA lib
> conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default Traceback
> (most recent call last): File "/usr/games/pysolfc", line 32, in <module>
> sys.exit(main(sys.argv)) File "/usr/share/games/pysolfc/pysollib/main.py",
> line 359, in main r = pysol_init(app, args)
>   File "/usr/share/games/pysolfc/pysollib/main.py", line 314, in pysol_init
>     app.audio.connectServer(app)
>   File "/usr/share/games/pysolfc/pysollib/pysolaudio.py", line 445, in

Hi Phil!

Sorry, but that line is a comment in version 2.2.0, which is the latest stable
release. Can you try reproducing the problem with it as well? Seems like you
are using a system package.


> connectServer self.mixer.init()
> pygame.error: No available audio device
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Elems to Avoid - http://perl-begin.org/tutorials/bad-elements/

Aesop originally wanted to write his fable as “The Hare and Windows Update”
instead of “The Hare and the Tortoise” but could not figure out how the hare
will ever lose to Windows Update, even despite him not taking the race
seriously.
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by PhilHudson** [comment]
Uninstalled the distro package, git clone'd from Github, 'make test'
fails, even after both 'pip install random2' and 'sudo pip install
random2'. Let's forget it. Please close the issue. I'll wait for
Debian testing to catch up. Sorry for the noise.

On 26 April 2018 at 08:54, Shlomi Fish <notifications@github.com> wrote:
> On Wed, 25 Apr 2018 18:42:24 -0700
> Phil Hudson <notifications@github.com> wrote:
>
>> Of course, my bad for not doing it first time.
>>
>> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
>> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver
>> returned error: No such file or directory ALSA lib
>> confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib
>> conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned
>> error:
>> No such file or directory ALSA lib confmisc.c:1246:(snd_func_refer) error
>> evaluating name ALSA lib conf.c:4528:(_snd_config_evaluate) function
>> snd_func_refer returned error: No such file or directory ALSA lib
>> conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
>> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default Traceback
>> (most recent call last): File "/usr/games/pysolfc", line 32, in <module>
>> sys.exit(main(sys.argv)) File "/usr/share/games/pysolfc/pysollib/main.py",
>> line 359, in main r = pysol_init(app, args)
>> File "/usr/share/games/pysolfc/pysollib/main.py", line 314, in pysol_init
>> app.audio.connectServer(app)
>> File "/usr/share/games/pysolfc/pysollib/pysolaudio.py", line 445, in
>
> Hi Phil!
>
> Sorry, but that line is a comment in version 2.2.0, which is the latest
> stable
> release. Can you try reproducing the problem with it as well? Seems like you
> are using a system package.
>
>
>> connectServer self.mixer.init()
>> pygame.error: No available audio device
>>
>>
>
>
>
> --
> -----------------------------------------------------------------
> Shlomi Fish http://www.shlomifish.org/
> Perl Elems to Avoid - http://perl-begin.org/tutorials/bad-elements/
>
> Aesop originally wanted to write his fable as “The Hare and Windows Update”
> instead of “The Hare and the Tortoise” but could not figure out how the hare
> will ever lose to Windows Update, even despite him not taking the race
> seriously.
> — http://www.shlomifish.org/humour/bits/facts/Windows-Update/
>
>
> Please reply to list if it's a mailing list post - http://shlom.in/reply .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Phil Hudson                  http://hudson-it.ddns.net
Pretty Good Privacy (PGP) ID: 0x887DCA63

**Comment by shlomif** [comment]
@PhilHudson : OK, thanks - will close. Note that make test has some other deps - see the .travis.yml file.
