### ISSUE TITLE
[SOLVED]unable to install pysolfc 2.2.0 on xfce4

### ISSUE THREAD

**Issue by uygwfd254** [shlomif/PySolFC#81]
i have download the tar file from sourceforge
https://sourceforge.net/projects/pysolfc/files/PySolFC/PySolFC-2.2.0/PySolFC-2.2.0.tar.xz/

then i unzip it by this command
```
cd ~/Downloads
tar -xf PySolFC-2.2.0.tar.xz
```

after that i follow the first step of the installation:
```
$ sudo apt-get install -y ack-grep cpanminus libperl-dev make perl python-glade2 python-gnome2 python-gnome2-dev python-gtk2 python-setuptools python-tk
$ sudo apt-get update
```
then i move on the second step. since i already unzip the file, i move to:

~~$ git clone https://github.com/shlomif/PySolFC.git~~
~~$ cd PySolFC~~
```
$ cd ~/Downloads/PySolFC-2.2.0
$ sudo urpmi tkinter
```

attempt to execute "sudo urpmi tkinter" resulted:
**sudo: urpmi: command not found**

i assumed that this command worked on megeia but not debian/ubuntu

if that is the case, can you tell me the step to complete the installation on my xfce4?

**Comment by uygwfd254** [comment]
actually this issue is referred to:
https://github.com/shlomif/PySolFC/issues/49

**Comment by shlomif** [comment]
@uygwfd254 : I corrected the instructions now - please see the latest ones. Just ignore the urpmi commands.

**Comment by uygwfd254** [comment]
i found out that gmake doesn't exist in debian, only make command exist.

so i try to run ```make test```
i got an error that says ```scripts/gen_individual_importing_tests.py``` does not exist.

i go ahead and download the PySolFC from here, github.

then, i have follow your instruction again and i found an error

when i run:
```
make test
make rules
```

i get these errors: https://pastebin.com/s3b38DYz
------------------------------------------------------------------------------------------------------------------------------------
and when i run: ```python3 pysol.py```

i got:
```
y41@localhost:~/Downloads/PySolFC$ python3 pysol.py
Traceback (most recent call last):
  File "pysol.py", line 37, in <module>
    from pysollib.main import main  # noqa: E402
  File "/home/y41/Downloads/PySolFC/pysollib/main.py", line 35, in <module>
    from pysollib.app import Application
  File "/home/y41/Downloads/PySolFC/pysollib/app.py", line 43, in <module>
    from pysollib.images import Images, SubsampledImages
  File "/home/y41/Downloads/PySolFC/pysollib/images.py", line 36, in <module>
    from pysollib.pysoltk import loadImage, copyImage, createImage, \
  File "/home/y41/Downloads/PySolFC/pysollib/pysoltk.py", line 48, in <module>
    from pysollib.tile.menubar import *  # noqa: F401,F403
  File "/home/y41/Downloads/PySolFC/pysollib/tile/menubar.py", line 34, in <module>
    from .selectgame import SelectGameDialog, SelectGameDialogWithPreview
  File "/home/y41/Downloads/PySolFC/pysollib/tile/selectgame.py", line 28, in <module>
    from six.moves import UserList
ImportError: cannot import name 'UserList'
y41@localhost:~/Downloads/PySolFC$
```

**Comment by shlomif** [comment]
Hi,

On Tue, 08 May 2018 16:57:41 -0700
uygwfd254 <notifications@github.com> wrote:

> i found out that gmake doesn't exist in debian, only make command exist.
> 

that sucks - "make" is more ambiguous.

> so i try to run ```make test```
> i got an error that says ```scripts/gen_individual_importing_tests.py``` does
> not exist.
> 

i guess it was not included in the distribution.

> i go ahead and download the PySolFC from here, github.
> 
> then, i have follow your instruction again and i found an error
> 
> when i run:
> ```
> make test
> make rules
> ```
> 
> i get these errors: https://pastebin.com/s3b38DYz
>

what is present above them?
 ------------------------------------------------------------------------------------------------------------------------------------
> and when i run: ```python3 pysol.py```
> 
> i got:
> ```
> y41@localhost:~/Downloads/PySolFC$ python3 pysol.py
> Traceback (most recent call last):
>   File "pysol.py", line 37, in <module>
>     from pysollib.main import main  # noqa: E402
>   File "/home/y41/Downloads/PySolFC/pysollib/main.py", line 35, in <module>
>     from pysollib.app import Application
>   File "/home/y41/Downloads/PySolFC/pysollib/app.py", line 43, in <module>
>     from pysollib.images import Images, SubsampledImages
>   File "/home/y41/Downloads/PySolFC/pysollib/images.py", line 36, in <module>
>     from pysollib.pysoltk import loadImage, copyImage, createImage, \
>   File "/home/y41/Downloads/PySolFC/pysollib/pysoltk.py", line 48, in <module>
>     from pysollib.tile.menubar import *  # noqa: F401,F403
>   File "/home/y41/Downloads/PySolFC/pysollib/tile/menubar.py", line 34, in
> <module> from .selectgame import SelectGameDialog, SelectGameDialogWithPreview
>   File "/home/y41/Downloads/PySolFC/pysollib/tile/selectgame.py", line 28, in
> <module> from six.moves import UserList
> ImportError: cannot import name 'UserList'
> y41@localhost:~/Downloads/PySolFC$
> ```
> 

perhaps your version of six.py is too old?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Networking Clients - http://shlom.in/net-clients

“Talk Like a Pirate Day” is the only day of the year when Chuck Norris only
talks like a pirate, and does not actually act like one.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hairspring** [comment]
Make in Debian _is_ gmake (GNU make).  Has been for at least 10 years.  If you want gmake, just add a symbolic link in /usr/bin.

**Comment by uygwfd254** [comment]
thanks for the info, hairspring.

as it turns out, i need to upgrade and download things:
- six 1.11.0
- random2 1.1.0
- setuptools 39.1.0

once i install those, i was able to run ```python pysol.py``` and download the cardset.
i was able to play  (づ Ꮂ )づ. https://imgur.com/a/p894Fzh

thanks for your help, **shlomif**
