### ISSUE TITLE
Music missing

### ISSUE THREAD

**Issue by THEtomaso** [shlomif/PySolFC#82]
So, why have you removed the music in these latest releases of PySolFC?
I've tried re-adding it manually, but it won't play.

**Comment by shlomif** [comment]
Hi @THEtomaso ! Thanks for the report. Removing the music was not intentional. Can you provide any details regarding your operating system/etc.? Do sound effects work?

**Comment by shlomif** [comment]
Note that when I put the mod files in http://www.shlomifish.org/Files/files/arcs/mods.7z under `~/.PySolFC/music`, the music plays fine.

**Comment by THEtomaso** [comment]
Thanks for your quick answer, shlomif.

My OS is Windows 8.1 Pro, x64.

Seems that the music files aren't even included in the Windows installer anymore.
With the latest PySolFC versions, there is no "music" folder in `C:\Program Files (x86)\PySol Fan Club edition\data`.
There is one here: `C:\Users\*****\AppData\Roaming\PySolFC\music`, but it is empty.
And in the game, when I go to Options > Sound, there aren't even any music settings present!

I tried to place the mods and music files in the proper folders manually, but it didn't work.

Sound effects work just fine though.

**Comment by Programator2** [comment]
@THEtomaso 
Music won't work on packaged exe version of PySolFC, since it doesn't contain an audio client capable of playing music. However, when you run PySolFC with your Python installation together with `pygame` package, music should work.

@shlomif 
We can bundle `pygame` with the installer (that would increase its size by about 6 MB).
Other option would be to bundle it with PySol-Sound-Server, but I haven't tested it on Windows.

**Comment by THEtomaso** [comment]
Well, the music always came bundled with earlier versions (including v2.0), and those installers were only half the size of the new ones!
```
v2.0 installer =  8.52 MB
v2.2 installer = 15.90 MB
```

Where can I download that `pygame` file that you speak of?

**Comment by THEtomaso** [comment]
Thanks for the commit, Programator2.
Now, just remember to include the actual music tracks as well. :)

**Comment by jan-kleks** [comment]
Just my two cents, the PySolFC music and sound effects are really nice -- soothing and relaxing, perfect for the solitaire, and IMHO they aged well (unlike PySolFC's graphic elements and design).

An interesting piece of information, the music tracks were provided by a very talented demoscene composer Carl "Nightbeat" Larsson.

Because it's very easy to turn the music and sound effects off, in the case someone does not like them, I am for bundling them with PySolFC whenever possible.

**Comment by Programator2** [comment]
You're welcome :)
You can find the newest installer at [https://ci.appveyor.com/project/shlomif/pysolfc/build/artifacts](https://ci.appveyor.com/project/shlomif/pysolfc/build/artifacts)

We'll include the music tracks soon, I'll just have to find the original archive.
Concerning the installer size, version 2.0 used Python 2.5. Python was smaller back then. But that doesn't mean there's no room for optimization.

And btw, you can install `pygame` to your default Python installation using `pip install pygame`.

**Comment by THEtomaso** [comment]
> PySolFC music and sound effects are really nice -- soothing and relaxing, perfect for the solitaire, and IMHO they aged well

I agree.
It's very atmospheric. :)
Always reminded me of the soundtrack for the first Unreal game.
Some of the more laid-back tracks would make excellent additions to PySolFC's playlist:
`https://www.youtube.com/watch?v=9IISjIMpepo` (My favorite is @ 40:34)
..but of course, legal issues probably prevents these tracks from being used.

--

> You can find the newest installer at https://ci.appveyor.com/project/shlomif/pysolfc/build/artifacts

Great!
But I've re-installed v2.0 now.
I'll upgrade once you've released a new version, with everything included.
Keep up the good work! :)

**Comment by shlomif** [comment]
@Programator2 : I found this - https://sourceforge.net/projects/pysolfc/files/PySol-Music/PySol-Music-4.40/ - but it is only a .dmg . there is also http://legacy.redhat.com/pub/contrib/libc6/noarch/SRPMS/
and the archive from it is http://www.shlomifish.org/Files/files/arcs/pysol-music-4.40.tar.gz

**Comment by Programator2** [comment]
Thanks @shlomif !

Now the music is included with the installer.

**Comment by THEtomaso** [comment]
Great!
But two of those are completely new tunes to me.
What happened to the beautiful '**Bye_For_Now**' and '**Ranger_Song**' tracks??

**Comment by shlomif** [comment]
On Sun, 27 May 2018 12:05:33 -0700
THEtomaso <notifications@github.com> wrote:

> Great!
> But two of those are completely new tunes to me.
> What happened to the beautiful '**Bye_For_Now**' and '**Ranger_Song**'
> tracks??
> 

you can find them here - http://www.shlomifish.org/Iglu/shlomif/mods/ - no idea
what their licence is.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/shlomif/what-you-should-know-about-automated-testing

He says “One and one and one is three”.
Got to be good‐looking ’cause he’s so hard to see.
    — The Beatles, “Come Together”

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by THEtomaso** [comment]
> no idea what their licence is.

Here are the copyright files:
[tracks-copyrights.zip](https://github.com/shlomif/PySolFC/files/2042961/tracks-copyrights.zip)
They both say "**Distributed under the GNU GPL by permission of the author**", so they should still be safe to use.
Please include them in the installer.

**Comment by jan-kleks** [comment]
@THEtomaso Agreed.

**Comment by shlomif** [comment]
@THEtomaso : I added these tracks again. @Programator2 : can you spin a new PySolFC windows build with them, please?

**Comment by shlomif** [comment]
@Programator2 :I think I managed on my own now.

**Comment by shlomif** [comment]
@THEtomaso : please test the new installer on https://ci.appveyor.com/project/shlomif/pysolfc/build/1.0.207 .

**Comment by THEtomaso** [comment]
Yes, all tracks are present.
Well done!
Guess we have the "ultimate version" now, like jan-kleks described it. :)
You should bump the version @ SF with these changes.

**Comment by Programator2** [comment]
Good job @shlomif !

**Comment by THEtomaso** [comment]
If anyone is interested, you'll find more tracks by Nightbeat on these two pages:
https://modarchive.org/index.php?request=view_artist_modules&query=69007

**Comment by shlomif** [comment]
Closing now that PySol FC 2.4.0 is out with the music.

**Comment by THEtomaso** [comment]
> If anyone is interested, you'll find more tracks by Nightbeat on these two pages:
https://modarchive.org/index.php?request=view_artist_modules&query=69007

I think '**Approach**', '**Dreamstone**' and '**Wake**' would be really nice additions to PySolFC's music library.
What do you think? :)

**Comment by shlomif** [comment]
On Sat, 13 Apr 2019 09:41:01 -0700
THEtomaso <notifications@github.com> wrote:

> > If anyone is interested, you'll find more tracks by Nightbeat on these two
> > pages:  
> https://modarchive.org/index.php?request=view_artist_modules&query=69007
> 
> I think '**Approach**', '**Dreamstone**' and '**Wake**' would be really nice
> additions to PySolFC's music library. What do you think? :)
> 

What are their licences?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Graphics Apps - http://shlom.in/graphics

As it turns out, compiling a C program from more than 20 years ago is actually
a lot easier than getting a Rails app from last year to work.
    — https://passy.svbtle.com/building-vim-from-1993-today

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by THEtomaso** [comment]
> What are their licences?

`https://modarchive.org/index.php?terms-upload`
