### ISSUE TITLE
Add instruction to include your own cards set

### ISSUE THREAD

**Issue by cpcbegin** [shlomif/PySolFC#83]
I'm trying to add a Spanish cardset (48 cards) but I don't find how I must change config.txt in order to load the cards.
Always shows the error:
```
Error while loading cardset
'None type' object has no attribute 'filename'.
```
This is my cardset:
[cardset-spanish-gnu.tar.gz](https://github.com/shlomif/PySolFC/files/2020186/cardset-spanish-gnu.tar.gz)

**Comment by cpcbegin** [comment]
But I see card sets with more than 52 cards, is it possible add a set with only 48?

**Comment by shlomif** [comment]
On Sun, 20 May 2018 22:04:06 -0700
cpcbegin <notifications@github.com> wrote:

> But I see card sets with more than 52 cards, is it possible add a set with
> only 48?
> 

I don't know.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Self-Sufficiency/

You name it — COBOL does not have it.
    — http://is.gd/ClKAz5

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rexx790** [comment]
> After adding the print I get card image path /home/shlomif/.PySolFC/cardsets/cardset-spanish-gnu/13c.gif does not exist - note that I also had to add a COPYRIGHT file. Thanks for the report.

The above message is telling us that the "king of clubs" (13c.gif) is missing, so it would suggest that a set with 48 cards is not possible. If you want to use the set then copy and rename 4 of the other cards "13c.gif, 13d.gif, 13h.gif, 13s.gif. They will now work. Not ideal though unless the game you are using only uses 48 cards.

**Comment by shlomif** [comment]
Closing as FIXED for now.
