### ISSUE TITLE
Missing option: Save games geometry

### ISSUE THREAD

**Issue by THEtomaso** [shlomif/PySolFC#84]
In v2.0, there was this option called "Save games geometry", which let us save the window size:

![pysolfc-bug1](https://user-images.githubusercontent.com/9382674/41195979-bea732cc-6c26-11e8-9608-24a6f875ade7.jpg)

In v2.2, this option is nowhere to be found!

(Win8.1Pro,x64)

**Comment by shlomif** [comment]
@THEtomaso : hi! Sorry for the late reply. I saw that this option is displayed if-and-only-if PIL ( https://github.com/python-pillow/Pillow ) is **not** used. I dont know why this is the case.

**Comment by THEtomaso** [comment]
This issue needs looking into.

Here's a screenshot where I've resized the window, to enjoy the entire 'Paradise Wide' background image:

![pysolfc-bug2_1](https://user-images.githubusercontent.com/9382674/41811114-e3cbb3b6-76f8-11e8-9705-013b7c1daddc.jpg)

But of course, every time I start a new game, it gets resized to this:

![pysolfc-bug2_2](https://user-images.githubusercontent.com/9382674/41811118-f998edd0-76f8-11e8-9a4e-56aa5ddeac02.jpg)

**Comment by THEtomaso** [comment]
This option is still missing in v2.6.1.
Have anyone found some time to look into this issue?

**Comment by shlomif** [comment]
@THEtomaso : please try the build from https://ci.appveyor.com/project/shlomif/pysolfc/builds/23593633 - see the "artifacts" link. I may have fixed it there.

**Comment by THEtomaso** [comment]
Yes, I can confirm that the "Save games geometry" option is present in that build, and that it works! :+1: 

The default startup window looks like this though (which is something that should be addressed):

![pysolfc-bug3](https://user-images.githubusercontent.com/9382674/55577355-b558c680-5713-11e9-8728-e663389b39f9.jpg)

**Comment by shlomif** [comment]
@THEtomaso : thanks for checking. I'll try to fix the remaining issue.

**Comment by shlomif** [comment]
@THEtomaso : please try the build on https://ci.appveyor.com/project/shlomif/pysolfc/builds/23626755 - it should be fixed there.

**Comment by THEtomaso** [comment]
Yes, the new build defaults to a normal window now.
Great work! :)

Does these latest changes warrant a v2.6.3 release, or are there some other issues that needs to be fixed first too?

**Comment by shlomif** [comment]
> Yes, the new build defaults to a normal window now.
> Great work! :)

Thanks!

> 
> Does these latest changes warrant a v2.6.3 release, or are there some other issues that needs to be attended to first?
> 

I'd like to make a new release with that but would like to wait for https://github.com/shlomif/PySolFC/issues/108 first.

> --
> 
> **EDIT:**
> Also, I wonder..
> Have you ever considered to let the cardsets, and even the Cardset Maker, come bundled with the PySol installer?
> I mean, I can understand why these things were provided as separate downloads in the past, but times have changed in this regard.
> PySol's latest Windows installers are less than 20 MB.
> By todays standards, I don't think anyone would mind a 50 MB download.

That is an interesting thought. I'll consider it - thanks! @Programator2 : what do you think?

**Comment by shlomif** [comment]
Fixed in 2.6.3. Closing.
