### ISSUE TITLE
AppVeyor MS Windows Build is Broken

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#86]
Hi!

See https://ci.appveyor.com/project/shlomif/PySolFC/history . Seems like one of the deps broke backcompat. @Programator2 : any idea how to fix it?

**Comment by Programator2** [comment]
It looks that pygame developers are working on it:
https://github.com/pygame/pygame/issues/474

Until they sort it out, I downgraded pygame version to 1.9.3.

**Comment by illume** [comment]
pygame 1.9.4 wheels for python 3.4 on windows have been uploaded to pypi. Sorry for the bother.

**Comment by shlomif** [comment]
On Tue, 24 Jul 2018 13:15:12 -0700
René Dudfield <notifications@github.com> wrote:

> pygame 1.9.4 wheels for python 3.4 on windows have been uploaded to pypi.
> Sorry for the bother.
> 

Thanks for the headsup and the fix.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

Katie: in case you have any interest in me, I should note that I have a policy
against getting involved with people who are 4 times my senior or more.
    — http://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
