### ISSUE TITLE
Remove random2 dependency

### ISSUE THREAD

**Issue by hlef** [shlomif/PySolFC#88]
Dear pysolfc developers,

I'm a Debian Developer working on the pysolfc package. Yesterday I have looked into packaging the latest version of pysolfc and stumbled across the fact that random2 is not packaged into Debian. Unfortunately python-random2 is most likely not going to be packaged into Debian since it's not actively maintained, and its usefulness is very unclear.

What's exactly the reason why you needed to replace the random builtin ?

Thanks for your work.

**Comment by shlomif** [comment]
Hi Hugo!

On Tue, 31 Jul 2018 01:23:17 -0700
Hugo Lefeuvre <notifications@github.com> wrote:

> Dear pysolfc developers,
> 
> I'm a Debian Developer working on the pysolfc package. 

Thanks for that!

> Yesterday I have
> looked into packaging the latest version of pysolfc and stumbled across the
> fact that random2 is not packaged into Debian. Unfortunately python-random2
> is most likely not going to be packaged into Debian since it's not actively
> maintained, and its usefulness is very unclear.
> 

Well, random2 appears to work pretty well, and does not appear to have any show
stopping bugs. See
https://perl.plover.com/yak/12views/samples/notes.html#sl-9 . If necessary,
then I or someone else can resume maintaining it.

> What's exactly the reason why you needed to replace the random builtin ?
> 

The "import random" module broke back compat with itself, causing PySol FC,
which relies on it for some deal randomisation (which I believe was a poor
decision of the past maintainers) to generate different cards' arrangements for
the same deal indices. As this is unacceptable, we switched to use random2
which maintains the back compat.

There are several options:

1. Find a way to use random.py while yielding the old behaviour for both py
2.7 and py 3.x.

2. Embed random2 inside PySol FC (but note that it is also used by
https://github.com/shlomif/fc-solve/tree/master/fc-solve/source/board_gen
which is also part of debian)

3. Package random2.

4. Use class inheritance from random.py to locally revert the offending
behaviour.
 
> Thanks for your work.
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/ways_to_do_it.html

Summer Glau can get more with a kind word alone than Al Capone could with a
kind word and a gun.
    — http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hlef** [comment]
Hi Shlomi,

Thanks for the quick answer.

If I understand well, a game with seed 42 in the Python 3 version will not be the same as a game with seed 42 in the Python 2 version when using the new random module, right ?

If yes, what about the [version](https://docs.python.org/3/library/random.html#random.seed) parameter of `seed()` ?

**Comment by hlef** [comment]
If not, can you describe the expected behaviour (an example would be perfect) & point me to the related unit tests so I can understand what you mean ? That would be great.

**Comment by shlomif** [comment]
Hi Hugo,

On Wed, 01 Aug 2018 20:48:55 -0700
Hugo Lefeuvre <notifications@github.com> wrote:

> Hi Shlomi,
> 
> Thanks for the quick answer.
> 
> If I understand well, a game with seed 42 in the Python 3 version will not be
> the same as a game with seed 42 in the Python 2 version when using the new
> random module, right ?
> 

Well, it only affects deals above seed 32,000 (such as seed = 100000) but you
are right.

> If yes, what about the
> [version](https://docs.python.org/3/library/random.html#random.seed)
> parameter of `seed()` ?
> 

I tried it in a separate branch and the tests fail in py3:

PYTHONPATH="`pwd`/tests/lib:$PWD" python3 \
tests/unit-generated/test__pysol_tests.ms_deals1__v3.py



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Humour - http://perl-begin.org/humour/

Doing linear scans over an associative array is like trying to club someone to
death with a loaded Uzi.     — Larry Wall

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
On Wed, 01 Aug 2018 21:09:02 -0700
Hugo Lefeuvre <notifications@github.com> wrote:

> If not, can you describe the expected behaviour (an example would be perfect)
> & point me to the related unit tests so I can understand what you mean ? That
> would be great.
> 

See
https://github.com/shlomif/PySolFC/blob/master/tests/lib/pysol_tests/ms_deals1/__init__.py

The 
        rand = constructRandom('123456')
test fails with random instead of random2.
-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/lecture/C-and-CPP/bad-elements/

Knuth is not God! Unless you confuse him with Dijkstra.
    — http://www.shlomifish.org/humour/bits/facts/Knuth/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@hlef : see https://github.com/shlomif/PySolFC/tree/try-to-get-rid-of-random2.py - the tests currently fail there - both locally and on travis and appveyor. Any idea how to fix them?

**Comment by shlomif** [comment]
@hlef : ping!

**Comment by shlomif** [comment]
@hlef : I am closing this for now due to lack of response. I can reopen it.

**Comment by hlef** [comment]
FTR, I have packaged random2 for Debian. I don't like this solution, but that was the easiest one. I'm currently working on pysolfc packaging, hope we manage to get it ready in time for Buster.

**Comment by shlomif** [comment]
On Thu, 31 Jan 2019 06:05:22 -0800
Hugo Lefeuvre <notifications@github.com> wrote:

> FTR, I have packaged random2 for Debian. I don't like this solution, but that
> was the easiest one. I'm currently working on pysolfc packaging, hope we
> manage to get it ready in time for Buster.
> 

Thanks for doing that! Note that there are some improvements in the git master.
Do you want me to release a new version now?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/

I’d love to change the world, but they won’t give me the source code.
    — Unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hlef** [comment]
My Debian 2.5.5 update is almost ready, waiting for random2 to land into unstable. If you do a release now I will try to package it for Buster but can't guarantee anything.

By the way, I have noticed a few issues while preparing the Debian update, I'll submit a PR in the next days.

**Comment by shlomif** [comment]
On Thu, 31 Jan 2019 08:55:18 -0800
Hugo Lefeuvre <notifications@github.com> wrote:

> My Debian 2.5.5 update is almost ready, waiting for random2 to land into
> unstable. If you do a release now I will try to package it for Buster but
> can't guarantee anything.
> 
> By the way, I have noticed a few issues while preparing the Debian update,
> I'll submit a PR in the next days.
> 

2.5.x are dev releases - not stable ones. That put aside, they shuld be pretty
solid. I'll wait for your pull req

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/open-source/resources/tech-tips/

Happy Birthday! You'll be older than I in no time at this rate!
    — ED Curtis Curtis on Facebook

Please reply to list if it's a mailing list post - http://shlom.in/reply .
