### ISSUE TITLE
No more cardsets under data/

### ISSUE THREAD

**Issue by hlef** [shlomif/PySolFC#89]
Dear pysolfc developers,

Until the 2.0 release, some cardsets were released under the data/ directory. I have recently noticed that those are not present anymore on the most recent versions. This means that pysolfc is not "independent" anymore from pysolfc-cardsets, meaning that pysolfc-cardsets is a dependency now, right ?

This might be very annoying for users wanting to keep the number of installed cardsets minimal.

What is the reason for this removal ?

**Comment by shlomif** [comment]
On Tue, 31 Jul 2018 01:40:29 -0700
Hugo Lefeuvre <notifications@github.com> wrote:

> Dear pysolfc developers,
> 
> Until the 2.0 release, some cardsets were released under the data/ directory.
> I have recently noticed that those are not present anymore on the most recent
> versions. This means that pysolfc is not "independent" anymore from
> pysolfc-cardsets, meaning that pysolfc-cardsets is a dependency now, right ?
> 
> This might be very annoying for users wanting to keep the number of installed
> cardsets minimal.
> 
> What is the reason for this removal ?
> 

No good reason except for the fact that the original release and binary
building process was not fully documented or automated and may have been a bit
broken recently. A PR to fix this will be welcome.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Optimising Code for Speed - http://shlom.in/optimise

Objective jIronPerl++.NET Enterprise Edition♭ Professional Home Premium 64-bit
Single-user.
    — based on a Freenode #perl conversation ( http://is.gd/cCUBY2 )

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@Programator2 : hi! Any idea?

**Comment by Programator2** [comment]
@shlomif hi! I don't remember seeing cardsets in the repository. Previous maintainer was probably including cardsets when packaging the game.
There's a minimal list of cardsets that should be included in the [cardsets_to_bundle](https://github.com/shlomif/PySolFC/blob/master/scripts/cardsets_to_bundle) file. This list is used in the [appveyor script](https://github.com/shlomif/PySolFC/blob/de836fe5a06ea8de7627e03185fc94678c27e733/.appveyor.yml#L40) (lines 40-42) when building the Windows installer for the game.
@hlef You can use it similarly to include cardsets listed in the file when preparing the Debian package.

**Comment by shlomif** [comment]
On Wed, 01 Aug 2018 03:45:10 -0700
Roderik Ploszek <notifications@github.com> wrote:

> @shlomif hi! I don't remember seeing cardsets in the repository. Previous
> maintainer was probably including cardsets when packaging the game. There's a
> minimal list of cardsets that should be included in the
> [cardsets_to_bundle](https://github.com/shlomif/PySolFC/blob/master/scripts/cardsets_to_bundle)
> file. This list is used in the [appveyor
> script](https://github.com/shlomif/PySolFC/blob/de836fe5a06ea8de7627e03185fc94678c27e733/.appveyor.yml#L40)
> (lines 40-42) when building the Windows installer for the game. @hlef You can
> use it similarly to include cardsets listed in the file when preparing the
> Debian package.
> 

Thanks for the advice!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Original Riddles - http://www.shlomifish.org/puzzles/

You name it — COBOL does not have it.
    — http://is.gd/ClKAz5

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hlef** [comment]
@Programator2 Yes, I will repack the tarball if necessary. But I usually prefer not doing it when the changes can be made upstream.

**Comment by shlomif** [comment]
@hlef: I think we can create a separate tarball of just those cardsets. Will it be an ok solution?

**Comment by shlomif** [comment]
@hlef : ping!

**Comment by jnumm** [comment]
This issue is solved: at least Debian and Fedora are now successfully using the minimal cardsets tarball.
