### ISSUE TITLE
upgrade to python3 ? 

### ISSUE THREAD

**Issue by sergiomb2** [shlomif/PySolFC#91]
Have you any plan / scheduled  to migrate this project to python3 ? 

Thanks

**Comment by shlomif** [comment]
@sergiomb2 : PySol FC's code supports both python 3.x as well as python 2.7, and seems to run fine on [pypy](http://pypy.org/) as well. See https://github.com/shlomif/PySolFC/issues/11 . That information about the support in the 2.1.0 release seems to be elided on [the site](https://pysolfc.sourceforge.io/) so I may need to fix it.

**Comment by shlomif** [comment]
Closing as it is fixed/invalid.
