### ISSUE TITLE
Error on Android 4.2.2

### ISSUE THREAD

**Issue by Imprecator** [shlomif/PySolFC#92]
SDL error: could not load any libpythonxxx.so

**Comment by shlomif** [comment]
Hi! Sorry for the late reply, @lufebe16 : can you help?

**Comment by lufebe16** [comment]
The android version of pysolfc is compiled for API 19, corresponding to Android 4.4 (Kitkat). Its the standard setting with the available build system 'python-for-android'. Tested on available devices, i.e Android 6 (marshmallow) and 7 (nougat).  There is no plan to support older OSes.

**Comment by shlomif** [comment]
@lufebe16 : thanks, closing as wontfix then.
