### ISSUE TITLE
pip install error: can't copy 'locale/ru/LC_MESSAGES/pysol.mo': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by nobrowser** [shlomif/PySolFC#94]
Trying to install via python 3 and pip on Fedora 28 (python 3.6.6), I get the output in the attached record (warning: long).  This was with the 2.4.0 tarball, but exactly the same happens with master if I try to pip directly from git.

[pip-output.txt.gz](https://github.com/shlomif/PySolFC/files/2493956/pip-output.txt.gz)

**Comment by Programator2** [comment]
Hi.

When you install PySol like this, message catalogs for locales are not compiled and setup.py can't find them.

Follow [instructions in readme](https://github.com/shlomif/PySolFC#running-from-source-without-installation) on how to build PySol.

**Comment by nobrowser** [comment]
Requiring users to run from the source tree is a horrible practice which I thought was only specific to academic projects with no engineering experience at all.
If the catalogs are not being built, why is that?  How hard is it to add that step to setup.py ?
I'll see if I can put together a patch.

**Comment by shlomif** [comment]
On Fri, 19 Oct 2018 15:40:36 -0700
Ian Zimmerman <notifications@github.com> wrote:

> Requiring users to run from the source tree is a horrible practice which I
> thought was only specific to academic projects with no engineering experience
> at all. If the catalogs are not being built, why is that?  How hard is it to
> add that step to setup.py ? I'll see if I can put together a patch.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Processing Tools - http://shlom.in/text-proc

Chuck Norris reads all messages posted to LKML (= the Linux Kernel Mailing
List), understands them all, and he kills all gnomes he sees in sight.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by nobrowser** [comment]
Nice avatar, shlomif :-)

**Comment by shlomif** [comment]
On Sat, 20 Oct 2018 01:18:05 -0700
Ian Zimmerman <notifications@github.com> wrote:

> Nice avatar, shlomif :-)
> 

thanks - see https://www.shlomifish.org/meta/FAQ/#evilphish-emblem .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/open-source/resources/tech-tips/

I started out as a BASIC programmer. Some people would say that I’m
permanently damaged. Some people are undoubtedly right.
    — Larry Wall

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by nobrowser** [comment]
And how good of you to credit the original designer.  I shot the picture I'm using here myself, but in the past I have used others' pictures without giving them credit :-(

And now to the actual issue.  I probed around a little, and eventually I hit [1] which fills me with utter hopelessness, so I'm OK with closing this, and playing patience with paper cards for a while.  By the way, the reason I wanted a venv is my distro [2] messed up the dependencies, and now their PySol package requires an obsolete version of pygame.

Notes:

1.  [cannot install pygtk in a venv](https://stackoverflow.com/questions/9064289/installing-pygtk-in-virtualenv)

2. Fedora 28

**Comment by nobrowser** [comment]
Ok, I hacked up something basic, see PR #95

**Comment by shlomif** [comment]
On Sun, 21 Oct 2018 14:08:17 -0700
Ian Zimmerman <notifications@github.com> wrote:

> Ok, I hacked up something basic, see PR #95
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Best Introductory Programming Language - http://shlom.in/intro-lang

If it isn’t in my email, it doesn’t exist.

And if the whole world says one thing and my email says something different,
email will conquer.

    — an Israeli Linuxer.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by snoopy-coder** [comment]
> When you install PySol like this, message catalogs for locales are not compiled and setup.py can't find them.

I dare to offer you my solution to this problem. It's for Windows, but I think it will work in other OS.
```
--- C:/Temp/PySolFC-pysolfc-2.6.2/pysollib/mygettext.py.bak	Wed Feb 27 23:52:26 2019
+++ C:/Temp/PySolFC-pysolfc-2.6.2/pysollib/mygettext.py	Wed Mar  6 21:14:52 2019
@@ -1,4 +1,5 @@
 import gettext
+import os
 import sys
 
 import six
@@ -17,7 +18,8 @@
     domain = gettext._current_domain
     try:
         t = gettext.translation(domain,
-                                gettext._localedirs.get(domain, None))
+#                                gettext._localedirs.get(domain, None))
+            os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'locale'))
     except IOError:
         if n == 1:
             return msgid1
@@ -37,7 +39,8 @@
         domain = gettext._current_domain
         try:
             t = gettext.translation(domain,
-                                    gettext._localedirs.get(domain, None))
+#                                    gettext._localedirs.get(domain, None))
+            os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'locale'))
         except IOError:
             return message
         if sys.version_info >= (3, 0):
```

**Comment by shlomif** [comment]
Closing for now.

**Comment by jnumm** [comment]
I believe this problem can be considered fixed in https://github.com/shlomif/PySolFC/commit/5062f0e0d92a06e44a8385380750f457d77a9dc9: if you don't build the .mo files in advance, setup.py won't try to install them.
